import { describe, expect, it } from "vitest";
import { assignSupportCase, buildCustomer360, closeSupportCase, openSupportCase, recordComplaintOutcome, resolveSupportCase, startInvestigation, supportCaseSla, type CustomerProfile } from "./index";

const customer: CustomerProfile = { customerId: "CUS-1", principalId: "PRI-1", organisationId: "ORG-1", state: "ACTIVE", country: "GB", region: "England", currency: "GBP", profileVersion: 4 };
const opened = (kind: "SUPPORT" | "COMPLAINT" | "DATA_CORRECTION" = "COMPLAINT") => openSupportCase({ caseId: "CASE-1", organisationId: "ORG-1", customerId: "CUS-1", kind, summary: "Invoice disputed", openedAt: "2026-08-27T09:00:00.000Z", dueAt: "2026-08-29T09:00:00.000Z", actorId: "support-1", actorRole: "CS" });
const investigating = (kind: "SUPPORT" | "COMPLAINT" | "DATA_CORRECTION" = "COMPLAINT") => startInvestigation(assignSupportCase(opened(kind), { organisationId: "ORG-1", ownerId: "case-owner", actorId: "support-1", actorRole: "CS", occurredAt: "2026-08-27T09:05:00.000Z" }), { organisationId: "ORG-1", actorId: "case-owner", actorRole: "CS", occurredAt: "2026-08-27T09:10:00.000Z", evidenceIds: ["INV-1"] });

describe("Customer 360 and support cases", () => {
  it("assembles tenant-scoped customer context without merging identities", () => expect(buildCustomer360({ organisationId: "ORG-1", customer, walletIds: ["WAL-1"], invoiceIds: ["INV-1"], evidenceIds: ["AUD-1"] })).toMatchObject({ customer: { principalId: "PRI-1", profileVersion: 4 }, walletIds: ["WAL-1"], invoiceIds: ["INV-1"] }));
  it("rejects cross-tenant customer or consent evidence", () => { expect(() => buildCustomer360({ organisationId: "ORG-2", customer })).toThrow(/Cross-tenant/); expect(() => buildCustomer360({ organisationId: "ORG-1", customer, consents: [{ consentId: "C-1", customerId: "CUS-1", organisationId: "ORG-2", type: "PRIVACY", version: 1, textHash: "hash", accepted: true, channel: "WEB", recordedAt: "2026-08-01" }] })).toThrow(/Cross-tenant/); });
  it("opens complaints with an explicit SLA and immutable event", () => expect(opened()).toMatchObject({ supportCase: { state: "OPEN", dueAt: "2026-08-29T09:00:00.000Z", version: 1 }, events: [{ action: "OPENED", immutable: true }] }));
  it("assigns and investigates with evidence", () => expect(investigating()).toMatchObject({ supportCase: { state: "INVESTIGATING", ownerId: "case-owner", version: 3 }, events: [{}, {}, { action: "INVESTIGATION_STARTED", evidenceIds: ["INV-1"] }] }));
  it("blocks cross-tenant case access", () => expect(() => assignSupportCase(opened(), { organisationId: "ORG-2", ownerId: "owner", actorId: "support", actorRole: "CS", occurredAt: "2026-08-27T09:05:00Z" })).toThrow(/Cross-tenant/));
  it("requires compliance to resolve complaints and sensitive corrections", () => { const input = { organisationId: "ORG-1", actorId: "support", actorRole: "CS" as const, occurredAt: "2026-08-27T10:00:00Z", resolution: "Corrected", evidenceIds: ["EVD-1"] }; expect(() => resolveSupportCase(investigating(), input)).toThrow(/Compliance/); expect(() => resolveSupportCase(investigating("DATA_CORRECTION"), input)).toThrow(/Compliance/); });
  it("allows support to resolve non-sensitive support cases", () => expect(resolveSupportCase(investigating("SUPPORT"), { organisationId: "ORG-1", actorId: "support", actorRole: "CS", occurredAt: "2026-08-27T10:00:00Z", resolution: "Explained invoice", evidenceIds: ["EVD-1"] }).supportCase.state).toBe("RESOLVED"));
  it("requires complaint outcome evidence before closure", () => { const resolved = resolveSupportCase(investigating(), { organisationId: "ORG-1", actorId: "compliance", actorRole: "CF", occurredAt: "2026-08-27T10:00:00Z", resolution: "Complaint upheld", evidenceIds: ["EVD-RES"] }); expect(() => closeSupportCase(resolved, { organisationId: "ORG-1", actorId: "support", actorRole: "CS", occurredAt: "2026-08-27T10:30:00Z" })).toThrow(/outcome/); const notified = recordComplaintOutcome(resolved, { organisationId: "ORG-1", actorId: "support", actorRole: "CS", occurredAt: "2026-08-27T10:20:00Z", evidenceId: "COMM-1" }); expect(closeSupportCase(notified, { organisationId: "ORG-1", actorId: "support", actorRole: "CS", occurredAt: "2026-08-27T10:30:00Z" }).supportCase.state).toBe("CLOSED"); });
  it("reports due-soon, breached and complete SLA states", () => { expect(supportCaseSla(opened().supportCase, "2026-08-28T12:00:00Z")).toBe("DUE_SOON"); expect(supportCaseSla(opened().supportCase, "2026-08-30T00:00:00Z")).toBe("BREACHED"); const supportResolved = resolveSupportCase(investigating("SUPPORT"), { organisationId: "ORG-1", actorId: "support", actorRole: "CS", occurredAt: "2026-08-27T10:00:00Z", resolution: "Done", evidenceIds: ["EVD"] }); const closed = closeSupportCase(supportResolved, { organisationId: "ORG-1", actorId: "support", actorRole: "CS", occurredAt: "2026-08-27T11:00:00Z" }); expect(supportCaseSla(closed.supportCase, "2026-08-30T00:00:00Z")).toBe("COMPLETE"); });
  it("preserves prior case history values across transitions", () => { const initial = opened(); const assigned = assignSupportCase(initial, { organisationId: "ORG-1", ownerId: "owner", actorId: "support", actorRole: "CS", occurredAt: "2026-08-27T09:05:00Z" }); expect(initial.supportCase).toMatchObject({ state: "OPEN", ownerId: null, version: 1 }); expect(assigned.supportCase).toMatchObject({ state: "ASSIGNED", ownerId: "owner", version: 2 }); });
});
