import { describe, expect, it } from "vitest";
import { createLedgerState, createReversalCommand, minorUnitScale, postJournal, projectAccounts, reconcileSafeguarding, verifyLedgerIntegrity, type LedgerAccount, type PostJournalCommand } from "./index";

const entity = "FC-US-INC";
const accounts: readonly LedgerAccount[] = [
  { accountId: "cash-usd", legalEntityId: entity, currency: "USD", type: "ASSET", normalBalance: "DEBIT", purpose: "SAFEGUARDED_CASH" },
  { accountId: "available-usd", legalEntityId: entity, currency: "USD", type: "LIABILITY", normalBalance: "CREDIT", purpose: "CUSTOMER_AVAILABLE" },
  { accountId: "reserved-usd", legalEntityId: entity, currency: "USD", type: "LIABILITY", normalBalance: "CREDIT", purpose: "CUSTOMER_RESERVED" },
  { accountId: "claim-usd", legalEntityId: entity, currency: "USD", type: "EXPENSE", normalBalance: "DEBIT", purpose: "PROTECTION_CLAIM" },
  { accountId: "station-usd", legalEntityId: entity, currency: "USD", type: "LIABILITY", normalBalance: "CREDIT", purpose: "STATION_PAYABLE" },
  { accountId: "bridge-usd", legalEntityId: entity, currency: "USD", type: "LIABILITY", normalBalance: "CREDIT", purpose: "FX_BRIDGE" },
  { accountId: "cash-cad", legalEntityId: entity, currency: "CAD", type: "ASSET", normalBalance: "DEBIT", purpose: "PROCESSOR_CLEARING" },
  { accountId: "bridge-cad", legalEntityId: entity, currency: "CAD", type: "LIABILITY", normalBalance: "CREDIT", purpose: "FX_BRIDGE" },
];
const lineage = { organisationId: "ORG-1", legalEntityId: entity, market: "US-TX", sourceContractId: "SETTLEMENT-1", rulesVersion: "rules-engine@1.0.0", scenarioId: "rise-within-boundary-us", externalReference: "FILL-1", actorId: "system-settlement", correlationId: "CORR-1" } as const;
const settlement = (overrides: Partial<PostJournalCommand> = {}): PostJournalCommand => ({ commandId: "CMD-1", idempotencyKey: "settle:FILL-1", journalId: "JRN-1", transactionId: "TXN-1", eventType: "FUEL_SETTLED", postedAt: "2026-08-26T14:00:00.000Z", lines: [{ lineId: "L1", accountId: "reserved-usd", currency: "USD", side: "DEBIT", amountMinor: 7_350 }, { lineId: "L2", accountId: "claim-usd", currency: "USD", side: "DEBIT", amountMinor: 450 }, { lineId: "L3", accountId: "station-usd", currency: "USD", side: "CREDIT", amountMinor: 7_800 }], positionMovements: [{ movementId: "M1", positionId: "POS-1", fuelProductId: "US-TX-REGULAR", type: "REDEEM", quantity4dp: 200_000 }], lineage, correctionOf: null, ...overrides });

describe("authoritative ledger", () => {
  it("posts the canonical settlement atomically when each currency balances", () => { const result = postJournal(createLedgerState("LEDGER-1", accounts), settlement()); expect(result.journal.sequence).toBe(1); expect(result.state.journals).toHaveLength(1); expect(result.idempotentReplay).toBe(false); });
  it("rejects an unbalanced journal without changing input state", () => { const state = createLedgerState("LEDGER-1", accounts); expect(() => postJournal(state, settlement({ lines: settlement().lines.slice(0, 2) }))).toThrow(/balance independently/i); expect(state.journals).toHaveLength(0); });
  it("balances source and destination currencies independently", () => { const fx = settlement({ commandId: "FX", idempotencyKey: "fx:1", journalId: "JRN-FX", eventType: "FX_CONVERTED", lines: [{ lineId: "U1", accountId: "cash-usd", currency: "USD", side: "CREDIT", amountMinor: 10_000 }, { lineId: "U2", accountId: "bridge-usd", currency: "USD", side: "DEBIT", amountMinor: 10_000 }, { lineId: "C1", accountId: "cash-cad", currency: "CAD", side: "DEBIT", amountMinor: 13_767 }, { lineId: "C2", accountId: "bridge-cad", currency: "CAD", side: "CREDIT", amountMinor: 13_767 }], positionMovements: [] }); expect(postJournal(createLedgerState("LEDGER-1", accounts), fx).journal.lines).toHaveLength(4); });
  it("returns the original posting on an exact idempotent retry", () => { const first = postJournal(createLedgerState("LEDGER-1", accounts), settlement()); const retry = postJournal(first.state, settlement()); expect(retry.idempotentReplay).toBe(true); expect(retry.state).toBe(first.state); expect(retry.journal).toBe(first.journal); });
  it("rejects idempotency-key reuse with different economics", () => { const first = postJournal(createLedgerState("LEDGER-1", accounts), settlement()); expect(() => postJournal(first.state, settlement({ commandId: "CMD-DIFFERENT" }))).toThrow(/different command/i); });
  it("creates a monotonic tamper-evident hash chain", () => { const first = postJournal(createLedgerState("LEDGER-1", accounts), settlement()); const second = postJournal(first.state, settlement({ commandId: "CMD-2", idempotencyKey: "settle:FILL-2", journalId: "JRN-2", transactionId: "TXN-2" })); expect(second.journal.sequence).toBe(2); expect(second.journal.previousHash).toBe(first.journal.integrityHash); expect(verifyLedgerIntegrity(second.state)).toBe(true); });
  it("detects journal tampering during integrity verification", () => { const posted = postJournal(createLedgerState("LEDGER-1", accounts), settlement()); const tampered = { ...posted.state, journals: [{ ...posted.journal, eventType: "ALTERED" }] }; expect(verifyLedgerIntegrity(tampered)).toBe(false); });
  it("rebuilds disposable account projections solely from journals", () => { const posted = postJournal(createLedgerState("LEDGER-1", accounts), settlement()); expect(projectAccounts(posted.state).find(({ accountId }) => accountId === "station-usd")).toMatchObject({ creditsMinor: 7_800, balanceMinor: 7_800 }); });
  it("reconciles safeguarding by legal entity and currency", () => { const funding = settlement({ commandId: "FUND", idempotencyKey: "fund:1", journalId: "JRN-FUND", eventType: "CUSTOMER_FUNDED", lines: [{ lineId: "F1", accountId: "cash-usd", currency: "USD", side: "DEBIT", amountMinor: 10_000 }, { lineId: "F2", accountId: "available-usd", currency: "USD", side: "CREDIT", amountMinor: 10_000 }], positionMovements: [] }); const posted = postJournal(createLedgerState("LEDGER-1", accounts), funding); expect(reconcileSafeguarding(posted.state, entity, "USD", 0)).toMatchObject({ status: "PASS", differenceMinor: 0 }); expect(reconcileSafeguarding(posted.state, entity, "USD", -1)).toMatchObject({ status: "BREAK", differenceMinor: -1 }); });
  it("retains protected quantity at four-decimal fixed precision", () => expect(postJournal(createLedgerState("LEDGER-1", accounts), settlement()).journal.positionMovements[0]).toMatchObject({ quantity4dp: 200_000, type: "REDEEM" }));
  it("creates a linked maker-checker reversal instead of editing history", () => { const posted = postJournal(createLedgerState("LEDGER-1", accounts), settlement()); const reversal = createReversalCommand(posted.journal, { commandId: "REV", idempotencyKey: "reverse:JRN-1", journalId: "JRN-REV", transactionId: "TXN-REV", postedAt: "2026-08-26T14:01:00.000Z", actorId: "finance-maker", approverId: "finance-checker", reason: "Matched correction evidence" }); const reversed = postJournal(posted.state, reversal); expect(reversed.journal.correctionOf).toBe("JRN-1"); expect(projectAccounts(reversed.state).every(({ balanceMinor }) => balanceMinor === 0)).toBe(true); expect(posted.journal.correctionOf).toBeNull(); });
  it("enforces explicit currency scales and typed account normal balances", () => { expect(minorUnitScale("USD")).toBe(2); expect(() => createLedgerState("BAD", [{ ...accounts[0]!, normalBalance: "CREDIT" }])).toThrow(/normal balance/i); });
});
