import { describe, expect, it } from "vitest";
import { authorizeIntegrationEnvironment, createFuelIngestionEnvelope, createMessageDispatchInstruction, normalizeDeliveryReceipt, type DeliveryReceipt, type FuelProviderRecord, type MessageDispatchRequest } from "./index";

const blockedGate = { decision: "BLOCKED" as const, evaluatedAt: "2026-08-27T00:00:00Z", passedControlIds: [], blockers: ["approvals open"], productionCredentialsMayBeProvisioned: false, auditEvidenceIds: [] };
const readyGate = { ...blockedGate, decision: "READY" as const, blockers: [], productionCredentialsMayBeProvisioned: true };
const fuel: FuelProviderRecord = { eventId: "FP-1", providerId: "PROVIDER-1", environment: "SANDBOX", adapterVersion: "adapter@1", correlationId: "CORR-1", receivedAt: "2026-08-27T12:00:00Z", signatureVerified: true, payloadHash: "sha256:fuel-1", licenceEvidenceId: "LIC-1", licenceStatus: "APPROVED", raw: { rawRecordId: "RAW-1", providerStationReference: "ST-1", providerProductReference: "UNL", observedAt: "2026-08-27T11:59:00Z", receivedAt: "2026-08-27T12:00:00Z", priceDecimal: "1.4590", currency: "GBP", unit: "LITRE", kind: "ACTUAL_PUMP", requestedUses: ["DISPLAY", "QUOTE"] } };
const message: MessageDispatchRequest = { communicationId: "COMM-1", organisationId: "ORG-1", recipientId: "CUS-1", environment: "SANDBOX", communicationClass: "REQUIRED", channel: "EMAIL", templateId: "TPL-1", templateVersion: "tpl@1", templateApproved: true, renderedContentHash: "sha256:rendered", idempotencyKey: "comm:1", outboxCommittedAtomically: true, preference: { organisationId: "ORG-1", recipientId: "CUS-1", version: "pref@1", marketingAllowed: false, availableChannels: ["EMAIL", "IN_APP"] } };
const receipt: DeliveryReceipt = { providerEventId: "MSG-EVT-1", communicationId: "COMM-1", organisationId: "ORG-1", environment: "SANDBOX", state: "DELIVERED", occurredAt: "2026-08-27T12:01:00Z", signatureVerified: true, payloadHash: "sha256:receipt", providerReference: "provider-msg-1" };

describe("fuel-price and messaging adapters", () => {
  it("creates an authenticated sandbox ingestion envelope without selecting a canonical price", () => expect(createFuelIngestionEnvelope(fuel, blockedGate)).toMatchObject({ envelopeId: "fuel:FP-1", schemaVersion: "pricing-ingestion@1.0.0", rawPayloadHash: "sha256:fuel-1" }));
  it("requires current approved fuel-data licence evidence", () => { expect(() => createFuelIngestionEnvelope({ ...fuel, licenceStatus: "OPEN" }, blockedGate)).toThrow(/licence/); expect(() => createFuelIngestionEnvelope({ ...fuel, licenceStatus: "EXPIRED" }, blockedGate)).toThrow(/licence/); });
  it("rejects unsigned, unhashed and replayed fuel events", () => { expect(() => createFuelIngestionEnvelope({ ...fuel, signatureVerified: false }, blockedGate)).toThrow(/Authenticated/); expect(() => createFuelIngestionEnvelope({ ...fuel, payloadHash: "bad" as `sha256:${string}` }, blockedGate)).toThrow(/content-addressed/); expect(() => createFuelIngestionEnvelope(fuel, blockedGate, new Set([fuel.eventId]))).toThrow(/Duplicate/); });
  it("blocks production fuel and messaging while P6-001 is blocked", () => { expect(() => createFuelIngestionEnvelope({ ...fuel, environment: "PRODUCTION" }, blockedGate)).toThrow(/P6-001/); expect(() => createMessageDispatchInstruction({ ...message, environment: "PRODUCTION" }, blockedGate)).toThrow(/P6-001/); });
  it("permits production boundaries only after the launch gate passes", () => { expect(() => authorizeIntegrationEnvironment("PRODUCTION", readyGate, "FUEL_PRICE")).not.toThrow(); expect(() => authorizeIntegrationEnvironment("PRODUCTION", readyGate, "MESSAGING")).not.toThrow(); });
  it("creates immutable worker-authorized dispatch instructions, never direct sends", () => expect(createMessageDispatchInstruction(message, blockedGate)).toMatchObject({ canSendDirectly: false, requiresWorkerAuthorization: true, immutable: true, preferenceVersion: "pref@1" }));
  it("requires approved templates and atomic outbox intent", () => { expect(() => createMessageDispatchInstruction({ ...message, templateApproved: false }, blockedGate)).toThrow(/Approved/); expect(() => createMessageDispatchInstruction({ ...message, outboxCommittedAtomically: false }, blockedGate)).toThrow(/outbox/); });
  it("suppresses duplicate dispatch and unavailable channels", () => { expect(() => createMessageDispatchInstruction(message, blockedGate, new Set([message.idempotencyKey]))).toThrow(/Duplicate/); expect(() => createMessageDispatchInstruction({ ...message, channel: "SMS" }, blockedGate)).toThrow(/unavailable/); });
  it("requires consent for marketing but not required notices", () => { expect(() => createMessageDispatchInstruction({ ...message, communicationClass: "MARKETING" }, blockedGate)).toThrow(/consent/); expect(createMessageDispatchInstruction(message, blockedGate).communicationId).toBe("COMM-1"); });
  it("rejects cross-tenant recipient preferences", () => expect(() => createMessageDispatchInstruction({ ...message, preference: { ...message.preference, organisationId: "ORG-2" } }, blockedGate)).toThrow(/scope/));
  it("normalizes signed tenant-matched delivery receipts", () => expect(normalizeDeliveryReceipt(receipt, blockedGate, { organisationId: "ORG-1", communicationId: "COMM-1" })).toMatchObject({ state: "DELIVERED", immutable: true }));
  it("rejects mismatched or replayed delivery receipts", () => { expect(() => normalizeDeliveryReceipt(receipt, blockedGate, { organisationId: "ORG-2", communicationId: "COMM-1" })).toThrow(/does not match/); expect(() => normalizeDeliveryReceipt(receipt, blockedGate, { organisationId: "ORG-1", communicationId: "COMM-1" }, new Set([receipt.providerEventId]))).toThrow(/Duplicate/); });
});
