export type Vehicle={vehicleId:string;organisationId:string;groupId:string;country:string;region:string;currency:"USD"|"CAD"|"GBP";status:"ACTIVE"|"RESTRICTED"|"RETIRED"};
export type Assignment={assignmentId:string;organisationId:string;vehicleId:string;driverId:string;effectiveFrom:string;effectiveTo:string|null};
export type FleetPolicy={policyId:string;version:number;organisationId:string;groupId:string;effectiveFrom:string;effectiveTo:string|null;perVehicleLimit4dp:number;organisationLimit4dp:number;autoRollover:boolean};
export type FleetState={vehicles:readonly Vehicle[];assignments:readonly Assignment[];policies:readonly FleetPolicy[]};
const active=(from:string,to:string|null,at:number)=>Date.parse(from)<=at&&(to===null||at<Date.parse(to));
export function createFleetState(input:FleetState):FleetState { const ids=[...input.vehicles.map(x=>x.vehicleId),...input.assignments.map(x=>x.assignmentId),...input.policies.map(x=>x.policyId+":"+x.version)]; if(new Set(ids).size!==ids.length)throw new Error("Fleet record identities must be unique."); return structuredClone(input); }
export function policyAt(state:FleetState,organisationId:string,vehicleId:string,at:string):FleetPolicy { const vehicle=state.vehicles.find(v=>v.vehicleId===vehicleId&&v.organisationId===organisationId); if(!vehicle)throw new Error("Vehicle is outside the active organisation."); const time=Date.parse(at); const policies=state.policies.filter(p=>p.organisationId===organisationId&&p.groupId===vehicle.groupId&&active(p.effectiveFrom,p.effectiveTo,time)).sort((a,b)=>b.version-a.version); if(!policies[0])throw new Error("No effective vehicle-group policy."); return policies[0]; }
export function driverAssignmentAt(state:FleetState,organisationId:string,vehicleId:string,at:string):Assignment { const time=Date.parse(at); const matches=state.assignments.filter(a=>a.organisationId===organisationId&&a.vehicleId===vehicleId&&active(a.effectiveFrom,a.effectiveTo,time)); if(matches.length!==1)throw new Error("Exactly one effective driver assignment is required."); return matches[0]!; }
export function evaluateFleetLimit(state:FleetState,input:{organisationId:string;vehicleId:string;requested4dp:number;vehicleUsed4dp:number;organisationUsed4dp:number;at:string}) { const vehicle=state.vehicles.find(v=>v.vehicleId===input.vehicleId&&v.organisationId===input.organisationId); if(!vehicle||vehicle.status!=="ACTIVE")return {allowed:false,reason:"VEHICLE_NOT_ACTIVE" as const}; const policy=policyAt(state,input.organisationId,input.vehicleId,input.at); if(input.vehicleUsed4dp+input.requested4dp>policy.perVehicleLimit4dp)return {allowed:false,reason:"VEHICLE_LIMIT_EXCEEDED" as const,policy}; if(input.organisationUsed4dp+input.requested4dp>policy.organisationLimit4dp)return {allowed:false,reason:"ORGANISATION_LIMIT_EXCEEDED" as const,policy}; return {allowed:true,reason:"ALLOWED" as const,policy}; }
export function publishPolicy(state:FleetState,actorOrganisationId:string,policy:FleetPolicy,now:string):FleetState { if(actorOrganisationId!==policy.organisationId)throw new Error("Cross-tenant policy administration is prohibited."); if(Date.parse(policy.effectiveFrom)<Date.parse(now))throw new Error("Fleet policy changes must be prospective."); if(policy.perVehicleLimit4dp<=0||policy.organisationLimit4dp<policy.perVehicleLimit4dp)throw new Error("Fleet limits are invalid."); return {...state,policies:[...state.policies,{...policy}]}; }
