"use client";

import { useState } from "react";
import { Activity, BarChart3, CheckCircle2, FlaskConical, LockKeyhole, ShieldCheck, TrendingUp } from "lucide-react";
import { authorize, type Environment, type Principal } from "@fuelcap/authz";
import { seededBasisDecision, seededBasisObservations, seededBasisPolicy, seededPublishedBasisModel, type BasisCandidateResult } from "@fuelcap/basis-model";

const selected = seededBasisDecision.candidates.find(({candidateId})=>candidateId===seededBasisDecision.selectedCandidateId)!;
const basis = (value:number|null) => value === null ? "—" : `${value < 0 ? "−" : ""}${(Math.abs(value)/10_000).toFixed(4)}`;
const error = (value:number|null) => value === null ? "—" : (value/10_000).toFixed(4);

export function BasisModelWorkspace({organisationId,principal,environment}:{organisationId:string;principal:Principal;environment:Environment}){
  const [candidate,setCandidate]=useState<BasisCandidateResult>(selected);
  const [action,setAction]=useState<"idle"|"drafted"|"denied">("idle");
  function draftRecalibration(){const permission=authorize({principal,environment,activeOrganisationId:organisationId,workspace:"pricing-data",verb:"initiate"});setAction(permission.allowed?"drafted":"denied");}
  return <section className="basis-model" aria-labelledby="basis-model-title">
    <div className="section-heading basis-model__heading"><div><span className="section-kicker">P7-002 · deterministic optimisation</span><h2 id="basis-model-title">Retail–wholesale basis model</h2><p>Signed basis is retail exposure minus wholesale hedge price. This simulation does not change quotes or execute hedges.</p></div><span className="pricing-blocked">Simulation only</span></div>
    <div className="basis-model__metrics"><article><TrendingUp size={17}/><span>Selected forecast</span><strong>{basis(seededBasisDecision.selectedForecastBasisMinor4)}</strong><small>signed currency units</small></article><article><BarChart3 size={17}/><span>Holdout MAE</span><strong>{error(selected.meanAbsoluteErrorMinor4)}</strong><small>4 unseen periods</small></article><article><Activity size={17}/><span>Maximum error</span><strong>{error(selected.maximumAbsoluteErrorMinor4)}</strong><small>limit {error(seededBasisPolicy.maximumAbsoluteErrorMinor4)}</small></article><article><CheckCircle2 size={17}/><span>Published model</span><strong>{seededPublishedBasisModel.state}</strong><small>{seededPublishedBasisModel.modelId}</small></article></div>
    <div className="basis-model__layout"><div className="basis-model__candidates"><div className="section-heading"><div><span className="section-kicker">No-lookahead backtest</span><h3>Candidate comparison</h3></div><span className="tenant-chip">{seededBasisDecision.candidates.length} transparent candidates</span></div><div className="basis-model__candidate-list">{seededBasisDecision.candidates.map((item)=><button key={item.candidateId} className={candidate.candidateId===item.candidateId?"basis-model__candidate--active":""} type="button" onClick={()=>setCandidate(item)}><span><strong>{item.strategy.replace("ROLLING_","")}</strong><small>{item.windowSize}-period rolling window</small></span><span><small>MAE</small><strong>{error(item.meanAbsoluteErrorMinor4)}</strong></span><span><small>Bias</small><strong>{basis(item.signedBiasMinor4)}</strong></span><b>{item.candidateId===seededBasisDecision.selectedCandidateId?"SELECTED":item.status}</b></button>)}</div></div>
      <aside className="basis-model__evidence"><span className="section-kicker">Candidate evidence</span><h3>{candidate.candidateId}</h3><dl><div><dt>Holdout periods</dt><dd>{candidate.holdoutCount}</dd></div><div><dt>Mean absolute error</dt><dd>{error(candidate.meanAbsoluteErrorMinor4)}</dd></div><div><dt>Maximum error</dt><dd>{error(candidate.maximumAbsoluteErrorMinor4)}</dd></div><div><dt>Signed bias</dt><dd>{basis(candidate.signedBiasMinor4)}</dd></div><div><dt>Next basis forecast</dt><dd>{basis(candidate.forecastBasisMinor4)}</dd></div><div><dt>Evidence references</dt><dd>{candidate.evidenceIds.length}</dd></div></dl><div className="basis-model__boundary"><LockKeyhole size={15}/><span>12 synthetic observations · 4 holdout periods · no future data · fixed-point arithmetic.</span></div></aside></div>
    <div className="basis-model__governance"><FlaskConical size={18}/><div><span className="section-kicker">Governed publication</span><strong>{seededPublishedBasisModel.makerId} → {seededPublishedBasisModel.checkerId}</strong><small>Exact digest · step-up approval · DISPLAY / SIMULATE · rollback required for replacement</small></div><button type="button" onClick={draftRecalibration}><ShieldCheck size={14}/> Draft recalibration</button></div>
    {action!=="idle"&&<div className={`customer-review-result customer-review-result--${action==="drafted"?"submitted":"denied"}`} role="status"><strong>{action==="drafted"?"Recalibration proposal drafted":"Permission denied"}</strong><span>{action==="drafted"?`A new ${seededBasisObservations.length}-observation simulation is ready for a different checker; the published model is unchanged.`:"This principal cannot initiate pricing-data governance."}</span></div>}
  </section>;
}
