"use client";
import { useState } from "react";
import { CheckCircle2, FileCheck2, LockKeyhole, ReceiptText, ShieldCheck, TriangleAlert } from "lucide-react";
import { authorize, type Environment, type Principal } from "@fuelcap/authz";
import { approveBillingCorrection, billingBreak, billingRecords, providerEvents, xeroProjection } from "@fuelcap/demo-data/billing-reconciliation";
const money = (minor: number) => `$${(minor / 100).toLocaleString("en-US", { minimumFractionDigits: 2 })}`;
type Selection = "billing" | "provider" | "xero" | "break";
export function BillingReconciliationWorkspace({ organisationId, principal, environment }: { organisationId: string; principal: Principal; environment: Environment }) {
  const [selected, setSelected] = useState<Selection>("billing"); const [action, setAction] = useState<"idle"|"denied"|"pending"|"approved">("idle");
  if (organisationId !== "org-fuelcap-global") return <div className="workspace-wrap"><div className="workspace-empty"><ReceiptText size={25}/><h1>Billing controls are platform-scoped</h1><p>Switch to FuelCap Global. Tenant contexts never inherit provider, tax or accounting records.</p></div></div>;
  const request = () => setAction(authorize({ principal, environment, activeOrganisationId: organisationId, workspace: "billing-reconciliation", verb: "initiate" }).allowed ? "pending" : "denied");
  const approve = () => { approveBillingCorrection("principal-fr-maker", "principal-fr-checker", "MATCH-009"); setAction("approved"); };
  return <div className="workspace-wrap"><section className="workspace-heading"><div><span className="demo-badge"><ShieldCheck size={13}/> Demonstrator data</span><h1>Billing & Reconciliation</h1><p>Provider events and accounting projections reconcile to the authoritative FuelCap ledger.</p></div><div className="workspace-version">Billing projection · v1.0</div></section>
    <section className="pricing-summary"><article><ReceiptText size={17}/><span>Billing records</span><strong>{billingRecords.length}</strong><small>Distinct financial concepts</small></article><article><CheckCircle2 size={17}/><span>Provider events</span><strong>1 / 1 / 1</strong><small>Processed · duplicate · rejected</small></article><article><FileCheck2 size={17}/><span>Xero projection</span><strong>Pending</strong><small>Simulated · retry {xeroProjection.retryCount}</small></article><article><TriangleAlert size={17}/><span>Blocking breaks</span><strong>1</strong><small>{money(billingBreak.differenceMinor)} fee match</small></article></section>
    <section className="canonical-decision-panel"><div><span className="section-kicker">Authority boundary</span><h2>FuelCap ledger remains authoritative</h2><p>Provider success and Xero acknowledgements link to journals; neither system directly mutates balances.</p></div><div className="canonical-price"><span>Fleet invoice</span><strong>{money(xeroProjection.amountMinor)}</strong><small>{xeroProjection.projectionId}</small></div><div className="eligibility-stack"><span className="pricing-eligible">Simulated</span><small>No live provider writes</small></div></section>
    <div className="pricing-layout"><section className="pricing-candidates-panel"><div className="section-heading"><div><span className="section-kicker">Reconciliation evidence</span><h2>Billing and provider records</h2></div></div><div className="pricing-candidate-list"><button type="button" className="pricing-candidate pricing-candidate--selected" onClick={() => setSelected("billing")}><span><strong>Distinct billing categories</strong><small>Funding · subscription · fleet invoice · protection charge</small></span><span><strong>{money(billingRecords.reduce((sum,r)=>sum+r.amountMinor,0))}</strong><small>All journal-linked</small></span><b>CONTROLLED</b><i>Inspect</i></button><button type="button" className="pricing-candidate pricing-candidate--selected" onClick={() => setSelected("provider")}><span><strong>Provider event integrity</strong><small>Signature · idempotency · payload hash</small></span><span><strong>3 events</strong><small>No duplicate journal</small></span><b>VERIFIED</b><i>Inspect</i></button><button type="button" className="pricing-candidate pricing-candidate--corroborating" onClick={() => setSelected("xero")}><span><strong>Xero outbound projection</strong><small>{xeroProjection.projectionId}</small></span><span><strong>Pending ack</strong><small>Retry evidence preserved</small></span><b>WARNING</b><i>Inspect</i></button><button type="button" className="pricing-candidate pricing-candidate--rejected" onClick={() => setSelected("break")}><span><strong>Processor fee break</strong><small>{billingBreak.breakId}</small></span><span><strong>{money(billingBreak.differenceMinor)}</strong><small>Typed account match required</small></span><b>BLOCKING</b><i>Inspect</i></button></div></section>
      <aside className="pricing-controls-panel"><span className="section-kicker">Evidence · immutable</span><h2>{selected === "billing" ? "Billing records" : selected === "provider" ? "Provider events" : selected === "xero" ? "Xero projection" : "Reconciliation break"}</h2><dl>{selected === "billing" ? billingRecords.map(r=><div key={r.id}><dt>{r.kind}</dt><dd>{money(r.amountMinor)} · {r.journalId}</dd></div>) : selected === "provider" ? providerEvents.map(e=><div key={e.eventId}><dt>{e.state}</dt><dd>{e.eventId} · signature {e.signatureValid ? "valid" : "failed"}</dd></div>) : selected === "xero" ? <><div><dt>Projection</dt><dd>{xeroProjection.projectionId}</dd></div><div><dt>Tax mapping</dt><dd>{xeroProjection.taxCode}</dd></div><div><dt>Delivery</dt><dd>PENDING ACK · simulated</dd></div></> : <><div><dt>Break</dt><dd>{billingBreak.breakId}</dd></div><div><dt>Reason</dt><dd>{billingBreak.reason}</dd></div><div><dt>Override</dt><dd>Prohibited</dd></div></>}</dl><div className="spread-action-row"><button type="button" onClick={request}>Request break correction</button></div>{action === "pending" && <div className="spread-action-row"><button type="button" onClick={approve}>Different-FR approval</button></div>}{action !== "idle" && <div className={`customer-review-result customer-review-result--${action === "denied" ? "denied" : "submitted"}`} role="status"><strong>{action === "denied" ? "Permission denied" : action === "approved" ? "Correction approved" : "Approval pending"}</strong><span>{action === "approved" ? "Evidence linked · no live movement." : "Self-approval prohibited."}</span></div>}<div className="pricing-integrity"><LockKeyhole size={15}/><span>Provider events, journals and exports remain immutable.</span></div></aside></div>
    <footer className="demo-footer"><span>FuelCap ledger authority</span><span>Simulated Stripe/Xero</span><span>No live money movement</span></footer></div>;
}
