"use client";

import { useState } from "react";
import { BellRing, CheckCircle2, Clock3, LockKeyhole, RefreshCw, ShieldCheck, Sparkles } from "lucide-react";
import { authorize, type Environment, type Principal } from "@fuelcap/authz";
import { afterNotice, approveRequiredTemplate, communicationPreference, criticalDelivery, draftRequiredTemplate, noticeHoursBeforeAction, outboxEvidence, preNotice, rolloverTemplates } from "@fuelcap/demo-data/communications";

type Selection = "pre" | "after" | "failure" | "template";
type ActionState = "idle" | "denied" | "pending" | "approved";

export function CommunicationsWorkspace({ organisationId, principal, environment }: { organisationId: string; principal: Principal; environment: Environment }) {
  const [selected, setSelected] = useState<Selection>("pre");
  const [action, setAction] = useState<ActionState>("idle");

  if (organisationId !== "org-fuelcap-global") return <div className="workspace-wrap"><div className="workspace-empty"><ShieldCheck size={25}/><h1>Communications are organisation-scoped</h1><p>Switch to FuelCap Global for the simulated delivery queue. Other tenants never inherit recipients, templates or delivery records.</p></div></div>;

  const requestTemplate = () => setAction(authorize({ principal, environment, activeOrganisationId: organisationId, workspace: "communications", verb: "initiate" }).allowed ? "pending" : "denied");
  const approveTemplate = () => { approveRequiredTemplate({ initiatedBy: "principal-operations", approvedBy: "principal-compliance-checker", approverRole: "CF", assurance: "step-up", evidenceIds: [draftRequiredTemplate.version, preNotice.renderedContentHash], sensitiveContentCheck: "PASS" }); setAction("approved"); };
  const hoursBefore = noticeHoursBeforeAction(preNotice.noticeAt, preNotice.actionAt);

  return <div className="workspace-wrap">
    <section className="workspace-heading"><div><span className="demo-badge"><ShieldCheck size={13}/> Demonstrator data</span><h1>Communications</h1><p>Prove required notices, consent basis, delivery integrity and fallback without contacting real customers.</p></div><div className="workspace-version">Scenario rollover-rise-fall-us · v1.0.0</div></section>
    <section className="pricing-summary"><article><Clock3 size={17}/><span>Rollover pre-notice</span><strong>{hoursBefore}h</strong><small>Approved window · 48–72h</small></article><article><CheckCircle2 size={17}/><span>Required delivery</span><strong>Delivered</strong><small>Marketing opted out</small></article><article><RefreshCw size={17}/><span>Primary retries</span><strong>{criticalDelivery.maxPrimaryAttempts}</strong><small>Bounded · fallback delivered</small></article><article><BellRing size={17}/><span>Real recipients</span><strong>0</strong><small>Simulator only</small></article></section>
    <section className="canonical-decision-panel"><div><span className="section-kicker">Required notice evidence</span><h2>{preNotice.communicationId}</h2><p>Required rollover communication remains deliverable despite marketing opt-out and is pinned to its governing event.</p></div><div className="canonical-price"><span>Delivery</span><strong>{preNotice.state}</strong><small>{preNotice.channel} · {rolloverTemplates[0].language}</small></div><div className="eligibility-stack"><span className="pricing-eligible">Content safe</span><small>Simulated · idempotent</small></div></section>
    <div className="pricing-layout"><section className="pricing-candidates-panel"><div className="section-heading"><div><span className="section-kicker">Delivery evidence</span><h2>Messages and operational exceptions</h2></div></div><div className="pricing-candidate-list">
      <button type="button" className="pricing-candidate pricing-candidate--selected" onClick={()=>setSelected("pre")}><span><strong>Auto-Rollover pre-notice</strong><small>{preNotice.templateVersion} · {hoursBefore} hours before action</small></span><span><strong>{preNotice.state}</strong><small>Required · email</small></span><b>ON TIME</b><i>Inspect</i></button>
      <button type="button" className="pricing-candidate pricing-candidate--selected" onClick={()=>setSelected("after")}><span><strong>Linked after-notice</strong><small>{afterNotice.templateVersion} · acknowledgement retained</small></span><span><strong>{afterNotice.state}</strong><small>Required · in-app</small></span><b>LINKED</b><i>Inspect</i></button>
      <button type="button" className="pricing-candidate pricing-candidate--corroborating" onClick={()=>setSelected("failure")}><span><strong>Critical delivery fallback</strong><small>Provider timeout · bounded backoff</small></span><span><strong>{criticalDelivery.attempts.length} attempts</strong><small>Approved in-app fallback</small></span><b>RECOVERED</b><i>Inspect</i></button>
      <button type="button" className="pricing-candidate pricing-candidate--corroborating" onClick={()=>setSelected("template")}><span><strong>Required-template proposal</strong><small>{draftRequiredTemplate.version} · wording diff</small></span><span><strong>US · en-US</strong><small>Email · CF approval required</small></span><b>DRAFT</b><i>Inspect</i></button>
    </div></section>
    <aside className="pricing-controls-panel"><span className="section-kicker">Evidence · immutable</span><h2>{selected === "pre" ? "Pre-notice lineage" : selected === "after" ? "After-notice lineage" : selected === "failure" ? "Retry and fallback" : "Template governance"}</h2><dl>
      {selected === "pre" ? <><div><dt>Governing event</dt><dd>{preNotice.governingEventId}</dd></div><div><dt>Rendered hash</dt><dd>{preNotice.renderedContentHash}</dd></div><div><dt>Preference</dt><dd>Marketing off · required email available</dd></div><div><dt>Outbox</dt><dd>{outboxEvidence.outboxId} · atomic</dd></div><div><dt>Idempotency</dt><dd>Duplicate suppressed</dd></div></> : selected === "after" ? <><div><dt>Governing event</dt><dd>{afterNotice.governingEventId}</dd></div><div><dt>Linked pre-notice</dt><dd>{afterNotice.linkedPreNoticeId}</dd></div><div><dt>Rendered hash</dt><dd>{afterNotice.renderedContentHash}</dd></div><div><dt>Acknowledged</dt><dd>{afterNotice.acknowledgedAt}</dd></div></> : selected === "failure" ? <>{criticalDelivery.attempts.map(({attempt,channel,state,reason})=><div key={attempt}><dt>Attempt {attempt} · {channel}</dt><dd>{state} · {reason}</dd></div>)}<div><dt>Sensitive subject</dt><dd>No</dd></div><div><dt>Fallback preference</dt><dd>Available and approved</dd></div></> : <><div><dt>Purpose</dt><dd>{draftRequiredTemplate.purpose}</dd></div><div><dt>Version</dt><dd>{draftRequiredTemplate.version}</dd></div><div><dt>Content check</dt><dd>{draftRequiredTemplate.sensitiveContentCheck}</dd></div><div><dt>Required approver</dt><dd>Different CF · step-up</dd></div></>}
    </dl><div className="spread-action-row"><button type="button" onClick={requestTemplate}>Request template approval</button></div>{action === "pending" && <div className="spread-action-row"><button type="button" onClick={approveTemplate}>Different-CF approval · step-up</button></div>}{action !== "idle" && <div className={`customer-review-result customer-review-result--${action === "denied" ? "denied" : "submitted"}`} role="status"><strong>{action === "denied" ? "Permission denied" : action === "approved" ? "Template approved" : "Approval pending"}</strong><span>{action === "approved" ? "Registry publication only · no customer delivery." : action === "denied" ? "Role has no template-change authority." : "Self-approval prohibited; different CF required."}</span></div>}<div className="pricing-integrity"><LockKeyhole size={15}/><span>Required notices cannot invent facts, expose sensitive detail or bypass approved wording.</span></div></aside></div>
    <section className="pricing-copilot"><Sparkles size={19}/><div><span className="section-kicker">Communications Copilot · cited</span><h2>Fallback recovered the critical notice</h2><p>Two bounded email failures exhausted the primary route; the approved in-app channel delivered without sensitive lock-screen content.</p><small>Sources · {criticalDelivery.communicationId} · {outboxEvidence.outboxId} · summary only</small></div></section>
    <footer className="demo-footer"><span>Marketing consent separate</span><span>{communicationPreference.version}</span><span>No live delivery</span></footer>
  </div>;
}
