"use client";
import { useEffect, useMemo, useState } from "react";
import { BadgeCheck, CreditCard, Search, Settings2, ShieldCheck, Users, WalletCards, X } from "lucide-react";
import type { Environment, Principal } from "@fuelcap/authz";
import { initialCustomerLifecycleSnapshot, type CustomerLifecycleSnapshot, type LifecycleCustomer, type ServicePlan } from "@fuelcap/demo-data/customer-lifecycle";

type Tab = "customers" | "plans" | "providers";
const pounds = (minor: number) => new Intl.NumberFormat("en-GB", { style: "currency", currency: "GBP" }).format(minor / 100);

export function CustomerWorkspace({ organisationId }: { organisationId: string; principal: Principal; environment: Environment }) {
  const [snapshot, setSnapshot] = useState<CustomerLifecycleSnapshot>(initialCustomerLifecycleSnapshot);
  const [tab, setTab] = useState<Tab>("customers");
  const [query, setQuery] = useState("");
  const [selectedId, setSelectedId] = useState<string | null>(null);
  async function refresh() { const response = await fetch("/api/customer-lifecycle", { cache: "no-store" }); if (response.ok) setSnapshot(await response.json() as CustomerLifecycleSnapshot); }
  useEffect(() => { const timer = window.setInterval(refresh, 1500); return () => window.clearInterval(timer); }, []);
  const customers = useMemo(() => snapshot.customers.filter((customer) => `${customer.name} ${customer.email} ${customer.customerId} ${customer.planId} ${customer.kycState}`.toLowerCase().includes(query.toLowerCase())), [query, snapshot.customers]);
  const selected = snapshot.customers.find((customer) => customer.customerId === selectedId) ?? null;
  const funds = snapshot.customers.reduce((sum, customer) => sum + customer.walletBalanceMinor, 0);
  async function savePlan(plan: ServicePlan, field: "monthlyFeeMinor" | "spreadBps" | "walletLimitMinor", value: number) { const response = await fetch("/api/customer-lifecycle", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ type: "UPSERT_PLAN", plan: { ...plan, [field]: value } }) }); if (response.ok) setSnapshot(await response.json() as CustomerLifecycleSnapshot); }

  return <div className="workspace-wrap lifecycle-workspace">
    <section className="workspace-heading"><div><span className="demo-badge"><ShieldCheck size={13}/> Customer operations</span><h1>Customers, plans and cards</h1><p>Commercial product setup and a live customer record shared with the customer app.</p></div><div className="workspace-version">Lifecycle v1 · sequence {snapshot.sequence}</div></section>
    <section className="customer-summary"><article><Users size={17}/><span>Customers</span><strong>{snapshot.customers.length}</strong><small>{snapshot.customers.filter((c) => c.kycState === "VERIFIED").length} verified</small></article><article><WalletCards size={17}/><span>Customer funds</span><strong>{pounds(funds)}</strong><small>Current wallet balances</small></article><article><BadgeCheck size={17}/><span>KYC verified</span><strong>{Math.round(snapshot.customers.filter((c) => c.kycState === "VERIFIED").length / snapshot.customers.length * 100)}%</strong><small>Provider decisions</small></article><article><CreditCard size={17}/><span>Cards active</span><strong>{snapshot.customers.filter((c) => c.card.status === "ACTIVE").length}</strong><small>Across configured issuers</small></article></section>
    <div className="lifecycle-tabs" role="tablist"><button type="button" className={tab === "customers" ? "is-active" : ""} onClick={() => setTab("customers")}>Customer register</button><button type="button" className={tab === "plans" ? "is-active" : ""} onClick={() => setTab("plans")}>Service plans</button><button type="button" className={tab === "providers" ? "is-active" : ""} onClick={() => setTab("providers")}>Card providers</button></div>
    {tab === "customers" && <section className="lifecycle-panel"><label className="lifecycle-search"><Search size={16}/><span className="sr-only">Search customers</span><input aria-label="Search customers" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search name, email, ID, plan or KYC status"/></label><div className="lifecycle-table-wrap"><table className="lifecycle-table"><thead><tr><th>Customer</th><th>Plan</th><th>KYC</th><th>Funds in</th><th>Funds out</th><th>Wallet</th><th>Customer P/L</th><th>Last activity</th></tr></thead><tbody>{customers.map((customer) => <CustomerRow key={customer.customerId} customer={customer} open={() => setSelectedId(customer.customerId)}/>)}</tbody></table></div></section>}
    {tab === "plans" && <section className="plan-editor-grid">{snapshot.plans.map((plan) => <article key={plan.id} className="plan-editor"><div><span>{plan.id}</span><h2>{plan.name}</h2><small>Version {plan.version}</small></div><label>Monthly fee<input aria-label={`${plan.name} monthly fee`} type="number" step="0.01" defaultValue={(plan.monthlyFeeMinor / 100).toFixed(2)} onBlur={(event) => void savePlan(plan, "monthlyFeeMinor", Math.round(Number(event.target.value) * 100))}/></label><label>Spread (basis points)<input aria-label={`${plan.name} spread`} type="number" defaultValue={plan.spreadBps} onBlur={(event) => void savePlan(plan, "spreadBps", Number(event.target.value))}/></label><label>Wallet limit<input aria-label={`${plan.name} wallet limit`} type="number" defaultValue={plan.walletLimitMinor / 100} onBlur={(event) => void savePlan(plan, "walletLimitMinor", Math.round(Number(event.target.value) * 100))}/></label><dl><div><dt>Fuel limit</dt><dd>{plan.monthlyFuelLimitLitres} L/month</dd></div><div><dt>Coverage</dt><dd>{plan.stationScope}</dd></div></dl><ul>{plan.benefits.map((benefit) => <li key={benefit}>{benefit}</li>)}</ul></article>)}</section>}
    {tab === "providers" && <section className="provider-grid">{snapshot.cardProviders.map((provider) => <article key={provider.id}><CreditCard size={22}/><div><span>{provider.role}</span><h2>{provider.name}</h2><p>Virtual debit · BIN {provider.bin}</p></div><strong>{provider.status}</strong><dl><div><dt>Allocated customers</dt><dd>{provider.customers}</dd></div><div><dt>Routing</dt><dd>{provider.role === "PRIMARY" ? "New verified customers" : "Automatic failover"}</dd></div></dl><button type="button"><Settings2 size={15}/> Configure provider</button></article>)}</section>}
    {selected && <><button type="button" className="evidence-backdrop" aria-label="Close customer details" onClick={() => setSelectedId(null)}/><aside className="lifecycle-drawer" role="dialog" aria-modal="true" aria-label={`${selected.name} customer details`}><div className="lifecycle-drawer__head"><div><span>Customer record</span><h2>{selected.name}</h2><p>{selected.customerId} · {selected.email}</p></div><button type="button" aria-label="Close customer details" onClick={() => setSelectedId(null)}><X size={18}/></button></div><div className={`kyc-state kyc-state--${selected.kycState.toLowerCase()}`}><BadgeCheck size={18}/><span><strong>KYC {selected.kycState.replace("_", " ")}</strong>Driving licence •••• {selected.licenceLast4 ?? "not captured"}</span></div><Detail customer={selected}/></aside></>}
    <footer className="demo-footer"><span>Shared customer lifecycle · {organisationId}</span><span>Polling every 1.5 seconds</span><span>Synthetic provider data · no live card issuance</span></footer>
  </div>;
}

function CustomerRow({ customer, open }: { customer: LifecycleCustomer; open: () => void }) { return <tr><td><button type="button" onClick={open}><strong>{customer.name}</strong><span>{customer.customerId}<br/>{customer.email}</span></button></td><td>{customer.planId}</td><td><span className={`table-state table-state--${customer.kycState.toLowerCase()}`}>{customer.kycState}</span></td><td>{pounds(customer.fundsInMinor)}</td><td>{pounds(customer.fundsOutMinor)}</td><td>{pounds(customer.walletBalanceMinor)}</td><td className={customer.customerProfitLossMinor >= 0 ? "positive-value" : "negative-value"}>{pounds(customer.customerProfitLossMinor)}</td><td>{customer.lastActivity}</td></tr>; }
function Detail({ customer }: { customer: LifecycleCustomer }) { return <div className="lifecycle-detail"><section><h3>App profile</h3><dl><div><dt>Plan</dt><dd>{customer.planId}</dd></div><div><dt>Phone</dt><dd>{customer.phone}</dd></div><div><dt>PIN</dt><dd>{customer.pinSet ? "Set" : "Required"}</dd></div></dl></section><section><h3>Wallet and performance</h3><dl><div><dt>Available balance</dt><dd>{pounds(customer.walletBalanceMinor)}</dd></div><div><dt>Funds in</dt><dd>{pounds(customer.fundsInMinor)}</dd></div><div><dt>Funds out</dt><dd>{pounds(customer.fundsOutMinor)}</dd></div><div><dt>Customer P/L</dt><dd>{pounds(customer.customerProfitLossMinor)}</dd></div><div><dt>Protected fuel</dt><dd>{customer.protectedVolumeLitres} L</dd></div></dl></section><section><h3>FuelCap card</h3><dl><div><dt>Status</dt><dd>{customer.card.status}</dd></div><div><dt>Card</dt><dd>{customer.card.maskedPan}</dd></div><div><dt>Expiry</dt><dd>{customer.card.expiry}</dd></div><div><dt>Provider</dt><dd>{customer.card.providerId}</dd></div></dl></section><section><h3>Latest synchronized activity</h3><p>{customer.lastActivity}</p><small>{new Date(customer.updatedAt).toLocaleString("en-GB")}</small></section></div>; }
