"use client";

import { useState } from "react";
import { Building2, KeyRound, LockKeyhole, Palette, Radio, ShieldCheck } from "lucide-react";
import { authoriseEnterpriseApi, seededApiCredential, seededBrandDraft, seededPublishedBrand, seededWebhookSubscription, simulateWebhookDelivery } from "@fuelcap/enterprise-platform";

export function EnterprisePlatformWorkspace() {
  const [deliveryState, setDeliveryState] = useState<"idle" | "duplicate">("idle");
  const apiDecision = authoriseEnterpriseApi({ credential: seededApiCredential, requestOrganisationId: "org-northstar-logistics", requiredScope: "reports:read", now: "2026-08-28T10:00:00Z" });
  const rehearseDelivery = () => { const seen = new Set<string>(); const input = { deliveryId: "DELIVERY-NORTHSTAR-1", organisationId: "org-northstar-logistics", event: "fleet.updated" as const, payloadDigest: "sha256:dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd" as const, idempotencyKey: "fleet-0842-v2", attemptedAt: "2026-08-28T10:05:00Z" }; simulateWebhookDelivery(seededWebhookSubscription, input, seen); simulateWebhookDelivery(seededWebhookSubscription, input, seen); setDeliveryState("duplicate"); };
  return <section className="enterprise-platform" aria-label="Enterprise platform control centre">
    <div className="section-heading enterprise-platform__heading"><div><span className="section-kicker">P7-004 · governed sandbox foundation</span><h2>White-label and enterprise platform</h2><p>Tenant-owned brand configuration, least-privilege API access and replay-safe webhook subscriptions. All integrations remain sandboxed.</p></div><span className="state-pill state-pill--watch">SANDBOX ONLY</span></div>
    <div className="enterprise-platform__metrics"><article><Building2 size={16}/><span>Enterprise tenant</span><strong>Northstar</strong><small>isolated configuration</small></article><article><Palette size={16}/><span>Brand version</span><strong>v{seededPublishedBrand.version}</strong><small>segregated approval</small></article><article><KeyRound size={16}/><span>API scopes</span><strong>{seededApiCredential.scopes.length}</strong><small>read-only · secret hidden</small></article><article><Radio size={16}/><span>Event types</span><strong>{seededWebhookSubscription.events.length}</strong><small>delivery disabled</small></article></div>
    <div className="enterprise-platform__grid"><article><span className="section-kicker">White-label configuration</span><h3>{seededPublishedBrand.displayName}</h3><dl><div><dt>Configuration</dt><dd>{seededBrandDraft.configurationId}</dd></div><div><dt>State</dt><dd>{seededPublishedBrand.state}</dd></div><div><dt>Primary colour</dt><dd><i className="enterprise-platform__swatch" style={{background:seededPublishedBrand.primaryColour}}/>{seededPublishedBrand.primaryColour}</dd></div><div><dt>Logo</dt><dd>{seededPublishedBrand.logoAssetReference}</dd></div><div><dt>Maker / checker</dt><dd>{seededPublishedBrand.publishedBy} / {seededPublishedBrand.approvedBy}</dd></div><div><dt>Live surface</dt><dd>Disabled</dd></div></dl></article>
    <article><span className="section-kicker">Enterprise API credential</span><h3>{seededApiCredential.label}</h3><dl><div><dt>Credential</dt><dd>{seededApiCredential.credentialId}</dd></div><div><dt>Decision</dt><dd>{apiDecision.status} · {apiDecision.reasonCode}</dd></div><div><dt>Granted scopes</dt><dd>{seededApiCredential.scopes.join(" · ")}</dd></div><div><dt>Secret</dt><dd>Reference only · hidden</dd></div><div><dt>Expires</dt><dd>{seededApiCredential.expiresAt.slice(0,10)}</dd></div><div><dt>Mode</dt><dd>Sandbox only</dd></div></dl></article>
    <article><span className="section-kicker">Webhook subscription</span><h3>{seededWebhookSubscription.subscriptionId}</h3><dl><div><dt>Events</dt><dd>{seededWebhookSubscription.events.join(" · ")}</dd></div><div><dt>Endpoint</dt><dd>{seededWebhookSubscription.endpointReference}</dd></div><div><dt>Signing key</dt><dd>Reference only · hidden</dd></div><div><dt>Outbound network</dt><dd>Disabled</dd></div><div><dt>Replay control</dt><dd>Subscription + idempotency key</dd></div></dl><button type="button" onClick={rehearseDelivery}><ShieldCheck size={14}/> Rehearse signed delivery</button>{deliveryState === "duplicate" && <div className="enterprise-platform__result" role="status"><strong>Duplicate suppressed</strong><span>No network request made; evidence is deterministic.</span></div>}</article></div>
    <div className="enterprise-platform__boundary"><LockKeyhole size={15}/><span>No live branding, production credential, public endpoint, outbound webhook, provider connection or money movement is enabled. Activation requires a separate approved decision and Phase 6 gates.</span></div>
  </section>;
}
