"use client";
import { useState } from "react";
import { AlertTriangle, CheckCircle2, LockKeyhole, Scale, ShieldCheck, Sparkles, Users } from "lucide-react";
import { authorize, type Environment, type Principal } from "@fuelcap/authz";
import { approveMaterialRestriction, explicitHold, fairnessSnapshot, ontarioCase } from "@fuelcap/demo-data/fraud-cases";
const money = (minor: number) => `C$${(minor / 100).toLocaleString("en-CA", { minimumFractionDigits: 2 })}`;
type Selection = "case" | "signals" | "hold" | "fairness";
export function FraudCasesWorkspace({ organisationId, principal, environment }: { organisationId: string; principal: Principal; environment: Environment }) {
  const [selected, setSelected] = useState<Selection>("case"); const [action, setAction] = useState<"idle"|"denied"|"pending"|"approved">("idle");
  if (organisationId !== "org-fuelcap-global") return <div className="workspace-wrap"><div className="workspace-empty"><ShieldCheck size={25}/><h1>Cases are organisation-scoped</h1><p>Switch to FuelCap Global for the governed Scenario 8 review queue. Other tenants never inherit these cases.</p></div></div>;
  const request = () => setAction(authorize({ principal, environment, activeOrganisationId: organisationId, workspace: "fraud-cases", verb: "initiate" }).allowed ? "pending" : "denied");
  const approve = () => { approveMaterialRestriction("principal-cf-maker", "principal-cf-checker", ontarioCase.signals.map(s=>s.signalId), true); setAction("approved"); };
  return <div className="workspace-wrap"><section className="workspace-heading"><div><span className="demo-badge"><ShieldCheck size={13}/> Demonstrator data</span><h1>Fraud & Cases</h1><p>Typed signals prioritise human review while customer value remains intact and restrictions stay proportional.</p></div><div className="workspace-version">Scenario eligibility-fraud-canada · v1.0.0</div></section>
    <section className="pricing-summary"><article><Users size={17}/><span>Human reviews</span><strong>{ontarioCase.reviewCount}</strong><small>Ontario cluster</small></article><article><AlertTriangle size={17}/><span>Rollover scope</span><strong>4,860 L</strong><small>Capability held · not balance</small></article><article><CheckCircle2 size={17}/><span>Customer value</span><strong>{money(ontarioCase.retainedCustomerValueMinor)}</strong><small>Retained and available</small></article><article><Scale size={17}/><span>Proxy testing</span><strong>Pass</strong><small>Protected attributes prohibited</small></article></section>
    <section className="canonical-decision-panel"><div><span className="section-kicker">Human-review case</span><h2>{ontarioCase.caseId}</h2><p>Eligibility is distinct from availability. No automated adverse outcome has been applied.</p></div><div className="canonical-price"><span>Severity</span><strong>Warning</strong><small>{ontarioCase.market} · {ontarioCase.reasonClass}</small></div><div className="eligibility-stack"><span className="pricing-eligible">Value preserved</span><small>Review and appeal available</small></div></section>
    <div className="pricing-layout"><section className="pricing-candidates-panel"><div className="section-heading"><div><span className="section-kicker">Case evidence</span><h2>Evidence-led investigation</h2></div></div><div className="pricing-candidate-list"><button type="button" className="pricing-candidate pricing-candidate--selected" onClick={()=>setSelected("case")}><span><strong>Case timeline</strong><small>Opened · assigned · human review</small></span><span><strong>18 reviews</strong><small>{ontarioCase.reviewRoute}</small></span><b>OPEN</b><i>Inspect</i></button><button type="button" className="pricing-candidate pricing-candidate--corroborating" onClick={()=>setSelected("signals")}><span><strong>Typed statistical signals</strong><small>Versioned reasons · synthetic provenance</small></span><span><strong>{ontarioCase.signals.length} signals</strong><small>No generative decision</small></span><b>REVIEW</b><i>Inspect</i></button><button type="button" className="pricing-candidate pricing-candidate--corroborating" onClick={()=>setSelected("hold")}><span><strong>Explicit capability hold</strong><small>{explicitHold.holdId} · expires automatically</small></span><span><strong>Auto-rollover</strong><small>Balance erased: no</small></span><b>PROPOSED</b><i>Inspect</i></button><button type="button" className="pricing-candidate pricing-candidate--selected" onClick={()=>setSelected("fairness")}><span><strong>Fairness assurance</strong><small>{fairnessSnapshot.version}</small></span><span><strong>3.20% FPR</strong><small>Proxy test passed</small></span><b>CONTROLLED</b><i>Inspect</i></button></div></section>
      <aside className="pricing-controls-panel"><span className="section-kicker">Evidence · immutable</span><h2>{selected === "case" ? "Case and customer impact" : selected === "signals" ? "Signal lineage" : selected === "hold" ? "Scoped hold" : "Fairness controls"}</h2><dl>{selected === "signals" ? ontarioCase.signals.map(s=><div key={s.signalId}><dt>{s.type} · {(s.scoreBps/100).toFixed(0)}%</dt><dd>{s.reasonCode} · {s.modelVersion}</dd></div>) : selected === "hold" ? <><div><dt>Capability</dt><dd>{explicitHold.capability}</dd></div><div><dt>Balance erased</dt><dd>No</dd></div><div><dt>Expiry</dt><dd>{explicitHold.expiresAt}</dd></div></> : selected === "fairness" ? <><div><dt>Protected attributes</dt><dd>Prohibited</dd></div><div><dt>Proxy test</dt><dd>PASS</dd></div><div><dt>Median review</dt><dd>{fairnessSnapshot.medianReviewMinutes} min</dd></div></> : <><div><dt>Customer</dt><dd>{ontarioCase.customerId}</dd></div><div><dt>Retained value</dt><dd>{money(ontarioCase.retainedCustomerValueMinor)}</dd></div><div><dt>Review route</dt><dd>{ontarioCase.reviewRoute}</dd></div></>}</dl><div className="spread-action-row"><button type="button" onClick={request}>Request scoped restriction</button></div>{action === "pending" && <div className="spread-action-row"><button type="button" onClick={approve}>Different-CF approval</button></div>}{action !== "idle" && <div className={`customer-review-result customer-review-result--${action === "denied" ? "denied" : "submitted"}`} role="status"><strong>{action === "denied" ? "Permission denied" : action === "approved" ? "Scoped hold approved" : "Approval pending"}</strong><span>{action === "approved" ? "Proportional, expiring hold · review route retained." : "Self-approval prohibited."}</span></div>}<div className="pricing-integrity"><LockKeyhole size={15}/><span>Emergency action cannot confiscate value or fabricate eligibility.</span></div></aside></div>
    <section className="pricing-copilot"><Sparkles size={19}/><div><span className="section-kicker">Case Copilot · cited</span><h2>Prioritise review; do not automate an adverse outcome</h2><p>Velocity and location signals justify investigation, not a balance restriction.</p><small>Sources · SIG-VELOCITY-018 · SIG-LOCATION-018 · summary only</small></div></section><footer className="demo-footer"><span>Human decision required</span><span>Customer value preserved</span><span>No live fraud provider</span></footer></div>;
}
