"use client";

import { useState } from "react";
import { Activity, GitBranch, LockKeyhole, ServerCog, ShieldCheck, Sparkles, TriangleAlert } from "lucide-react";
import { authorize, type Environment, type Principal } from "@fuelcap/authz";
import { adapters, approveIntegrationConfiguration, auditRecords, configurationProposal, correlationTrace, incident, platformRelease, replayEvent, serviceChecks, validateWebhook, webhookReceipt } from "@fuelcap/demo-data/platform-integrations-audit";

type Selection = "health" | "adapters" | "event" | "audit";
type ActionState = "idle" | "denied" | "pending" | "approved";

export function PlatformIntegrationsAuditWorkspace({ organisationId, principal, environment }: { organisationId: string; principal: Principal; environment: Environment }) {
  const [selected, setSelected] = useState<Selection>("health");
  const [action, setAction] = useState<ActionState>("idle");
  const [replay, setReplay] = useState<"idle" | "safe">("idle");

  if (organisationId !== "org-fuelcap-global") return <div className="workspace-wrap"><div className="workspace-empty"><ShieldCheck size={25}/><h1>Platform evidence is tenant-safe</h1><p>Switch to FuelCap Global for platform configuration and integration evidence. Other tenants never inherit payloads, incidents, secrets or audit records.</p></div></div>;

  const requestConfiguration = () => setAction(authorize({ principal, environment, activeOrganisationId: organisationId, workspace: "platform-integrations-audit", verb: "initiate" }).allowed ? "pending" : "denied");
  const approveConfiguration = () => { approveIntegrationConfiguration({ initiatedBy: "principal-data-maker", approvedBy: "principal-platform-checker", approverRole: "PA", assurance: "step-up", compatibilityStatus: "PASS", rollbackReference: configurationProposal.rollbackReference, secretValueDisplayed: false }); setAction("approved"); };
  const simulateReplay = () => { const inbox = new Set<string>(); const journals = new Set<string>(); replayEvent("EVENT-0091", inbox, journals); replayEvent("EVENT-0091", inbox, journals); setReplay("safe"); };
  const webhookDecision = validateWebhook(webhookReceipt);

  return <div className="workspace-wrap">
    <section className="workspace-heading"><div><span className="demo-badge"><ShieldCheck size={13}/> Demonstrator data</span><h1>Platform, Integrations & Audit</h1><p>Inspect service health, honest adapter modes, contract delivery, incidents and governed configuration without exposing secrets.</p></div><div className="workspace-version">Release {platformRelease.deploymentCommit} · {platformRelease.environment}</div></section>
    <section className="pricing-summary"><article><Activity size={17}/><span>Service checks</span><strong>2 / 3</strong><small>Healthy · one simulated degradation</small></article><article><ServerCog size={17}/><span>Adapters</span><strong>{adapters.length}</strong><small>Test · simulated · mock</small></article><article><TriangleAlert size={17}/><span>Dead letters</span><strong>1</strong><small>Owned · invalid signature</small></article><article><GitBranch size={17}/><span>Correlation trace</span><strong>{correlationTrace.length} stages</strong><small>Quote through projections</small></article></section>
    <section className="canonical-decision-panel"><div><span className="section-kicker">Deployment and integrity</span><h2>{platformRelease.service}</h2><p>Production serves a demonstrator release; service evidence does not claim production-grade availability or unproven live integrations.</p></div><div className="canonical-price"><span>Release commit</span><strong>{platformRelease.deploymentCommit}</strong><small>{platformRelease.health} · checked {platformRelease.checkedAt.slice(11,16)} UTC</small></div><div className="eligibility-stack"><span className="pricing-eligible">Secrets redacted</span><small>Audit evidence immutable</small></div></section>
    <div className="pricing-layout"><section className="pricing-candidates-panel"><div className="section-heading"><div><span className="section-kicker">Operational evidence</span><h2>Services, adapters and delivery integrity</h2></div></div><div className="pricing-candidate-list">
      <button type="button" className="pricing-candidate pricing-candidate--selected" onClick={()=>setSelected("health")}><span><strong>Service and dependency health</strong><small>Release · freshness · owner · demonstrator objective</small></span><span><strong>2 healthy</strong><small>1 degraded mock worker</small></span><b>CONTROLLED</b><i>Inspect</i></button>
      <button type="button" className="pricing-candidate pricing-candidate--selected" onClick={()=>setSelected("adapters")}><span><strong>Provider-neutral adapters</strong><small>Explicit mode · contract · credential metadata</small></span><span><strong>{adapters.length} adapters</strong><small>No live mode claimed</small></span><b>HONEST</b><i>Inspect</i></button>
      <button type="button" className="pricing-candidate pricing-candidate--rejected" onClick={()=>setSelected("event")}><span><strong>Blocked webhook receipt</strong><small>{webhookReceipt.receiptId} · immutable receipt hash</small></span><span><strong>Dead letter</strong><small>{webhookReceipt.reasonCode}</small></span><b>BLOCKED</b><i>Inspect</i></button>
      <button type="button" className="pricing-candidate pricing-candidate--corroborating" onClick={()=>setSelected("audit")}><span><strong>Configuration and audit</strong><small>{configurationProposal.proposalId} · rollback pinned</small></span><span><strong>{auditRecords.length} records</strong><small>Sensitive fields redacted</small></span><b>GOVERNED</b><i>Inspect</i></button>
    </div></section>
    <aside className="pricing-controls-panel"><span className="section-kicker">Evidence · immutable</span><h2>{selected === "health" ? "Service checks" : selected === "adapters" ? "Adapter registry" : selected === "event" ? "Receipt and replay" : "Configuration audit"}</h2><dl>
      {selected === "health" ? serviceChecks.map(({serviceId,health,freshnessSeconds,owner})=><div key={serviceId}><dt>{serviceId} · {health}</dt><dd>{owner} · {freshnessSeconds}s freshness</dd></div>) : selected === "adapters" ? adapters.map(({adapterId,mode,contractVersion,secretDisplayed})=><div key={adapterId}><dt>{adapterId} · {mode}</dt><dd>{contractVersion} · secret displayed: {secretDisplayed ? "yes" : "no"}</dd></div>) : selected === "event" ? <><div><dt>Decision</dt><dd>{webhookDecision.reasonCode}</dd></div><div><dt>Receipt hash</dt><dd>{webhookReceipt.rawPayloadHash}</dd></div><div><dt>Tenant / schema</dt><dd>Valid / compatible</dd></div><div><dt>Correlation</dt><dd>{webhookReceipt.correlationId}</dd></div><div><dt>Owner</dt><dd>{webhookReceipt.deadLetterOwner}</dd></div></> : <><div><dt>Before / after</dt><dd>{configurationProposal.beforeConfigurationHash} → {configurationProposal.afterConfigurationHash}</dd></div><div><dt>Credential</dt><dd>Secret reference only · value hidden</dd></div><div><dt>Rollback</dt><dd>{configurationProposal.rollbackReference}</dd></div><div><dt>Audit</dt><dd>{auditRecords.map(({auditId})=>auditId).join(" · ")}</dd></div></>}
    </dl>{selected === "event" && <div className="spread-action-row"><button type="button" onClick={simulateReplay}>Simulate safe replay</button></div>}{replay === "safe" && selected === "event" && <div className="customer-review-result customer-review-result--submitted" role="status"><strong>Duplicate suppressed</strong><span>Inbox matched · no duplicate financial posting.</span></div>}<div className="spread-action-row"><button type="button" onClick={requestConfiguration}>Request configuration change</button></div>{action === "pending" && <div className="spread-action-row"><button type="button" onClick={approveConfiguration}>Different-DI/PA approval · step-up</button></div>}{action !== "idle" && <div className={`customer-review-result customer-review-result--${action === "denied" ? "denied" : "submitted"}`} role="status"><strong>{action === "denied" ? "Permission denied" : action === "approved" ? "Configuration approved" : "Approval pending"}</strong><span>{action === "approved" ? "Rollback pinned · post-change health required." : action === "denied" ? "Role has no integration-change authority." : "Self-approval prohibited; different DI or PA required."}</span></div>}<div className="pricing-integrity"><LockKeyhole size={15}/><span>Config cannot expose secrets, relax tenancy or bypass ledger integrity.</span></div></aside></div>
    <section className="pricing-copilot"><Sparkles size={19}/><div><span className="section-kicker">Incident Copilot · cited</span><h2>{incident.title}</h2><p>{incident.containment}. Follow {incident.runbookId}; human verification is required before closure.</p><small>Sources · {incident.incidentId} · {webhookReceipt.receiptId} · advisory only</small></div></section>
    <footer className="demo-footer"><span>No unproven live partner</span><span>Correlation {webhookReceipt.correlationId}</span><span>Simulated incident</span></footer>
  </div>;
}
