"use client";

import { useEffect, useRef, useState } from "react";
import { Activity, AlertTriangle, FileCheck2, LockKeyhole, ShieldCheck, Sparkles, X } from "lucide-react";
import { authorize, type Environment, type Principal } from "@fuelcap/authz";
import { acceptedExposureSnapshot as exposure, createSimulatedHedgeExecution, stressProjections, texasHedgeRecommendation as recommendation, type StressProjection } from "@fuelcap/demo-data/risk-hedging";

type Evidence = { kind: "exposure" | "recommendation" } | { kind: "stress"; stress: StressProjection };
const money = (minor: number) => `$${(minor / 100).toLocaleString("en-US", { maximumFractionDigits: 0 })}`;
const gallons = (value: number) => `${(value / 10000).toLocaleString("en-US")} gal`;

export function RiskHedgingWorkspace({ organisationId, principal, environment }: { organisationId: string; principal: Principal; environment: Environment }) {
  const [evidence, setEvidence] = useState<Evidence | null>(null);
  const [action, setAction] = useState<"idle" | "denied" | "pending" | "simulated">("idle");
  const drawerRef = useRef<HTMLElement | null>(null);
  useEffect(() => { if (!evidence) return; const overflow = document.body.style.overflow; document.body.style.overflow = "hidden"; requestAnimationFrame(() => drawerRef.current?.querySelector<HTMLElement>("button")?.focus()); const close = (event: KeyboardEvent) => { if (event.key === "Escape") setEvidence(null); }; document.addEventListener("keydown", close); return () => { document.removeEventListener("keydown", close); document.body.style.overflow = overflow; }; }, [evidence]);
  if (organisationId !== "org-fuelcap-global") return <div className="workspace-wrap"><div className="workspace-empty"><ShieldCheck size={25} /><h1>Risk exposure is platform-scoped</h1><p>Switch to FuelCap Global to inspect accepted-position exposure. Tenant contexts never inherit platform risk records.</p><span>Accepted positions only · context boundary enforced</span></div></div>;
  function requestApproval() { const result = authorize({ principal, environment, activeOrganisationId: organisationId, workspace: "risk-hedging", verb: "initiate" }); setAction(result.allowed ? "pending" : "denied"); }
  function approveSimulation() { createSimulatedHedgeExecution(recommendation, "principal-rt-maker", "principal-rt-checker"); setAction("simulated"); }
  return <div className="workspace-wrap risk-workspace">
    <section className="workspace-heading"><div><span className="demo-badge"><ShieldCheck size={13} /> Demonstrator data · simulation only</span><h1>Risk & Hedging</h1><p>Accepted positions become explainable exposure, deterministic stresses and governed simulated responses.</p></div><div className="workspace-version">Scenario exposure-ai-recommendation · v1.0.0</div></section>
    <section className="pricing-summary"><article><Activity size={17} /><span>Accepted exposure</span><strong>{gallons(exposure.acceptedQuantity4dp)}</strong><small>Accepted positions only</small></article><article><AlertTriangle size={17} /><span>Texas concentration</span><strong>37%</strong><small>14 fleets · 312 vehicles</small></article><article><ShieldCheck size={17} /><span>Value at boundary</span><strong>{money(exposure.valueAtBoundaryMinor)}</strong><small>Version-pinned projection</small></article><article><LockKeyhole size={17} /><span>Pool coverage</span><strong>1.70×</strong><small>0.20× above floor</small></article></section>
    <section className="canonical-decision-panel"><div><span className="section-kicker">Accepted-position snapshot</span><h2>{exposure.snapshotId}</h2><p>Uncommitted quote demand is excluded. Price, spread and rules evidence is pinned.</p></div><button className="evidence-link" type="button" onClick={() => setEvidence({ kind: "exposure" })}>Inspect lineage</button><div className="eligibility-stack"><span className="pricing-eligible">Reconciled</span><small>21 Aug 2026 · 16:45 UTC</small></div></section>
    <div className="pricing-layout"><section className="pricing-candidates-panel"><div className="section-heading"><div><span className="section-kicker">Deterministic stress laboratory</span><h2>Seven reproducible outcomes</h2></div><span className="tenant-chip">black-76-demo@1.0</span></div><div className="pricing-candidate-list">{stressProjections.map((stress) => <button type="button" key={stress.stressId} className={`pricing-candidate ${stress.outcome === "CONTROLLED" ? "pricing-candidate--selected" : "pricing-candidate--rejected"}`} onClick={() => setEvidence({ kind: "stress", stress })}><span><strong>{stress.label}</strong><small>Volatility {(stress.volatilityBps / 100).toFixed(0)}% · basis {(stress.basisShockBps / 100).toFixed(2)}%</small></span><span><strong>{money(stress.expectedClaimsMinor)}</strong><small>Pool cover {(stress.poolCoverageAfter100dp / 100).toFixed(2)}×</small></span><b>{stress.outcome}</b><i>Inspect</i></button>)}</div></section>
      <aside className="pricing-controls-panel"><span className="section-kicker">Cited recommendation</span><h2>Simulate 25,000 gal cover</h2><dl><div><dt>Instrument</dt><dd>Simulated call spread</dd></div><div><dt>Premium</dt><dd>{money(recommendation.estimatedPremiumMinor)}</dd></div><div><dt>Expected payoff</dt><dd>{money(recommendation.expectedPayoffMinor)}</dd></div><div><dt>Pool cover after</dt><dd>2.30×</dd></div><div><dt>Confidence</dt><dd>91%</dd></div></dl><button className="evidence-link" type="button" onClick={() => setEvidence({ kind: "recommendation" })}>Recommendation evidence</button><div className="spread-action-row"><button type="button" onClick={requestApproval}>Request simulated approval</button></div>{action === "pending" && <div className="spread-action-row"><button type="button" onClick={approveSimulation}>Different-RT approval</button></div>}{action !== "idle" && <div className={`customer-review-result customer-review-result--${action === "denied" ? "denied" : "submitted"}`} role="status"><strong>{action === "denied" ? "Permission denied" : action === "simulated" ? "Simulated execution created" : "Approval pending"}</strong><span>{action === "denied" ? `${principal.roles.join("/")} cannot initiate this action.` : action === "simulated" ? "Different RT recorded · no live instrument or money movement." : "Self-approval prohibited · different RT and step-up required."}</span></div>}<div className="pricing-integrity"><LockKeyhole size={15} /><span>No broker connection. Only labelled simulation is available.</span></div></aside></div>
    <section className="pricing-copilot"><Sparkles size={19} /><div><span className="section-kicker">Exposure Copilot · cited</span><h2>Texas concentration warrants a proportionate paper response</h2><p>Boundary and correlation stresses show the clearest reserve sensitivity.</p><small>Sources · {exposure.snapshotId} · STRESS-BREACH · STRESS-CORR</small></div></section>
    {evidence && <><button className="evidence-backdrop" type="button" aria-label="Close risk evidence" onClick={() => setEvidence(null)} /><aside ref={drawerRef} className="evidence-drawer" role="dialog" aria-modal="true" aria-label="Risk evidence"><div className="evidence-drawer__heading"><div><span className="section-kicker">Evidence · immutable</span><h2>{evidence.kind === "stress" ? evidence.stress.label : evidence.kind === "exposure" ? "Accepted-position lineage" : "Hedge recommendation"}</h2></div><button className="icon-button" type="button" onClick={() => setEvidence(null)} aria-label="Close risk evidence"><X size={18} /></button></div>{evidence.kind === "stress" ? <dl className="evidence-facts"><div><dt>Stress</dt><dd>{evidence.stress.stressId}</dd></div><div><dt>Claims</dt><dd>{money(evidence.stress.expectedClaimsMinor)}</dd></div><div><dt>Simulated payoff</dt><dd>{money(evidence.stress.simulatedPayoffMinor)}</dd></div><div><dt>Reserve use</dt><dd>{money(evidence.stress.reserveUseMinor)}</dd></div><div><dt>Residual exposure</dt><dd>{money(evidence.stress.residualExposureMinor)}</dd></div><div><dt>Outcome</dt><dd>{evidence.stress.outcome}</dd></div></dl> : <dl className="evidence-facts"><div><dt>Record</dt><dd>{evidence.kind === "exposure" ? exposure.snapshotId : recommendation.recommendationId}</dd></div><div><dt>Version</dt><dd>{evidence.kind === "exposure" ? exposure.version : recommendation.version}</dd></div><div><dt>Quantity</dt><dd>{evidence.kind === "exposure" ? gallons(exposure.acceptedQuantity4dp) : gallons(recommendation.quantity4dp)}</dd></div><div><dt>Model / spread</dt><dd>{evidence.kind === "exposure" ? exposure.spreadDecisionVersion : recommendation.modelVersion}</dd></div><div><dt>Provenance</dt><dd>illustrative-fixed</dd></div><div><dt>Boundary</dt><dd>SIMULATION ONLY</dd></div></dl>}<div className="customer-evidence-boundary"><FileCheck2 size={15} /><span>Snapshot → model → stress → recommendation → approval → simulated execution → audit</span></div></aside></>}
    <footer className="demo-footer"><span>Accepted positions only</span><span>Black-76 demonstrator model</span><span>No live hedge or money movement</span></footer>
  </div>;
}
