"use client";

import { useState } from "react";
import { FileCheck2, GitCompareArrows, LockKeyhole, Play, ShieldCheck, Sparkles, TriangleAlert } from "lucide-react";
import { authorize, type Environment, type Principal } from "@fuelcap/authz";
import { approveRulePublication, blockingValidationEvidence, draftEligibilityRule, pinnedRuleDecision, publishedEligibilityRule, ruleImpact, scenarioRegression, validationEvidence } from "@fuelcap/demo-data/rules-automation";

type Selection = "rules" | "validation" | "regression" | "decision";
type ActionState = "idle" | "denied" | "pending" | "scheduled";

export function RulesAutomationWorkspace({ organisationId, principal, environment }: { organisationId: string; principal: Principal; environment: Environment }) {
  const [selected, setSelected] = useState<Selection>("rules");
  const [action, setAction] = useState<ActionState>("idle");

  if (organisationId !== "org-fuelcap-global") return <div className="workspace-wrap"><div className="workspace-empty"><ShieldCheck size={25}/><h1>Rules are platform-scoped</h1><p>Switch to FuelCap Global to inspect governed rule versions. Customer and fleet tenants never inherit publication authority.</p></div></div>;

  const requestPublication = () => setAction(authorize({ principal, environment, activeOrganisationId: organisationId, workspace: "rules-automation", verb: "initiate" }).allowed ? "pending" : "denied");
  const approvePublication = () => {
    approveRulePublication({ initiatedBy: "principal-cf-maker", approvedBy: "principal-cf-checker", initiatorRole: "CF", approverRole: "CF", requiredRole: "CF", assurance: "step-up", validationStatus: validationEvidence.status, regressionPassed: ruleImpact.status === "PASS" });
    setAction("scheduled");
  };

  return <div className="workspace-wrap">
    <section className="workspace-heading"><div><span className="demo-badge"><ShieldCheck size={13}/> Demonstrator data</span><h1>Rules & Automation</h1><p>Compose typed policy, compare deterministic impact and publish only through validated maker-checker control.</p></div><div className="workspace-version">Rules scenario suite · v1.0.0</div></section>
    <section className="pricing-summary"><article><FileCheck2 size={17}/><span>Published version</span><strong>1.3.0</strong><small>Immutable · effective now</small></article><article><Play size={17}/><span>Scenario regression</span><strong>{ruleImpact.passedScenarioCount} / {ruleImpact.scenarioCount}</strong><small>Canonical suite passed</small></article><article><GitCompareArrows size={17}/><span>Changed outcomes</span><strong>0</strong><small>Customers · transactions · exposure</small></article><article><TriangleAlert size={17}/><span>Blocking controls</span><strong>{blockingValidationEvidence.reasonCodes.length}</strong><small>Unsafe example cannot publish</small></article></section>
    <section className="canonical-decision-panel"><div><span className="section-kicker">Published rules decision</span><h2>{publishedEligibilityRule.ruleSetId}</h2><p>Published versions are immutable. Editing creates a separate proposal and never changes pinned historical outcomes.</p></div><div className="canonical-price"><span>Active version</span><strong>{publishedEligibilityRule.version.replace("eligibility@", "")}</strong><small>{publishedEligibilityRule.domain} · owner {publishedEligibilityRule.ownerRole}</small></div><div className="eligibility-stack"><span className="pricing-eligible">Regression green</span><small>Effective {publishedEligibilityRule.effectiveFrom.slice(0, 10)}</small></div></section>
    <div className="pricing-layout"><section className="pricing-candidates-panel"><div className="section-heading"><div><span className="section-kicker">Governed lifecycle</span><h2>Rule and impact evidence</h2></div></div><div className="pricing-candidate-list">
      <button type="button" className="pricing-candidate pricing-candidate--selected" onClick={()=>setSelected("rules")}><span><strong>Eligibility rule proposal</strong><small>{draftEligibilityRule.version} · supersedes {draftEligibilityRule.supersedesVersion}</small></span><span><strong>{draftEligibilityRule.conditions.length} conditions</strong><small>Restricted typed expressions</small></span><b>DRAFT</b><i>Inspect</i></button>
      <button type="button" className="pricing-candidate pricing-candidate--selected" onClick={()=>setSelected("validation")}><span><strong>Validation evidence</strong><small>{validationEvidence.validationId} · types · ranges · conflicts</small></span><span><strong>6 / 6</strong><small>All publication checks pass</small></span><b>VALID</b><i>Inspect</i></button>
      <button type="button" className="pricing-candidate pricing-candidate--corroborating" onClick={()=>setSelected("regression")}><span><strong>Canonical impact simulation</strong><small>{ruleImpact.simulationId} · current versus draft</small></span><span><strong>12 scenarios</strong><small>Zero outcome changes</small></span><b>PASS</b><i>Inspect</i></button>
      <button type="button" className="pricing-candidate pricing-candidate--selected" onClick={()=>setSelected("decision")}><span><strong>Historical decision replay</strong><small>{pinnedRuleDecision.decisionId} · original clock and facts</small></span><span><strong>Human review</strong><small>Immutable pinned outcome</small></span><b>PINNED</b><i>Inspect</i></button>
    </div></section>
    <aside className="pricing-controls-panel"><span className="section-kicker">Evidence · immutable</span><h2>{selected === "rules" ? "Typed proposal" : selected === "validation" ? "Publication validation" : selected === "regression" ? "Scenario impact" : "Pinned replay"}</h2><dl>
      {selected === "rules" ? <><div><dt>Lifecycle</dt><dd>Draft → validate → simulate → approve → schedule</dd></div>{draftEligibilityRule.conditions.map((condition)=><div key={`${condition.fact}-${condition.operator}`}><dt>{condition.fact}</dt><dd>{condition.operator} · {String(condition.value)}</dd></div>)}<div><dt>Arbitrary code</dt><dd>Prohibited</dd></div></> : selected === "validation" ? <>{Object.entries(validationEvidence.checks).map(([check,status])=><div key={check}><dt>{check.replaceAll(/([A-Z])/g," $1")}</dt><dd>{status}</dd></div>)}<div><dt>Unsafe proposal</dt><dd>BLOCKED · {blockingValidationEvidence.reasonCodes.join(" · ")}</dd></div></> : selected === "regression" ? <><div><dt>Canonical scenarios</dt><dd>{scenarioRegression.length} / {scenarioRegression.length} passed</dd></div><div><dt>Customer changes</dt><dd>{ruleImpact.changedCustomers}</dd></div><div><dt>Financial impact</dt><dd>$0.00 margin · $0.00 reserve</dd></div><div><dt>Review workload</dt><dd>No change</dd></div></> : <><div><dt>Rule version</dt><dd>{pinnedRuleDecision.ruleVersion}</dd></div><div><dt>Outcome</dt><dd>{pinnedRuleDecision.outcome}</dd></div><div><dt>Failed condition</dt><dd>{pinnedRuleDecision.failedConditions.join(" · ")}</dd></div><div><dt>Original clock</dt><dd>{pinnedRuleDecision.evaluatedAt}</dd></div></>}
    </dl><div className="spread-action-row"><button type="button" onClick={requestPublication}>Simulate & request publication</button></div>{action === "pending" && <div className="spread-action-row"><button type="button" onClick={approvePublication}>Different-CF approval · step-up</button></div>}{action !== "idle" && <div className={`customer-review-result customer-review-result--${action === "denied" ? "denied" : "submitted"}`} role="status"><strong>{action === "denied" ? "Permission denied" : action === "scheduled" ? "Publication scheduled" : "Approval pending"}</strong><span>{action === "scheduled" ? `${draftEligibilityRule.version} · effective ${draftEligibilityRule.effectiveFrom}` : action === "denied" ? "Role has no publication authority." : "Self-approval prohibited; different CF required."}</span></div>}<div className="pricing-integrity"><LockKeyhole size={15}/><span>Emergency withdrawal cannot rewrite history, bypass RLS or fabricate validity.</span></div></aside></div>
    <section className="pricing-copilot"><Sparkles size={19}/><div><span className="section-kicker">Rules Copilot · cited</span><h2>No intervention recommended</h2><p>The draft is validation-green and changes no canonical outcome. Human approval remains required before scheduling.</p><small>Sources · {validationEvidence.validationId} · {ruleImpact.simulationId} · draft/explanation only</small></div></section>
    <footer className="demo-footer"><span>Restricted expressions</span><span>Different same-domain approver</span><span>No autonomous publication</span></footer>
  </div>;
}
