"use client";

import { useEffect, useRef, useState } from "react";
import { ArrowRight, Calculator, CheckCircle2, FileCheck2, Globe2, LockKeyhole, ShieldCheck, Sparkles, X } from "lucide-react";
import { authorize, type Environment, type Principal } from "@fuelcap/authz";
import { activeSpreadDecision, directCanonicalFxRate, fxReferenceObservations, pinnedMultiMarketQuote, proposeSpreadComponents, triangulatedCanonicalFxRate, validateSpreadDraft, type FxReferenceObservation, type SpreadComponentKey } from "@fuelcap/demo-data/spread-fx";

type Evidence = { kind: "spread" } | { kind: "fx"; observation: FxReferenceObservation } | { kind: "quote" };
type ActionState = "idle" | "denied" | "invalid" | "submitted";
const initialComponents = activeSpreadDecision.components;
const componentLabels: Record<SpreadComponentKey, string> = { protectionCostBps: "Modelled protection cost", fuelCapMarginBps: "FuelCap margin", reserveBufferBps: "Reserve / pool buffer" };
const percent = (bps: number) => `${(bps / 100).toFixed(2)}%`;
const rate = (rate6dp: number) => (rate6dp / 1_000_000).toFixed(6);

export function SpreadFxWorkspace({ organisationId, principal, environment }: { organisationId: string; principal: Principal; environment: Environment }) {
  const [components, setComponents] = useState({ ...initialComponents });
  const [reason, setReason] = useState("Rebalance component allocation while preserving the governed gross spread.");
  const [actionState, setActionState] = useState<ActionState>("idle");
  const [evidence, setEvidence] = useState<Evidence | null>(null);
  const drawerRef = useRef<HTMLElement | null>(null);
  const draft = proposeSpreadComponents(activeSpreadDecision, components, reason, principal.principalId);
  const validation = validateSpreadDraft(draft);
  const directRate = directCanonicalFxRate("USD/CAD")!;
  const triangulatedRate = triangulatedCanonicalFxRate("GBP/USD", "USD/CAD", "GBP/CAD", "USD")!;

  useEffect(() => {
    if (!evidence) return;
    const previousOverflow = document.body.style.overflow;
    document.body.style.overflow = "hidden";
    requestAnimationFrame(() => drawerRef.current?.querySelector<HTMLElement>("button")?.focus());
    const close = (event: KeyboardEvent) => { if (event.key === "Escape") setEvidence(null); };
    document.addEventListener("keydown", close);
    return () => { document.removeEventListener("keydown", close); document.body.style.overflow = previousOverflow; };
  }, [evidence]);

  if (organisationId !== "org-fuelcap-global") return <div className="workspace-wrap"><div className="workspace-empty"><Globe2 size={25} /><h1>Spread and FX decisions are platform-scoped</h1><p>Switch to FuelCap Global to inspect governed component and currency decisions. Tenant contexts never inherit platform pricing policy.</p><span>Context boundary enforced · no silent currency or market relabelling</span></div></div>;

  function updateComponent(key: SpreadComponentKey, value: string) {
    setComponents((current) => ({ ...current, [key]: Math.max(0, Math.round(Number(value) * 100)) }));
    setActionState("idle");
  }
  function submitDraft() {
    const permission = authorize({ principal, environment, activeOrganisationId: organisationId, workspace: "spread-fx", verb: "initiate" });
    setActionState(!permission.allowed ? "denied" : !validation.valid ? "invalid" : "submitted");
  }

  return <div className="workspace-wrap spread-fx-workspace">
    <section className="workspace-heading"><div><span className="demo-badge"><ShieldCheck size={13} /> Demonstrator data</span><h1>Spread & FX</h1><p>Compose transparent customer economics, pin explicit currency direction and publish only through governed maker-checker control.</p></div><div className="workspace-version">Scenario fx-movement-multi-market · v1.0.0</div></section>
    <section className="pricing-summary"><article><Calculator size={17} /><span>Gross spread</span><strong>{percent(activeSpreadDecision.grossSpreadBps)}</strong><small>Governed total · components editable</small></article><article><CheckCircle2 size={17} /><span>Component reconciliation</span><strong>{validation.componentTotalBps} bps</strong><small>{validation.componentTotalBps === 230 ? "Matches governed total" : "Publication blocked"}</small></article><article><Globe2 size={17} /><span>Fixed FX evidence</span><strong>3 pairs</strong><small>Explicit direction · fixed clock</small></article><article><LockKeyhole size={17} /><span>Ledger residue</span><strong>$0.00</strong><small>Balanced per currency</small></article></section>
    <section className="canonical-decision-panel"><div><span className="section-kicker">Published decision</span><h2>{activeSpreadDecision.version}</h2><p>The active version is immutable. Editing below creates a separate proposal and never changes accepted quotes.</p></div><div className="canonical-price"><span>Protection charge</span><strong>{percent(activeSpreadDecision.grossSpreadBps)}</strong><small>Effective 22 Aug 2026 · 14:00 UTC</small></div><div className="eligibility-stack"><span className="pricing-eligible">Published</span><small>Simulation eligible</small></div></section>
    <div className="spread-fx-layout"><section className="spread-editor-panel"><div className="section-heading"><div><span className="section-kicker">Draft component allocation</span><h2>Rebalance the 2.30% gross spread</h2></div><button className="evidence-link" type="button" onClick={() => setEvidence({ kind: "spread" })}>Decision evidence</button></div><div className="spread-component-grid">{(Object.keys(componentLabels) as SpreadComponentKey[]).map((key) => <label key={key}><span>{componentLabels[key]}</span><div><input type="number" min="0" step="0.01" value={(components[key] / 100).toFixed(2)} onChange={(event) => updateComponent(key, event.target.value)} aria-label={`${componentLabels[key]} percent`} /><b>%</b></div><small>Active {percent(initialComponents[key])}</small></label>)}</div><div className={`spread-reconciliation ${validation.valid ? "spread-reconciliation--valid" : "spread-reconciliation--invalid"}`} role="status"><span>Draft total</span><strong>{percent(validation.componentTotalBps)}</strong><span>{validation.valid ? "Reconciled to 2.30%" : "Must equal 2.30% before simulation"}</span></div><label className="spread-reason"><span>Required change reason</span><textarea value={reason} onChange={(event) => { setReason(event.target.value); setActionState("idle"); }} rows={2} /></label><div className="spread-action-row"><button type="button" onClick={submitDraft}>Simulate & request approval</button><span>Different RT approver · step-up required · scheduler publishes</span></div>{actionState !== "idle" && <div className={`customer-review-result customer-review-result--${actionState === "submitted" ? "submitted" : "denied"}`} role="status"><strong>{actionState === "submitted" ? "Publication request drafted" : actionState === "invalid" ? "Reconciliation failed" : "Permission denied"}</strong><span>{actionState === "submitted" ? "Impact and golden regression passed. Self-approval remains prohibited; no active decision changed." : actionState === "invalid" ? validation.errors.join(" ") : `${principal.roles.join("/")} cannot initiate Spread/FX publication.`}</span></div>}</section>
      <aside className="fx-rates-panel"><span className="section-kicker">Canonical FX evidence</span><h2>Direction is explicit</h2><button type="button" onClick={() => setEvidence({ kind: "fx", observation: fxReferenceObservations[0] })}><span>USD <ArrowRight size={12} /> CAD</span><strong>{rate(directRate.rate6dp)}</strong><small>Direct · {directRate.observationIds[0]}</small></button><button type="button" onClick={() => setEvidence({ kind: "fx", observation: fxReferenceObservations[1] })}><span>GBP <ArrowRight size={12} /> CAD</span><strong>{rate(triangulatedRate.rate6dp)}</strong><small>Via USD · 2 pinned legs</small></button><div className="pricing-integrity"><LockKeyhole size={15} /><span>No silent inversion. Stale, missing or unsupported evidence cannot be forced valid.</span></div></aside></div>
    <section className="spread-proof-row"><button type="button" onClick={() => setEvidence({ kind: "quote" })}><FileCheck2 size={18} /><span><small>Immutable quote pinning</small><strong>{pinnedMultiMarketQuote.quoteId}</strong></span><b>Inspect evidence</b></button><div><Sparkles size={18} /><span><small>Spread & FX Copilot · cited</small><strong>No intervention recommended</strong><p>All fixed conversions reconcile. Component edits remain draft-only until deterministic validation and human approval.</p></span></div></section>
    {evidence && <><button className="evidence-backdrop" type="button" aria-label="Close Spread and FX evidence" onClick={() => setEvidence(null)} /><aside ref={drawerRef} className="evidence-drawer" role="dialog" aria-modal="true" aria-label="Spread and FX evidence"><div className="evidence-drawer__heading"><div><span className="section-kicker">Evidence · immutable</span><h2>{evidence.kind === "spread" ? "Spread decision lineage" : evidence.kind === "quote" ? "Pinned quote economics" : "FX observation lineage"}</h2></div><button className="icon-button" type="button" onClick={() => setEvidence(null)} aria-label="Close Spread and FX evidence"><X size={18} /></button></div>{evidence.kind === "spread" ? <dl className="evidence-facts"><div><dt>Decision</dt><dd>{activeSpreadDecision.decisionId}</dd></div><div><dt>Version</dt><dd>{activeSpreadDecision.version}</dd></div><div><dt>Components</dt><dd>1.30% · 0.70% · 0.30%</dd></div><div><dt>Policy / algorithm</dt><dd>{activeSpreadDecision.policyVersion} · {activeSpreadDecision.algorithmVersion}</dd></div><div><dt>Maker / checker</dt><dd>{activeSpreadDecision.initiatedBy} · {activeSpreadDecision.approvedBy}</dd></div><div><dt>Provenance</dt><dd>{activeSpreadDecision.provenance} · demonstrator</dd></div></dl> : evidence.kind === "quote" ? <dl className="evidence-facts"><div><dt>Quote</dt><dd>{pinnedMultiMarketQuote.quoteId}</dd></div><div><dt>Reference price</dt><dd>{pinnedMultiMarketQuote.referencePriceDecisionId}</dd></div><div><dt>Spread version</dt><dd>{pinnedMultiMarketQuote.spreadDecisionVersion}</dd></div><div><dt>Canonical FX</dt><dd>{pinnedMultiMarketQuote.canonicalFxRateId}</dd></div><div><dt>FX adjustment</dt><dd>{pinnedMultiMarketQuote.fxAdjustmentDecisionVersion}</dd></div><div><dt>Rules</dt><dd>{pinnedMultiMarketQuote.rulesVersion}</dd></div></dl> : <dl className="evidence-facts"><div><dt>Observation</dt><dd>{evidence.observation.observationId}</dd></div><div><dt>Direction</dt><dd>{evidence.observation.baseCurrency} → {evidence.observation.quoteCurrency}</dd></div><div><dt>Rate</dt><dd>{rate(evidence.observation.rate6dp)}</dd></div><div><dt>Observed / ingested</dt><dd>{evidence.observation.sourceObservedAt} · {evidence.observation.ingestedAt}</dd></div><div><dt>Licence</dt><dd>{evidence.observation.licenceClass}</dd></div><div><dt>Payload hash</dt><dd>{evidence.observation.rawPayloadSha256}</dd></div></dl>}<div className="customer-evidence-boundary"><LockKeyhole size={15} /><span>Read only · later decisions never recalculate accepted quotes or historical conversions.</span></div></aside></>}
    <footer className="demo-footer"><span>Provenance · illustrative-fixed</span><span>Scenario 11 · injected clock</span><span>No live FX or money movement</span></footer>
  </div>;
}
