"use client";
import { useState } from "react";
import { CheckCircle2, LockKeyhole, ReceiptText, ShieldCheck, TriangleAlert } from "lucide-react";
import { authorize, type Environment, type Principal } from "@fuelcap/authz";
import { createCorrectionJournal, journalBalance, reconciliationBreak, safeguardingHolds, safeguardingProjection, settlementJournal } from "@fuelcap/demo-data/transactions-ledger";
const money = (minor: number) => `$${(minor / 100).toLocaleString("en-US", { minimumFractionDigits: 2 })}`;
export function TransactionsLedgerWorkspace({ organisationId, principal, environment }: { organisationId: string; principal: Principal; environment: Environment }) {
  const [selected, setSelected] = useState<"journal" | "position" | "break">("journal");
  const [action, setAction] = useState<"idle" | "denied" | "pending" | "corrected">("idle");
  const balance = journalBalance(settlementJournal);
  if (organisationId !== "org-fuelcap-global") return <div className="workspace-wrap"><div className="workspace-empty"><ReceiptText size={25}/><h1>Ledger controls are platform-scoped</h1><p>Switch to FuelCap Global. Tenant contexts never inherit another organisation’s journals.</p></div></div>;
  const request = () => setAction(authorize({ principal, environment, activeOrganisationId: organisationId, workspace: "transactions-ledger", verb: "initiate" }).allowed ? "pending" : "denied");
  const approve = () => { createCorrectionJournal(settlementJournal, "principal-fr-maker", "principal-fr-checker", "MATCH-017"); setAction("corrected"); };
  return <div className="workspace-wrap"><section className="workspace-heading"><div><span className="demo-badge"><ShieldCheck size={13}/> Demonstrator data</span><h1>Transactions & Ledger</h1><p>Immutable journals explain every balance and four-decimal fuel position.</p></div><div className="workspace-version">Sequence {settlementJournal.sequence}</div></section>
    <section className="pricing-summary"><article><ShieldCheck size={17}/><span>Safeguarded assets</span><strong>{money(safeguardingProjection.safeguardedMinor)}</strong><small>Invariant {safeguardingHolds() ? "holds" : "breached"}</small></article><article><ReceiptText size={17}/><span>Customer liabilities</span><strong>{money(safeguardingProjection.customerLiabilityMinor)}</strong><small>Journal projection</small></article><article><CheckCircle2 size={17}/><span>Journal</span><strong>{balance.balanced ? "Balanced" : "Blocked"}</strong><small>Debit = credit · USD</small></article><article><TriangleAlert size={17}/><span>Open breaks</span><strong>1</strong><small>{money(reconciliationBreak.differenceMinor)} pending match</small></article></section>
    <div className="pricing-layout"><section className="pricing-candidates-panel"><div className="section-heading"><div><span className="section-kicker">Transaction lifecycle</span><h2>Boundary settlement · {settlementJournal.transactionId}</h2></div></div><div className="pricing-candidate-list">{(["journal","position","break"] as const).map((item) => <button key={item} type="button" className={`pricing-candidate ${item === "break" ? "pricing-candidate--rejected" : "pricing-candidate--selected"}`} onClick={() => setSelected(item)}><span><strong>{item === "journal" ? "Double-entry journal" : item === "position" ? "Position movement" : "External match pending"}</strong><small>{item === "journal" ? settlementJournal.journalId : item === "position" ? settlementJournal.movements[0].positionId : reconciliationBreak.breakId}</small></span><span><strong>{item === "journal" ? money(balance.debit) : item === "position" ? "20.0000 gal" : money(reconciliationBreak.differenceMinor)}</strong><small>{item === "break" ? "Original immutable" : "Reconciled evidence"}</small></span><b>{item === "break" ? "OPEN" : "BALANCED"}</b><i>Inspect</i></button>)}</div></section>
      <aside className="pricing-controls-panel"><span className="section-kicker">Evidence · immutable</span><h2>{selected === "journal" ? "Journal lines" : selected === "position" ? "Position movement" : "Reconciliation break"}</h2><dl>{selected === "journal" ? settlementJournal.lines.map((line) => <div key={line.lineId}><dt>{line.side} · {line.account}</dt><dd>{money(line.amountMinor)}</dd></div>) : selected === "position" ? <><div><dt>Position</dt><dd>{settlementJournal.movements[0].positionId}</dd></div><div><dt>Movement</dt><dd>REDEEM · 20.0000 gal</dd></div></> : <><div><dt>Break</dt><dd>{reconciliationBreak.breakId}</dd></div><div><dt>Reason</dt><dd>{reconciliationBreak.reason}</dd></div></>}</dl><div className="spread-action-row"><button type="button" onClick={request}>Request correction</button></div>{action === "pending" && <div className="spread-action-row"><button type="button" onClick={approve}>Different-FR approval</button></div>}{action !== "idle" && <div className={`customer-review-result customer-review-result--${action === "denied" ? "denied" : "submitted"}`} role="status"><strong>{action === "denied" ? "Permission denied" : action === "corrected" ? "Linked correction created" : "Approval pending"}</strong><span>{action === "corrected" ? "Original preserved; new sequence and hash recorded." : "Self-approval prohibited."}</span></div>}<div className="pricing-integrity"><LockKeyhole size={15}/><span>Original postings cannot be edited or deleted.</span></div></aside></div>
    <footer className="demo-footer"><span>Integer minor units</span><span>Four-decimal positions</span><span>No live money movement</span></footer></div>;
}
