import { describe, expect, it } from "vitest";
import { acceptAssuranceEvidence, acceptEvidenceRoomSubmission, assuranceCommissioningPacks, assuranceEngagements, assuranceEvidenceRooms, assurancePortfolio, createAssuranceCommissioningPack, decideSingleFlightDeployment, evaluateAssurancePortfolio, evaluateProductionReadiness, evaluateServiceTopology, issueAssuranceEvidenceRoom, operationalRunbooks, productionReadinessAssessment, productionReadinessControls, readinessEvidence, recoveryExercises, renderServiceTopology, seededTopologyAssessment, singleFlightDeploymentRunbook, submitAssuranceEvidence, supportReadiness, validateAssessorAppointment, type AssuranceEngagement, type AssessorAppointment, type AssuranceSubmission, type DeploymentSnapshot, type ReadinessEvidence, type RenderServiceObservation } from "./index";
const external = (controlId: string, kind: string): ReadinessEvidence => ({ evidenceId: `EXT-${controlId}-${kind}`, controlId, kind, status: "PASS", source: "INDEPENDENT", issuedAt: "2026-08-27T00:00:00Z", expiresAt: "2027-08-27T00:00:00Z", contentHash: `sha256:${controlId}-${kind}`, makerActorId: "external-maker", checkerActorId: "external-checker" });
const allExternal = [external("SEC-PENTEST", "scope"), external("SEC-PENTEST", "report"), external("SEC-PENTEST", "remediation-verification"), external("PRI-DPIA", "approved-dpia"), external("RES-DR", "restore-report")];
const expectedCommit = "68d49cfa86672c64b41eeb53fa83235e6d31d4de";
const snapshot = (deployId: string, status: DeploymentSnapshot["status"], commit = expectedCommit): DeploymentSnapshot => ({ deployId, status, commit, createdAt: "2026-08-28T12:16:00Z", updatedAt: "2026-08-28T12:17:00Z" });
const run = (overrides = {}) => evaluateProductionReadiness({ controls: productionReadinessControls, evidence: [...readinessEvidence, ...allExternal], exercises: recoveryExercises, runbooks: operationalRunbooks, support: supportReadiness, assessedAt: "2026-08-27T15:00:00Z", ...overrides });
describe("production readiness programme", () => {
  it("keeps the seeded programme blocked and not externally certified", () => expect(productionReadinessAssessment).toMatchObject({ decision: "BLOCKED", scoreBps: 6250, externallyCertified: false, pilotMayStart: false }));
  it("names independent penetration, privacy and recovery evidence blockers", () => expect(productionReadinessAssessment.blockers).toEqual(expect.arrayContaining([expect.stringContaining("SEC-PENTEST"), expect.stringContaining("PRI-DPIA"), expect.stringContaining("RES-DR")])));
  it("becomes pilot-ready only with all independent evidence", () => expect(run()).toMatchObject({ decision: "READY_FOR_PILOT", scoreBps: 10000, externallyCertified: true, pilotMayStart: true }));
  it("rejects internal evidence for external attestations", () => expect(run({ evidence: [...readinessEvidence, ...allExternal.map((item) => ({ ...item, source: "INTERNAL" as const }))] }).externallyCertified).toBe(false));
  it("rejects expired and self-checked evidence", () => { expect(run({ evidence: [...readinessEvidence, ...allExternal.map((item, index) => index ? item : { ...item, expiresAt: "2026-08-01T00:00:00Z" })] }).decision).toBe("BLOCKED"); expect(run({ evidence: [...readinessEvidence, ...allExternal.map((item, index) => index ? item : { ...item, checkerActorId: item.makerActorId })] }).decision).toBe("BLOCKED"); });
  it("requires every evidence kind for multi-part controls", () => expect(run({ evidence: [...readinessEvidence, ...allExternal.filter(({ kind }) => kind !== "remediation-verification")] }).decision).toBe("BLOCKED"));
  it("blocks failed recovery and missed RTO or RPO", () => { expect(run({ exercises: [{ ...recoveryExercises[0], status: "FAIL" as const }] }).decision).toBe("BLOCKED"); expect(run({ exercises: [{ ...recoveryExercises[0], recoveryTimeSeconds: 1801 }] }).decision).toBe("BLOCKED"); expect(run({ exercises: [{ ...recoveryExercises[0], recoveryPointSeconds: 301 }] }).decision).toBe("BLOCKED"); });
  it("requires deterministic projection rebuild evidence", () => expect(run({ exercises: [{ ...recoveryExercises[0], projectionRebuildVerified: false }] }).decision).toBe("BLOCKED"));
  it("requires approved owned runbooks with escalation, rollback and verification", () => expect(run({ runbooks: [{ ...operationalRunbooks[0], approved: false }, ...operationalRunbooks.slice(1)] }).decision).toBe("BLOCKED"));
  it("requires rehearsed segregated support handoff", () => { expect(run({ support: { ...supportReadiness, handoffRehearsed: false } }).decision).toBe("BLOCKED"); expect(run({ support: { ...supportReadiness, secondaryOwner: supportReadiness.primaryOwner } }).decision).toBe("BLOCKED"); });
  it("reports all four readiness domains", () => expect(run().domainResults.map(({ domain }) => domain)).toEqual(["SECURITY", "PRIVACY", "RESILIENCE", "OPERATIONS"]));
  it("rejects invalid assessment time", () => expect(() => run({ assessedAt: "invalid" })).toThrow(/valid/));
});

describe("single-flight release deployment", () => {
  it("waits while any deployment is active", () => expect(decideSingleFlightDeployment({ expectedCommit, deployments: [snapshot("dep-auto", "update_in_progress")], cacheClearDeployId: null, automaticDeployGraceExpired: false })).toMatchObject({ action: "WAIT", activeDeployIds: ["dep-auto"] }));
  it("waits for an unrelated active release instead of overtaking it", () => expect(decideSingleFlightDeployment({ expectedCommit, deployments: [snapshot("dep-other", "build_in_progress", "1ca3cb719a343433106b69d288b11454ba06c1d5")], cacheClearDeployId: null, automaticDeployGraceExpired: true })).toMatchObject({ action: "WAIT", reason: "another release is active" }));
  it("triggers cache clear only after the automatic deployment settles", () => expect(decideSingleFlightDeployment({ expectedCommit, deployments: [snapshot("dep-auto", "live")], cacheClearDeployId: null, automaticDeployGraceExpired: false })).toMatchObject({ action: "TRIGGER_CACHE_CLEAR" }));
  it("uses a bounded grace when no automatic deployment appears", () => expect(decideSingleFlightDeployment({ expectedCommit, deployments: [], cacheClearDeployId: null, automaticDeployGraceExpired: true })).toMatchObject({ action: "TRIGGER_CACHE_CLEAR" }));
  it("smokes only the matching stable cache-clear deployment", () => expect(decideSingleFlightDeployment({ expectedCommit, deployments: [snapshot("dep-clear", "live")], cacheClearDeployId: "dep-clear", automaticDeployGraceExpired: true })).toMatchObject({ action: "SMOKE", deployId: "dep-clear" }));
  it("fails closed for missing, failed or mismatched cache-clear evidence", () => { expect(decideSingleFlightDeployment({ expectedCommit, deployments: [], cacheClearDeployId: "missing", automaticDeployGraceExpired: true }).action).toBe("REVIEW_FAILURE"); expect(decideSingleFlightDeployment({ expectedCommit, deployments: [snapshot("dep-clear", "build_failed")], cacheClearDeployId: "dep-clear", automaticDeployGraceExpired: true }).action).toBe("REVIEW_FAILURE"); expect(decideSingleFlightDeployment({ expectedCommit, deployments: [snapshot("dep-clear", "update_failed")], cacheClearDeployId: "dep-clear", automaticDeployGraceExpired: true }).action).toBe("REVIEW_FAILURE"); expect(decideSingleFlightDeployment({ expectedCommit, deployments: [snapshot("dep-clear", "live", "1ca3cb719a343433106b69d288b11454ba06c1d5")], cacheClearDeployId: "dep-clear", automaticDeployGraceExpired: true }).action).toBe("REVIEW_FAILURE"); });
  it("rejects malformed or duplicate provenance", () => { expect(() => decideSingleFlightDeployment({ expectedCommit: "short", deployments: [], cacheClearDeployId: null, automaticDeployGraceExpired: false })).toThrow(/full SHA/); expect(() => decideSingleFlightDeployment({ expectedCommit, deployments: [snapshot("same", "live"), snapshot("same", "deactivated")], cacheClearDeployId: null, automaticDeployGraceExpired: false })).toThrow(/unique/); });
  it("keeps the runbook non-authorising", () => expect(singleFlightDeploymentRunbook).toMatchObject({ liveActivationAuthorised: false, pollIntervalSeconds: 10, automaticDiscoveryGraceSeconds: 300 }));
});

describe("independent assurance commissioning", () => {
  const submitted = (controlId: string, deliverables: readonly string[]): AssuranceEngagement => ({ ...assuranceEngagements.find((item) => item.controlId === controlId)!, state: "EVIDENCE_SUBMITTED", submittedEvidenceIds: deliverables });
  it("tracks all three external gates without claiming commission or acceptance", () => expect(assurancePortfolio).toMatchObject({ status: "AT_RISK", commissioned: 0, accepted: 0, total: 3, outstandingDeliverables: 5 }));
  it("rejects unknown or internal controls from the independent portfolio", () => expect(evaluateAssurancePortfolio([{ ...assuranceEngagements[0], controlId: "OPS-SUPPORT" }], productionReadinessControls, "2026-08-27T15:00:00Z").blockers[0]).toMatch(/not an independent/));
  it("detects missing assessors and scope self-approval", () => expect(evaluateAssurancePortfolio([{ ...assuranceEngagements[0], assessorOrganisation: "", approvedBy: assuranceEngagements[0].scopedBy }], productionReadinessControls, "2026-08-27T15:00:00Z").blockers).toHaveLength(3));
  it("marks incomplete engagements overdue after their due date", () => expect(evaluateAssurancePortfolio(assuranceEngagements, productionReadinessControls, "2026-11-01T00:00:00Z").status).toBe("OVERDUE"));
  it("requires submitted state and an independent acceptance reviewer", () => { expect(() => acceptAssuranceEvidence(assuranceEngagements[0], allExternal, "reviewer")).toThrow(/submitted/); expect(() => acceptAssuranceEvidence(submitted("SEC-PENTEST", ["scope", "report", "remediation-verification"]), allExternal, "security-lead")).toThrow(/independent/); });
  it("requires every scoped deliverable to have passing independent evidence", () => expect(() => acceptAssuranceEvidence(submitted("SEC-PENTEST", ["scope", "report", "remediation-verification"]), allExternal.slice(0, 2), "acceptance-reviewer")).toThrow(/deliverables/));
  it("accepts only matching independent evidence after segregated review", () => expect(acceptAssuranceEvidence(submitted("SEC-PENTEST", ["scope", "report", "remediation-verification"]), allExternal, "acceptance-reviewer")).toMatchObject({ state: "ACCEPTED", acceptedEvidenceIds: ["EXT-SEC-PENTEST-scope", "EXT-SEC-PENTEST-report", "EXT-SEC-PENTEST-remediation-verification"] }));
  it("rejects an invalid portfolio timestamp", () => expect(() => evaluateAssurancePortfolio(assuranceEngagements, productionReadinessControls, "invalid")).toThrow(/valid/));
});

describe("assessor-ready commissioning packs", () => {
  const appointment: AssessorAppointment = { engagementId: "ASR-PENTEST-001", assessorOrganisation: "Example Independent Assurance Ltd", leadAssessor: "external-lead", independenceDeclared: true, conflictsDisclosed: [], confidentialityAccepted: true, dataHandlingAccepted: true, appointedBy: "security-lead", approvedBy: "compliance-lead", appointedAt: "2026-09-01T09:00:00Z" };
  it("creates one approved pack per independent gate", () => expect(assuranceCommissioningPacks.map(({ controlId }) => controlId)).toEqual(["SEC-PENTEST", "PRI-DPIA", "RES-DR"]));
  it("pins scope, exclusions, handling, deliverables and acceptance criteria", () => expect(assuranceCommissioningPacks.every((pack) => pack.inScope.length && pack.outOfScope.length && pack.rulesOfEngagement.length && pack.evidenceHandling.length && pack.requiredDeliverables.length === pack.acceptanceCriteria.length && pack.contentHash.startsWith("sha256:"))).toBe(true));
  it("rejects unsupported commissioning-pack controls", () => expect(() => createAssuranceCommissioningPack({ ...assuranceEngagements[0], controlId: "OPS-SUPPORT" })).toThrow(/approved/));
  it("accepts a complete segregated appointment", () => expect(validateAssessorAppointment(appointment, assuranceEngagements[0])).toEqual({ valid: true, blockers: [] }));
  it("rejects mismatched, unidentified or conflicted assessors", () => expect(validateAssessorAppointment({ ...appointment, engagementId: "wrong", assessorOrganisation: "", conflictsDisclosed: ["prior implementation role"] }, assuranceEngagements[0]).blockers).toHaveLength(3));
  it("requires accepted handling terms and segregated approval", () => expect(validateAssessorAppointment({ ...appointment, confidentialityAccepted: false, dataHandlingAccepted: false, approvedBy: appointment.appointedBy }, assuranceEngagements[0]).blockers).toHaveLength(2));
  it("requires a valid appointment timestamp", () => expect(validateAssessorAppointment({ ...appointment, appointedAt: "invalid" }, assuranceEngagements[0]).valid).toBe(false));
});

describe("assurance evidence room", () => {
  const appointment: AssessorAppointment = { engagementId: "ASR-PENTEST-001", assessorOrganisation: "Example Independent Assurance Ltd", leadAssessor: "external-lead", independenceDeclared: true, conflictsDisclosed: [], confidentialityAccepted: true, dataHandlingAccepted: true, appointedBy: "security-lead", approvedBy: "compliance-lead", appointedAt: "2026-09-01T09:00:00Z" };
  const engagement = assuranceEngagements[0]; const pack = assuranceCommissioningPacks[0];
  const issued = () => issueAssuranceEvidenceRoom(assuranceEvidenceRooms[0], pack, engagement, appointment, "security-lead", "2026-09-01T10:00:00Z");
  const submission = (overrides: Partial<AssuranceSubmission> = {}): AssuranceSubmission => ({ submissionId: "SUB-PENTEST-001", engagementId: engagement.engagementId, assessorOrganisation: appointment.assessorOrganisation, submittedAt: "2026-09-15T10:00:00Z", evidence: allExternal.filter(({ controlId }) => controlId === "SEC-PENTEST"), findings: [], supersedesSubmissionId: null, contentHash: "sha256:submission-pentest-001", ...overrides });
  it("prepares one unopened evidence room per commissioning pack", () => expect(assuranceEvidenceRooms.every((room) => room.state === "PREPARED" && room.chainOfCustody.length === 0)).toBe(true));
  it("issues only a matching pack with a valid appointment and authorised issuer", () => expect(issued()).toMatchObject({ state: "ISSUED", assessorOrganisation: appointment.assessorOrganisation }));
  it("rejects invalid appointment or issuer during issue", () => { expect(() => issueAssuranceEvidenceRoom(assuranceEvidenceRooms[0], pack, engagement, { ...appointment, independenceDeclared: false }, "security-lead", "2026-09-01T10:00:00Z")).toThrow(/invalid/); expect(() => issueAssuranceEvidenceRoom(assuranceEvidenceRooms[0], pack, engagement, appointment, "other", "2026-09-01T10:00:00Z")).toThrow(/issuer/); });
  it("accepts matching independent evidence and appends custody", () => expect(submitAssuranceEvidence(issued(), submission())).toMatchObject({ state: "UNDER_REVIEW", submissionIds: ["SUB-PENTEST-001"] }));
  it("rejects mismatched assessor, internal evidence and invalid integrity", () => { expect(() => submitAssuranceEvidence(issued(), submission({ assessorOrganisation: "wrong" }))).toThrow(/assessor/); expect(() => submitAssuranceEvidence(issued(), submission({ evidence: [{ ...allExternal[0], source: "INTERNAL" }] }))).toThrow(/independent/); expect(() => submitAssuranceEvidence(issued(), submission({ contentHash: "bad" }))).toThrow(/integrity/); });
  it("is idempotent for a repeated submission id", () => { const reviewed = submitAssuranceEvidence(issued(), submission()); expect(submitAssuranceEvidence(reviewed, submission())).toBe(reviewed); });
  it("requires immutable supersession for later submissions", () => { const reviewed = submitAssuranceEvidence(issued(), submission()); expect(() => submitAssuranceEvidence(reviewed, submission({ submissionId: "SUB-PENTEST-002" }))).toThrow(/supersede/); });
  it("blocks unresolved high or critical findings", () => { const item = submission({ findings: [{ findingId: "F-1", severity: "HIGH", title: "Tenant escape", status: "OPEN", remediationEvidenceId: null, acceptedRiskBy: null }] }); const reviewed = submitAssuranceEvidence(issued(), item); expect(() => acceptEvidenceRoomSubmission(reviewed, item, engagement, "acceptance-reviewer")).toThrow(/Blocking/); });
  it("requires remediation evidence for remediated findings", () => { const item = submission({ findings: [{ findingId: "F-1", severity: "HIGH", title: "Tenant escape", status: "REMEDIATED", remediationEvidenceId: null, acceptedRiskBy: null }] }); const reviewed = submitAssuranceEvidence(issued(), item); expect(() => acceptEvidenceRoomSubmission(reviewed, item, engagement, "acceptance-reviewer")).toThrow(/remediation/); });
  it("accepts a complete latest submission through segregated review", () => { const item = submission({ findings: [{ findingId: "F-1", severity: "HIGH", title: "Tenant escape", status: "REMEDIATED", remediationEvidenceId: "EXT-RETEST-001", acceptedRiskBy: null }] }); const reviewed = submitAssuranceEvidence(issued(), item); expect(acceptEvidenceRoomSubmission(reviewed, item, engagement, "acceptance-reviewer")).toMatchObject({ state: "ACCEPTED", acceptedSubmissionId: item.submissionId }); });
});

describe("governed Render service topology", () => {
  const observations = (): RenderServiceObservation[] => renderServiceTopology.map((service) => ({
    serviceId: service.serviceId,
    serviceName: service.serviceName,
    publicUrl: service.publicUrl,
    rootDirectory: service.rootDirectory,
    buildCommand: service.buildCommand,
    startCommand: service.startCommand,
    nodeVersion: service.nodeVersion,
    autoDeploy: service.autoDeploy,
    liveCommit: expectedCommit,
    latestDeployStatus: "live",
  }));

  it("pins one canonical consumer, admin and marketing service", () => expect(seededTopologyAssessment.canonicalRoles).toEqual({ CONSUMER: "srv-d9hltsfaqgkc73al7lig", ADMIN: "srv-da49ao2fngtc7388cec0", MARKETING: "srv-d9ve5ku1egvs73e3brk0" }));
  it("keeps the development topology limited to three canonical services", () => { expect(renderServiceTopology).toHaveLength(3); expect(seededTopologyAssessment).toMatchObject({ decision: "ALIGNED", blockers: [], deletionAuthorised: false }); expect(renderServiceTopology.map(({ serviceName }) => serviceName)).not.toContain("fuel-cap"); });
  it("detects command, root, runtime and auto-deploy drift", () => { const items = observations(); items[0] = { ...items[0], rootDirectory: "apps/admin", buildCommand: "npm ci", nodeVersion: "20.18.0", autoDeploy: false }; expect(evaluateServiceTopology(renderServiceTopology, items).blockers[0]).toMatch(/root directory, build command, Node version, auto-deploy/); });
  it("requires a provenance-valid live deployment", () => { const items = observations(); items[1] = { ...items[1], latestDeployStatus: "build_failed", liveCommit: null }; expect(evaluateServiceTopology(renderServiceTopology, items).blockers).toContain("fuelcap-app: no provenance-valid live deployment"); });
  it("blocks missing and unregistered services", () => { const items = observations().slice(1); items.push({ ...items[0], serviceId: "srv-unknown", serviceName: "unknown" }); const blockers = evaluateServiceTopology(renderServiceTopology, items).blockers; expect(blockers).toContain("fuel-cap-1: service observation is missing"); expect(blockers).toContain("unknown: unregistered Render service"); });
  it("rejects duplicate contract and observation identifiers", () => { expect(() => evaluateServiceTopology([...renderServiceTopology, renderServiceTopology[0]], observations())).toThrow(/contract identifiers/); expect(() => evaluateServiceTopology(renderServiceTopology, [...observations(), observations()[0]])).toThrow(/Observed service identifiers/); });
  it("aligns all three registered development services", () => expect(evaluateServiceTopology(renderServiceTopology, observations())).toMatchObject({ decision: "ALIGNED", alignedServiceIds: renderServiceTopology.map(({ serviceId }) => serviceId) }));
});
