import { describe, expect, it } from "vitest";
import { evaluateProductionReadiness, operationalRunbooks, productionReadinessAssessment, productionReadinessControls, readinessEvidence, recoveryExercises, supportReadiness, type ReadinessEvidence } from "./index";
const external = (controlId: string, kind: string): ReadinessEvidence => ({ evidenceId: `EXT-${controlId}-${kind}`, controlId, kind, status: "PASS", source: "INDEPENDENT", issuedAt: "2026-08-27T00:00:00Z", expiresAt: "2027-08-27T00:00:00Z", contentHash: `sha256:${controlId}-${kind}`, makerActorId: "external-maker", checkerActorId: "external-checker" });
const allExternal = [external("SEC-PENTEST", "scope"), external("SEC-PENTEST", "report"), external("SEC-PENTEST", "remediation-verification"), external("PRI-DPIA", "approved-dpia"), external("RES-DR", "restore-report")];
const run = (overrides = {}) => evaluateProductionReadiness({ controls: productionReadinessControls, evidence: [...readinessEvidence, ...allExternal], exercises: recoveryExercises, runbooks: operationalRunbooks, support: supportReadiness, assessedAt: "2026-08-27T15:00:00Z", ...overrides });
describe("production readiness programme", () => {
  it("keeps the seeded programme blocked and not externally certified", () => expect(productionReadinessAssessment).toMatchObject({ decision: "BLOCKED", scoreBps: 6250, externallyCertified: false, pilotMayStart: false }));
  it("names independent penetration, privacy and recovery evidence blockers", () => expect(productionReadinessAssessment.blockers).toEqual(expect.arrayContaining([expect.stringContaining("SEC-PENTEST"), expect.stringContaining("PRI-DPIA"), expect.stringContaining("RES-DR")])));
  it("becomes pilot-ready only with all independent evidence", () => expect(run()).toMatchObject({ decision: "READY_FOR_PILOT", scoreBps: 10000, externallyCertified: true, pilotMayStart: true }));
  it("rejects internal evidence for external attestations", () => expect(run({ evidence: [...readinessEvidence, ...allExternal.map((item) => ({ ...item, source: "INTERNAL" as const }))] }).externallyCertified).toBe(false));
  it("rejects expired and self-checked evidence", () => { expect(run({ evidence: [...readinessEvidence, ...allExternal.map((item, index) => index ? item : { ...item, expiresAt: "2026-08-01T00:00:00Z" })] }).decision).toBe("BLOCKED"); expect(run({ evidence: [...readinessEvidence, ...allExternal.map((item, index) => index ? item : { ...item, checkerActorId: item.makerActorId })] }).decision).toBe("BLOCKED"); });
  it("requires every evidence kind for multi-part controls", () => expect(run({ evidence: [...readinessEvidence, ...allExternal.filter(({ kind }) => kind !== "remediation-verification")] }).decision).toBe("BLOCKED"));
  it("blocks failed recovery and missed RTO or RPO", () => { expect(run({ exercises: [{ ...recoveryExercises[0], status: "FAIL" as const }] }).decision).toBe("BLOCKED"); expect(run({ exercises: [{ ...recoveryExercises[0], recoveryTimeSeconds: 1801 }] }).decision).toBe("BLOCKED"); expect(run({ exercises: [{ ...recoveryExercises[0], recoveryPointSeconds: 301 }] }).decision).toBe("BLOCKED"); });
  it("requires deterministic projection rebuild evidence", () => expect(run({ exercises: [{ ...recoveryExercises[0], projectionRebuildVerified: false }] }).decision).toBe("BLOCKED"));
  it("requires approved owned runbooks with escalation, rollback and verification", () => expect(run({ runbooks: [{ ...operationalRunbooks[0], approved: false }, ...operationalRunbooks.slice(1)] }).decision).toBe("BLOCKED"));
  it("requires rehearsed segregated support handoff", () => { expect(run({ support: { ...supportReadiness, handoffRehearsed: false } }).decision).toBe("BLOCKED"); expect(run({ support: { ...supportReadiness, secondaryOwner: supportReadiness.primaryOwner } }).decision).toBe("BLOCKED"); });
  it("reports all four readiness domains", () => expect(run().domainResults.map(({ domain }) => domain)).toEqual(["SECURITY", "PRIVACY", "RESILIENCE", "OPERATIONS"]));
  it("rejects invalid assessment time", () => expect(() => run({ assessedAt: "invalid" })).toThrow(/valid/));
});
