export type ReadinessDomain = "SECURITY" | "PRIVACY" | "RESILIENCE" | "OPERATIONS";
export type EvidenceStatus = "PASS" | "FAIL" | "OPEN" | "EXPIRED";
export interface ReadinessControl { readonly controlId: string; readonly domain: ReadinessDomain; readonly title: string; readonly ownerRole: string; readonly externalAttestationRequired: boolean; readonly blocksPilot: boolean; readonly requiredEvidenceKinds: readonly string[]; }
export interface ReadinessEvidence { readonly evidenceId: string; readonly controlId: string; readonly kind: string; readonly status: EvidenceStatus; readonly source: "INTERNAL" | "INDEPENDENT"; readonly issuedAt: string; readonly expiresAt: string; readonly contentHash: string; readonly makerActorId: string; readonly checkerActorId: string; }
export interface RecoveryExercise { readonly exerciseId: string; readonly capability: string; readonly status: "PASS" | "FAIL"; readonly exercisedAt: string; readonly recoveryTimeSeconds: number; readonly recoveryPointSeconds: number; readonly rtoSeconds: number; readonly rpoSeconds: number; readonly projectionRebuildVerified: boolean; readonly evidenceIds: readonly string[]; }
export interface Runbook { readonly runbookId: string; readonly capability: string; readonly owner: string; readonly version: string; readonly approved: boolean; readonly lastRehearsedAt: string; readonly escalationRoute: readonly string[]; readonly rollbackSteps: readonly string[]; readonly verificationSteps: readonly string[]; }
export interface SupportReadiness { readonly rotaId: string; readonly coverage: "BUSINESS_HOURS" | "24X7"; readonly primaryOwner: string; readonly secondaryOwner: string; readonly incidentCommander: string; readonly customerCommunicationOwner: string; readonly severityResponseMinutes: Readonly<Record<"SEV1" | "SEV2" | "SEV3", number>>; readonly handoffRehearsed: boolean; readonly evidenceId: string; }
export interface ReadinessAssessment { readonly decision: "READY_FOR_PILOT" | "BLOCKED"; readonly assessedAt: string; readonly scoreBps: number; readonly domainResults: readonly Readonly<{ domain: ReadinessDomain; passed: number; total: number; status: "PASS" | "BLOCKED" }>[]; readonly blockers: readonly string[]; readonly evidenceIds: readonly string[]; readonly externallyCertified: boolean; readonly pilotMayStart: boolean; }

export const productionReadinessControls: readonly ReadinessControl[] = [
  { controlId: "SEC-PENTEST", domain: "SECURITY", title: "Independent penetration test", ownerRole: "Platform Security", externalAttestationRequired: true, blocksPilot: true, requiredEvidenceKinds: ["scope", "report", "remediation-verification"] },
  { controlId: "SEC-SECRETS", domain: "SECURITY", title: "Secrets and credential isolation", ownerRole: "Platform Operations", externalAttestationRequired: false, blocksPilot: true, requiredEvidenceKinds: ["rotation-test"] },
  { controlId: "PRI-DPIA", domain: "PRIVACY", title: "Jurisdictional privacy impact assessment", ownerRole: "Compliance", externalAttestationRequired: true, blocksPilot: true, requiredEvidenceKinds: ["approved-dpia"] },
  { controlId: "PRI-RETENTION", domain: "PRIVACY", title: "Retention and rights workflow exercise", ownerRole: "Compliance", externalAttestationRequired: false, blocksPilot: true, requiredEvidenceKinds: ["rights-exercise", "deletion-verification"] },
  { controlId: "RES-DR", domain: "RESILIENCE", title: "Independent disaster-recovery assurance", ownerRole: "Platform Operations", externalAttestationRequired: true, blocksPilot: true, requiredEvidenceKinds: ["restore-report"] },
  { controlId: "RES-RESTORE", domain: "RESILIENCE", title: "Ledger-safe restoration exercise", ownerRole: "Finance Operations", externalAttestationRequired: false, blocksPilot: true, requiredEvidenceKinds: ["exercise-result"] },
  { controlId: "OPS-RUNBOOKS", domain: "OPERATIONS", title: "Critical capability runbook coverage", ownerRole: "Operations", externalAttestationRequired: false, blocksPilot: true, requiredEvidenceKinds: ["runbook-catalogue"] },
  { controlId: "OPS-SUPPORT", domain: "OPERATIONS", title: "Support rota and escalation rehearsal", ownerRole: "Operations", externalAttestationRequired: false, blocksPilot: true, requiredEvidenceKinds: ["handoff-rehearsal"] },
] as const;

const currentEvidence = (control: ReadinessControl, evidence: readonly ReadinessEvidence[], assessedAt: number) => evidence.filter((item) => item.controlId === control.controlId && item.status === "PASS" && item.makerActorId !== item.checkerActorId && item.contentHash.startsWith("sha256:") && Number.isFinite(Date.parse(item.expiresAt)) && Date.parse(item.expiresAt) > assessedAt && (!control.externalAttestationRequired || item.source === "INDEPENDENT"));
export function evaluateProductionReadiness(input: Readonly<{ controls: readonly ReadinessControl[]; evidence: readonly ReadinessEvidence[]; exercises: readonly RecoveryExercise[]; runbooks: readonly Runbook[]; support: SupportReadiness; assessedAt: string }>): ReadinessAssessment {
  const assessedAt = Date.parse(input.assessedAt); if (!Number.isFinite(assessedAt)) throw new Error("A valid readiness assessment timestamp is required.");
  const blockers: string[] = []; const passedControls: string[] = [];
  for (const control of input.controls) {
    const items = currentEvidence(control, input.evidence, assessedAt); const kinds = new Set(items.map(({ kind }) => kind));
    if (!control.requiredEvidenceKinds.every((kind) => kinds.has(kind))) { if (control.blocksPilot) blockers.push(`${control.controlId}: required current evidence is incomplete`); continue; }
    passedControls.push(control.controlId);
  }
  for (const exercise of input.exercises) if (exercise.status !== "PASS" || exercise.recoveryTimeSeconds > exercise.rtoSeconds || exercise.recoveryPointSeconds > exercise.rpoSeconds || !exercise.projectionRebuildVerified || !exercise.evidenceIds.length) blockers.push(`${exercise.exerciseId}: recovery objective or verification failed`);
  for (const runbook of input.runbooks) if (!runbook.approved || !runbook.owner.trim() || !runbook.escalationRoute.length || !runbook.rollbackSteps.length || !runbook.verificationSteps.length) blockers.push(`${runbook.runbookId}: operational runbook incomplete`);
  if (!input.support.handoffRehearsed || !input.support.primaryOwner.trim() || input.support.primaryOwner === input.support.secondaryOwner || !input.support.evidenceId.trim()) blockers.push(`${input.support.rotaId}: support handoff or segregation incomplete`);
  const domainResults = (["SECURITY", "PRIVACY", "RESILIENCE", "OPERATIONS"] as const).map((domain) => { const controls = input.controls.filter((item) => item.domain === domain); const passed = controls.filter((item) => passedControls.includes(item.controlId)).length; return { domain, passed, total: controls.length, status: passed === controls.length ? "PASS" as const : "BLOCKED" as const }; });
  const scoreBps = input.controls.length ? Math.round(passedControls.length / input.controls.length * 10_000) : 0;
  const externallyCertified = input.controls.filter(({ externalAttestationRequired }) => externalAttestationRequired).every((control) => passedControls.includes(control.controlId));
  return { decision: blockers.length ? "BLOCKED" : "READY_FOR_PILOT", assessedAt: input.assessedAt, scoreBps, domainResults, blockers, evidenceIds: input.evidence.filter(({ controlId }) => passedControls.includes(controlId)).map(({ evidenceId }) => evidenceId), externallyCertified, pilotMayStart: blockers.length === 0 && externallyCertified };
}

const evidence = (controlId: string, kind: string, source: ReadinessEvidence["source"] = "INTERNAL"): ReadinessEvidence => ({ evidenceId: `EVD-${controlId}-${kind}`, controlId, kind, status: "PASS", source, issuedAt: "2026-08-27T12:00:00Z", expiresAt: "2027-08-27T12:00:00Z", contentHash: `sha256:${controlId}-${kind}`, makerActorId: "readiness-maker", checkerActorId: "readiness-checker" });
export const readinessEvidence: readonly ReadinessEvidence[] = [evidence("SEC-SECRETS", "rotation-test"), evidence("PRI-RETENTION", "rights-exercise"), evidence("PRI-RETENTION", "deletion-verification"), evidence("RES-RESTORE", "exercise-result"), evidence("OPS-RUNBOOKS", "runbook-catalogue"), evidence("OPS-SUPPORT", "handoff-rehearsal")];
export const recoveryExercises: readonly RecoveryExercise[] = [{ exerciseId: "EX-RESTORE-001", capability: "Ledger and safeguarding projections", status: "PASS", exercisedAt: "2026-08-27T13:00:00Z", recoveryTimeSeconds: 1200, recoveryPointSeconds: 60, rtoSeconds: 1800, rpoSeconds: 300, projectionRebuildVerified: true, evidenceIds: ["EVD-RESTORE-001"] }];
export const operationalRunbooks: readonly Runbook[] = ["PRICING", "LEDGER", "PAYMENTS", "IDENTITY", "COMMUNICATIONS"].map((capability) => ({ runbookId: `RB-${capability}`, capability, owner: `${capability} Operations`, version: "1.0.0", approved: true, lastRehearsedAt: "2026-08-27T14:00:00Z", escalationRoute: ["On-call", "Incident Commander"], rollbackSteps: ["Stop new activity", "Restore last verified configuration"], verificationSteps: ["Verify health", "Reconcile evidence"] }));
export const supportReadiness: SupportReadiness = { rotaId: "ROTA-PILOT-001", coverage: "BUSINESS_HOURS", primaryOwner: "operations-primary", secondaryOwner: "operations-secondary", incidentCommander: "incident-commander", customerCommunicationOwner: "customer-operations", severityResponseMinutes: { SEV1: 15, SEV2: 60, SEV3: 240 }, handoffRehearsed: true, evidenceId: "EVD-HANDOFF-001" };
export const productionReadinessAssessment = evaluateProductionReadiness({ controls: productionReadinessControls, evidence: readinessEvidence, exercises: recoveryExercises, runbooks: operationalRunbooks, support: supportReadiness, assessedAt: "2026-08-27T15:00:00Z" });
