import { describe, expect, it } from "vitest";
import { authorizePaymentEnvironment, createDeadLetter, normalizeBankObservation, normalizeCardProgrammeEvent, reconcileExternalInstruction, type BankObservation, type CardProgrammeEvent } from "./index";

const blockedGate = { decision: "BLOCKED" as const, evaluatedAt: "2026-08-27T00:00:00Z", passedControlIds: [], blockers: ["approvals open"], productionCredentialsMayBeProvisioned: false, auditEvidenceIds: [] };
const readyGate = { ...blockedGate, decision: "READY" as const, blockers: [], productionCredentialsMayBeProvisioned: true };
const card: CardProgrammeEvent = { eventId: "EV-CARD-1", eventType: "CLEARING", providerId: "card-sandbox", environment: "SANDBOX", organisationId: "ORG-1", legalEntityId: "FC-UK", cardToken: "card_tok_1", providerReference: "PRESENT-1", amountMinor: 6800, currency: "GBP", occurredAt: "2026-08-27T12:00:00Z", signatureVerified: true, payloadHash: "sha256:card-1" };
const bank: BankObservation = { observationId: "EV-BANK-1", providerId: "bank-sandbox", environment: "SANDBOX", organisationId: "ORG-1", legalEntityId: "FC-UK", accountToken: "bank_tok_1", providerReference: "BANK-1", direction: "CREDIT", amountMinor: 6800, currency: "GBP", bookedAt: "2026-08-27T12:01:00Z", signatureVerified: true, payloadHash: "sha256:bank-1" };

describe("card programme and banking adapters", () => {
  it("normalizes sandbox card events without ledger authority", () => expect(normalizeCardProgrammeEvent(card, blockedGate)).toMatchObject({ source: "CARD_PROGRAMME", type: "CLEARING", canPostLedger: false, requiresLedgerIdempotency: true, immutable: true }));
  it("normalizes sandbox bank observations without ledger authority", () => expect(normalizeBankObservation(bank, blockedGate)).toMatchObject({ source: "BANK", type: "BANK_CREDIT", canPostLedger: false }));
  it("blocks production adapters while P6-001 is blocked", () => { expect(() => normalizeCardProgrammeEvent({ ...card, environment: "PRODUCTION" }, blockedGate)).toThrow(/P6-001/); expect(() => normalizeBankObservation({ ...bank, environment: "PRODUCTION" }, blockedGate)).toThrow(/P6-001/); });
  it("permits the production boundary only after the launch gate passes", () => expect(() => authorizePaymentEnvironment("PRODUCTION", readyGate)).not.toThrow());
  it("rejects duplicate external events", () => { expect(() => normalizeCardProgrammeEvent(card, blockedGate, new Set([card.eventId]))).toThrow(/Duplicate/); expect(() => normalizeBankObservation(bank, blockedGate, new Set([bank.observationId]))).toThrow(/Duplicate/); });
  it("requires signed, content-addressed evidence", () => { expect(() => normalizeCardProgrammeEvent({ ...card, signatureVerified: false }, blockedGate)).toThrow(/Authenticated/); expect(() => normalizeBankObservation({ ...bank, payloadHash: "raw" }, blockedGate)).toThrow(/content-addressed/); });
  it("prohibits PAN and bank account details in adapter contracts", () => { expect(() => normalizeCardProgrammeEvent({ ...card, cardToken: "4242424242424242" }, blockedGate)).toThrow(/PAN/); expect(() => normalizeBankObservation({ ...bank, accountToken: "12-34-56 12345678" }, blockedGate)).toThrow(/account details/); });
  it("requires positive safe-integer minor units", () => { expect(() => normalizeCardProgrammeEvent({ ...card, amountMinor: 0 }, blockedGate)).toThrow(/minor units/); expect(() => normalizeBankObservation({ ...bank, amountMinor: 1.5 }, blockedGate)).toThrow(/minor units/); });
  it("matches external instructions to tenant-scoped internal records", () => { const instruction = normalizeBankObservation(bank, blockedGate); expect(reconcileExternalInstruction(instruction, { organisationId: "ORG-1", legalEntityId: "FC-UK", amountMinor: 6800, currency: "GBP", internalReference: "JRN-1" })).toMatchObject({ status: "MATCHED", differenceMinor: 0 }); });
  it("opens deterministic scope, currency and amount breaks", () => { const instruction = normalizeBankObservation(bank, blockedGate); expect(reconcileExternalInstruction(instruction, { organisationId: "ORG-2", legalEntityId: "FC-UK", amountMinor: 6800, currency: "GBP", internalReference: "JRN-1" }).reason).toBe("SCOPE_MISMATCH"); expect(reconcileExternalInstruction(instruction, { organisationId: "ORG-1", legalEntityId: "FC-UK", amountMinor: 6800, currency: "USD", internalReference: "JRN-1" }).reason).toBe("CURRENCY_MISMATCH"); expect(reconcileExternalInstruction(instruction, { organisationId: "ORG-1", legalEntityId: "FC-UK", amountMinor: 6700, currency: "GBP", internalReference: "JRN-1" })).toMatchObject({ reason: "AMOUNT_MISMATCH", differenceMinor: 100 }); });
  it("creates owned retryable dead letters without clearing breaks", () => expect(createDeadLetter("EV-1", "Provider timeout", "sha256:event")).toEqual({ deadLetterId: "payments-dlq:EV-1", sourceEventId: "EV-1", reason: "Provider timeout", ownerRole: "DATA_INTEGRATIONS", retryable: true, evidenceHash: "sha256:event" }));
});
