import { describe, expect, it } from "vitest";
import { cancelRemainingProtection, createSettlementState, settlePurchase, type SettlementCommand } from "./index";

const allocation = { allocationId: "ALLOC-1", purchaseId: "PURCHASE-1", clearingId: "CLEAR-1", customerId: "CUSTOMER-1", walletId: "WALLET-1", organisationId: "ORG-1", currency: "USD", confirmedFuelQuantity4dp: 200_000, unprotectedQuantity4dp: 0, nonFuelAmountMinor: 0, actualPumpObservationId: "PUMP-1", provenance: "SIMULATED", correlationId: "CORR-1", lines: [{ protectionTransactionId: "PROTECT-1", allocatedQuantity4dp: 200_000, protectionChargeMinor: 0, quoteId: "QUOTE-1", spreadDecisionVersion: "spread@1", rulesVersion: "rules@1" }] } as const;
const base: SettlementCommand = { commandId: "CMD-1", idempotencyKey: "settle:1", settlementId: "SETTLE-1", allocation, terms: [{ protectionTransactionId: "PROTECT-1", referencePrice4dp: 35_000, strikePrice4dp: 36_750, maximumBoundaryPrice4dp: 40_250 }], actualPumpPrice4dp: 39_000, accounts: { customerReservedAccountId: "reserved", customerAvailableAccountId: "available", protectionClaimAccountId: "claim", stationPayableAccountId: "station" }, legalEntityId: "FC-US", market: "US-TX", actorId: "settlement-engine", settledAt: "2026-08-27T10:00:00.000Z" };
const balanced = (lines: readonly { side: "DEBIT" | "CREDIT"; amountMinor: number }[]) => lines.filter((line) => line.side === "DEBIT").reduce((n, line) => n + line.amountMinor, 0) === lines.filter((line) => line.side === "CREDIT").reduce((n, line) => n + line.amountMinor, 0);

describe("settlement engine", () => {
  it("reproduces the canonical in-boundary rise", () => { const decision = settlePurchase(createSettlementState(), base).decision; expect(decision).toMatchObject({ stationPaymentMinor: 7_800, customerDebitMinor: 7_350, poolContributionMinor: 450, aboveBoundaryCustomerMinor: 0, lowerPriceReleaseMinor: 0 }); });
  it("caps the canonical boundary breach and exposes customer excess", () => { const decision = settlePurchase(createSettlementState(), { ...base, actualPumpPrice4dp: 42_000 }).decision; expect(decision).toMatchObject({ stationPaymentMinor: 8_400, customerDebitMinor: 7_700, poolContributionMinor: 700, aboveBoundaryCustomerMinor: 350, availableDebitMinor: 350 }); });
  it("passes through the canonical lower pump price and releases unused reserved value", () => { const decision = settlePurchase(createSettlementState(), { ...base, actualPumpPrice4dp: 34_000 }).decision; expect(decision).toMatchObject({ stationPaymentMinor: 6_800, customerDebitMinor: 6_800, poolContributionMinor: 0, lowerPriceReleaseMinor: 550, reservedDebitMinor: 7_350 }); });
  it("settles unprotected overflow entirely at pump price", () => { const input = { ...base, allocation: { ...allocation, confirmedFuelQuantity4dp: 250_000, unprotectedQuantity4dp: 50_000 } }; const decision = settlePurchase(createSettlementState(), input).decision; expect(decision).toMatchObject({ stationPaymentMinor: 9_750, customerDebitMinor: 9_300, poolContributionMinor: 450, availableDebitMinor: 1_950 }); });
  it("applies each protection slice under its own pinned terms", () => { const input: SettlementCommand = { ...base, allocation: { ...allocation, lines: [{ ...allocation.lines[0], allocatedQuantity4dp: 100_000 }, { ...allocation.lines[0], protectionTransactionId: "PROTECT-2", allocatedQuantity4dp: 100_000, quoteId: "QUOTE-2" }] }, terms: [...base.terms, { protectionTransactionId: "PROTECT-2", referencePrice4dp: 36_000, strikePrice4dp: 37_800, maximumBoundaryPrice4dp: 41_400 }] }; const decision = settlePurchase(createSettlementState(), input).decision; expect(decision.slices.map(({ customerExactNumerator }) => customerExactNumerator)).toEqual([3_675_000_000, 3_780_000_000]); });
  it("emits balanced ledger and position instructions with lineage", () => { const decision = settlePurchase(createSettlementState(), base).decision; expect(balanced(decision.postingInstruction.lines)).toBe(true); expect(decision.postingInstruction).toMatchObject({ eventType: "FUEL_PURCHASE_SETTLED", sourceContractId: "ALLOC-1", correlationId: "CORR-1", provenance: "SIMULATED" }); expect(decision.postingInstruction.positionRedemptions).toEqual([{ protectionTransactionId: "PROTECT-1", quantity4dp: 200_000 }]); });
  it("does not include non-fuel spend in fuel settlement", () => { const decision = settlePurchase(createSettlementState(), { ...base, allocation: { ...allocation, nonFuelAmountMinor: 999 } }).decision; expect(decision.stationPaymentMinor).toBe(7_800); });
  it("replays an identical command without a second decision", () => { const first = settlePurchase(createSettlementState(), base); const replay = settlePurchase(first.state, base); expect(replay.idempotentReplay).toBe(true); expect(replay.state.decisions).toHaveLength(1); });
  it("rejects changed facts under the same idempotency key", () => { const first = settlePurchase(createSettlementState(), base); expect(() => settlePurchase(first.state, { ...base, actualPumpPrice4dp: 39_001 })).toThrow(/different command/i); });
  it("rejects missing terms and quantity disagreement", () => { expect(() => settlePurchase(createSettlementState(), { ...base, terms: [] })).toThrow(/pinned settlement terms/i); expect(() => settlePurchase(createSettlementState(), { ...base, allocation: { ...allocation, confirmedFuelQuantity4dp: 199_999 } })).toThrow(/equal confirmed/i); });
});

describe("unused-protection cancellation", () => {
  const cancellation = { cancellationId: "CANCEL-1", idempotencyKey: "cancel:1", protectionTransactionId: "PROTECT-1", remainingQuantity4dp: 50_000, strikePrice4dp: 36_750, currency: "USD" as const, customerReservedAccountId: "reserved", customerAvailableAccountId: "available", canceledAt: "2026-08-27T11:00:00.000Z" };
  it("reproduces the customer-favourable $18.38 canonical release", () => expect(cancelRemainingProtection(cancellation)).toMatchObject({ exactReleaseNumerator: 1_837_500_000, customerCreditMinor: 1_838, absorbedResidualNumerator: 500_000, protectionChargeRefundMinor: 0 }));
  it("moves released value from reserved to available with balanced lines", () => { const decision = cancelRemainingProtection(cancellation); expect(balanced(decision.postingLines)).toBe(true); expect(decision.postingLines).toEqual([{ lineId: "CANCEL-1:RESERVED", accountId: "reserved", side: "DEBIT", amountMinor: 1_838 }, { lineId: "CANCEL-1:AVAILABLE", accountId: "available", side: "CREDIT", amountMinor: 1_838 }]); });
});
