import { describe, expect, it } from "vitest";
import type { RuleDecision } from "@fuelcap/rules-engine";
import { approveRiskHold, proposeRiskHold, recordRiskDecision, scoreRiskSignals, validateFairnessSnapshot, type RiskSignal } from "./index";

const signals: readonly RiskSignal[] = [{ signalId: "SIG-V", organisationId: "ORG-1", subjectId: "CUS-1", type: "VELOCITY", scoreBps: 8200, confidenceBps: 9300, modelVersion: "velocity@2", reasonCode: "VELOCITY_CLUSTER", evidenceIds: ["EVD-V"], observedAt: "2026-08-27T10:00:00Z", simulated: true }, { signalId: "SIG-L", organisationId: "ORG-1", subjectId: "CUS-1", type: "LOCATION_IMPOSSIBILITY", scoreBps: 7000, confidenceBps: 8800, modelVersion: "location@3", reasonCode: "LOCATION_INCONSISTENT", evidenceIds: ["EVD-L"], observedAt: "2026-08-27T10:01:00Z", simulated: true }];
const score = () => scoreRiskSignals(signals, { VELOCITY: 2, LOCATION_IMPOSSIBILITY: 1 }, "risk-score@1");
const rule = (outcome = "TEMPORARY_HOLD"): RuleDecision => ({ decisionId: "RULE-DEC-1", engineVersion: "rules-engine@1.0.0", ruleSetId: "RISK-RULES", ruleSetVersion: "risk-rules@4", ruleId: "HIGH-RISK", ruleVersion: "4.1", factsVersion: "risk-facts@1", outcome, matchedConditions: ["risk.scoreBps GTE 7500"], failedConditions: [], reasonCodes: ["HUMAN_REVIEW_REQUIRED"], calculatedValues: {}, followUpActions: ["OPEN_CASE"], explanationTemplate: "risk-review-v2", evidenceReferences: ["RULE-EVD-1"], evaluatedAt: "2026-08-27T10:02:00Z" });
const decision = () => recordRiskDecision({ decisionId: "RISK-DEC-1", score: score(), ruleDecision: rule(), capability: "AUTO_ROLLOVER", scopeReference: "PROTECTION-1", startsAt: "2026-08-27T10:02:00Z", expiresAt: "2026-08-29T10:02:00Z", reviewRoute: "Human review and appeal" });

describe("fraud and anti-selection decisioning", () => {
  it("scores typed signals deterministically with pinned model lineage", () => expect(score()).toMatchObject({ scoreBps: 7800, confidenceBps: 8800, modelVersion: "risk-score@1", signalIds: ["SIG-V", "SIG-L"] }));
  it("rejects cross-tenant signal aggregation", () => expect(() => scoreRiskSignals([...signals, { ...signals[0]!, signalId: "OTHER", organisationId: "ORG-2" }], {}, "risk@1")).toThrow(/Cross-tenant/));
  it("records the Rules Engine as decision authority", () => expect(decision()).toMatchObject({ outcome: "TEMPORARY_HOLD", ruleDecisionId: "RULE-DEC-1", ruleSetVersion: "risk-rules@4", generativeAiAuthority: false }));
  it("applies the minimum named capability and scope", () => expect(decision()).toMatchObject({ capability: "AUTO_ROLLOVER", scopeReference: "PROTECTION-1", customerValueErasedMinor: 0 }));
  it("rejects vague restrictive outcomes without scope", () => expect(() => recordRiskDecision({ decisionId: "D", score: score(), ruleDecision: rule("RESTRICT_WITHDRAWAL"), capability: null, scopeReference: null, startsAt: "2026-08-27", expiresAt: "2026-08-28", reviewRoute: "Appeal" })).toThrow(/exact capability/));
  it("requires expiry for holds and prolonged restrictions", () => expect(() => recordRiskDecision({ decisionId: "D", score: score(), ruleDecision: rule(), capability: "TRANSACTION", scopeReference: "TX-1", startsAt: "2026-08-27", expiresAt: null, reviewRoute: "Appeal" })).toThrow(/expiry/));
  it("preserves combined signal and rule evidence with review route", () => expect(decision()).toMatchObject({ reasonCodes: ["VELOCITY_CLUSTER", "LOCATION_INCONSISTENT", "HUMAN_REVIEW_REQUIRED"], evidenceIds: ["EVD-V", "EVD-L", "RULE-EVD-1"], reviewRoute: "Human review and appeal" }));
  it("creates explicit holds without erasing customer value", () => expect(proposeRiskHold(decision(), { holdId: "HOLD-1", amountMinor: 0, releaseRule: "Release after cleared review or expiry", makerId: "cf-maker" })).toMatchObject({ state: "PROPOSED", capability: "AUTO_ROLLOVER", customerValueErasedMinor: 0 }));
  it("requires different-checker step-up approval", () => { const hold = proposeRiskHold(decision(), { holdId: "HOLD-1", amountMinor: 0, releaseRule: "Review", makerId: "cf-maker" }); expect(approveRiskHold(hold, { checkerId: "cf-checker", stepUp: true, evidenceIds: ["CASE-EVD"] }).state).toBe("APPROVED"); expect(() => approveRiskHold(hold, { checkerId: "cf-maker", stepUp: true, evidenceIds: ["EVD"] })).toThrow(/Different-checker/); });
  it("rejects unsupported vague Rules Engine outcomes", () => expect(() => recordRiskDecision({ decisionId: "D", score: score(), ruleDecision: rule("ACCOUNT_BLOCKED"), capability: null, scopeReference: null, startsAt: "2026-08-27", expiresAt: null, reviewRoute: "Appeal" })).toThrow(/unsupported/));
  it("validates fairness without protected attributes or failed proxy tests", () => { const snapshot = { snapshotId: "FAIR-1", market: "CA-ON", segment: "PERSONAL", modelVersion: "risk@1", falsePositiveRateBps: 320, medianReviewMinutes: 46, lossAvoidedMinor: 10000, customerImpactCount: 18, protectedAttributesUsed: false as const, proxyTestStatus: "PASS" as const, sampledAt: "2026-08-27" }; expect(validateFairnessSnapshot(snapshot)).toBe("PASS"); expect(() => validateFairnessSnapshot({ ...snapshot, proxyTestStatus: "FAIL" })).toThrow(/proxy/); });
});
