import { describe, expect, it } from "vitest";
import { authoriseEnterpriseApi, publishBrandConfiguration, seededApiCredential, seededBrandDraft, seededPublishedBrand, seededWebhookSubscription, simulateWebhookDelivery, validateBrandConfiguration } from "./index";

describe("P7-004 enterprise platform", () => {
  it("validates a complete tenant brand", () => expect(validateBrandConfiguration(seededBrandDraft)).toEqual([]));
  it("rejects invalid colours, assets and insecure URLs", () => expect(validateBrandConfiguration({ ...seededBrandDraft, primaryColour: "red" as `#${string}`, logoAssetReference: "https://logo.invalid", supportUrl: "http://support.invalid" })).toEqual(expect.arrayContaining(["PRIMARY_COLOUR_INVALID", "LOGO_REFERENCE_INVALID", "HTTPS_URL_REQUIRED"])));
  it("publishes only through segregated approval", () => { expect(seededPublishedBrand).toMatchObject({ state: "PUBLISHED", liveCustomerSurface: false }); expect(() => publishBrandConfiguration(seededBrandDraft, { makerId: "same", checkerId: "same", assurance: "STEP_UP" })).toThrow(/different-checker/); });
  it("allows an exact tenant and scope", () => expect(authoriseEnterpriseApi({ credential: seededApiCredential, requestOrganisationId: "org-northstar-logistics", requiredScope: "reports:read", now: "2026-08-28T10:00:00Z" })).toMatchObject({ allowed: true, status: 200, reasonCode: "ALLOWED" }));
  it("denies cross-tenant access", () => expect(authoriseEnterpriseApi({ credential: seededApiCredential, requestOrganisationId: "org-other", requiredScope: "reports:read", now: "2026-08-28T10:00:00Z" })).toMatchObject({ allowed: false, reasonCode: "TENANT_MISMATCH" }));
  it("denies absent scopes", () => expect(authoriseEnterpriseApi({ credential: seededApiCredential, requestOrganisationId: "org-northstar-logistics", requiredScope: "transactions:read", now: "2026-08-28T10:00:00Z" })).toMatchObject({ allowed: false, reasonCode: "SCOPE_DENIED" }));
  it("denies expired and revoked credentials", () => { expect(authoriseEnterpriseApi({ credential: seededApiCredential, requestOrganisationId: "org-northstar-logistics", requiredScope: "reports:read", now: seededApiCredential.expiresAt }).reasonCode).toBe("CREDENTIAL_EXPIRED"); expect(authoriseEnterpriseApi({ credential: { ...seededApiCredential, state: "REVOKED" }, requestOrganisationId: "org-northstar-logistics", requiredScope: "reports:read", now: "2026-08-28T10:00:00Z" }).reasonCode).toBe("CREDENTIAL_INACTIVE"); });
  it("simulates no-network webhook delivery and suppresses replay", () => { const seen = new Set<string>(); const input = { deliveryId: "DELIVERY-1", organisationId: "org-northstar-logistics", event: "fleet.updated" as const, payloadDigest: "sha256:bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb" as const, idempotencyKey: "evt-1", attemptedAt: "2026-08-28T10:00:00Z" }; expect(simulateWebhookDelivery(seededWebhookSubscription, input, seen)).toMatchObject({ status: "SIMULATED", networkRequestMade: false }); expect(simulateWebhookDelivery(seededWebhookSubscription, input, seen)).toMatchObject({ status: "DUPLICATE_SUPPRESSED", networkRequestMade: false }); });
  it("blocks inactive subscriptions and mismatched tenants", () => { const seen = new Set<string>(); const input = { deliveryId: "DELIVERY-2", organisationId: "org-other", event: "fleet.updated" as const, payloadDigest: "sha256:cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc" as const, idempotencyKey: "evt-2", attemptedAt: "2026-08-28T10:00:00Z" }; expect(simulateWebhookDelivery(seededWebhookSubscription, input, seen)).toMatchObject({ status: "BLOCKED", networkRequestMade: false }); });
  it("never exposes credential or signing secret values", () => { expect(seededApiCredential).toMatchObject({ secretDisplayed: false, sandboxOnly: true }); expect(seededWebhookSubscription).toMatchObject({ signingSecretDisplayed: false, outboundDeliveryEnabled: false }); });
});
