import { describe, expect, it } from "vitest";
import { clearBreak, createReconciliationState, isActionBlocked, runReconciliation, type ReconciliationInput } from "./index";
const base: ReconciliationInput = { runId: "RUN-1", idempotencyKey: "reconcile:1", legalEntityId: "FC-US", currency: "USD", safeguardedCashMinor: 10_000, customerAvailableMinor: 6_000, customerReservedMinor: 3_000, refundPayableMinor: 1_000, ledgerIntegrityValid: true, inFlightItems: [], externalMatches: [], observedAt: "2026-08-27T12:00:00.000Z" };
describe("safeguarding reconciliation", () => {
  it("passes only when cash, liabilities and identified in-flight items reconcile", () => expect(runReconciliation(createReconciliationState(), base).report).toMatchObject({ status: "PASS", differenceMinor: 0, customerLiabilitiesMinor: 10_000 }));
  it("uses explicitly identified in-flight adjustments", () => expect(runReconciliation(createReconciliationState(), { ...base, safeguardedCashMinor: 9_500, inFlightItems: [{ itemId: "IF-1", type: "PROCESSOR", amountMinor: 500, externalReference: "pi_1", identified: true }] }).report.status).toBe("PASS"));
  it("opens a blocking break for safeguarding mismatch", () => { const result = runReconciliation(createReconciliationState(), { ...base, safeguardedCashMinor: 9_999 }); expect(result.report.status).toBe("BREAK"); expect(result.state.breaks[0]).toMatchObject({ reason: "SAFEGUARDING_MISMATCH", differenceMinor: -1 }); expect(isActionBlocked(result.state, "WITHDRAWALS")).toBe(true); });
  it("does not use unidentified items as a balancing plug", () => { const result = runReconciliation(createReconciliationState(), { ...base, safeguardedCashMinor: 9_500, inFlightItems: [{ itemId: "IF-X", type: "BANK", amountMinor: 500, externalReference: "bank-x", identified: false }] }); expect(result.report.differenceMinor).toBe(-500); expect(result.state.breaks.map((b) => b.reason)).toEqual(["SAFEGUARDING_MISMATCH", "UNIDENTIFIED_IN_FLIGHT_ITEM"]); });
  it("breaks on ledger integrity and missing or mismatched external observations", () => { const result = runReconciliation(createReconciliationState(), { ...base, ledgerIntegrityValid: false, externalMatches: [{ matchId: "M1", source: "STRIPE", internalReference: "PAY-1", externalReference: null, internalAmountMinor: 100, externalAmountMinor: null }, { matchId: "M2", source: "BANK", internalReference: "BANK-1", externalReference: "EXT-1", internalAmountMinor: 100, externalAmountMinor: 99 }] }); expect(result.state.breaks.map((b) => b.reason)).toEqual(["LEDGER_INTEGRITY_FAILED", "EXTERNAL_ITEM_MISSING", "EXTERNAL_AMOUNT_MISMATCH"]); });
  it("replays identical runs idempotently and rejects changed evidence", () => { const first = runReconciliation(createReconciliationState(), base); expect(runReconciliation(first.state, base).idempotentReplay).toBe(true); expect(() => runReconciliation(first.state, { ...base, safeguardedCashMinor: 9_999 })).toThrow(/different evidence/i); });
  it("requires maker-checker, evidence, step-up and a passing corrected run", () => { const broken = runReconciliation(createReconciliationState(), { ...base, safeguardedCashMinor: 9_999 }); const pass = runReconciliation(broken.state, { ...base, runId: "RUN-2", idempotencyKey: "reconcile:2" }); const command = { breakId: "RUN-1:BREAK:1", makerId: "maker", checkerId: "checker", evidence: "Bank statement matched", stepUpVerified: true, breakGlass: false, correctedRunId: "RUN-2", clearedAt: "2026-08-27T12:05:00.000Z" }; expect(clearBreak(pass.state, command).breaks[0]?.status).toBe("CLEARED"); expect(() => clearBreak(pass.state, { ...command, checkerId: "maker" })).toThrow(/different maker/i); });
  it("forbids break-glass clearance", () => { const broken = runReconciliation(createReconciliationState(), { ...base, safeguardedCashMinor: 9_999 }); const pass = runReconciliation(broken.state, { ...base, runId: "RUN-2", idempotencyKey: "reconcile:2" }); expect(() => clearBreak(pass.state, { breakId: "RUN-1:BREAK:1", makerId: "m", checkerId: "c", evidence: "e", stepUpVerified: true, breakGlass: true, correctedRunId: "RUN-2", clearedAt: "2026-08-27T12:05:00.000Z" })).toThrow(/Break-glass/i); });
});
