export const TREASURY_VERSION = "treasury-risk-transfer@0.1.0" as const;
export type TreasuryCashFlow = Readonly<{ flowId:string; legalEntityId:string; currency:"USD"|"GBP"|"EUR"; day:number; category:"PREMIUM"|"CLAIM"|"HEDGE"|"OPERATING"|"CAPITAL"; amountMinor:number; direction:"IN"|"OUT"; evidenceIds:readonly string[]; customerSafeguarded:false; simulated:true }>;
export type LiquidityPolicy = Readonly<{ policyId:string; minimumClosingMinor:number; minimumCoverageBps:number; maximumSingleDayOutflowMinor:number }>;
export type LiquidityDay = Readonly<{ day:number; inflowMinor:number; outflowMinor:number; closingMinor:number; coverageBps:number; status:"ADEQUATE"|"WATCH"|"BREACH" }>;
export type LiquidityForecast = Readonly<{ forecastId:string; version:typeof TREASURY_VERSION; legalEntityId:string; currency:"USD"|"GBP"|"EUR"; openingMinor:number; expectedClaimsMinor:number; days:readonly LiquidityDay[]; status:"ADEQUATE"|"WATCH"|"BREACH"; evidenceIds:readonly string[]; simulated:true; customerMoneyIncluded:false }>;
export type TreasuryTransfer = Readonly<{ transferId:string; forecastId:string; amountMinor:number; sourceAccountReference:string; destinationAccountReference:string; makerId:string; checkerId:string|null; state:"PROPOSED"|"APPROVED"; evidenceDigest:`sha256:${string}`; executionEligible:false; moneyMovement:false }>;
export type RiskTransferProgramme = Readonly<{ programmeId:string; legalEntityId:string; currency:"USD"|"GBP"|"EUR"; type:"QUOTA_SHARE"|"EXCESS_OF_LOSS"; attachmentMinor:number; limitMinor:number; cededShareBps:number; collateralMinor:number; counterparty:string; counterpartyConcentrationBps:number; dueDiligenceState:"PENDING"|"APPROVED"; wordingState:"DRAFT"|"APPROVED"; makerId:string; checkerId:string|null; state:"DRAFT"|"APPROVED"; simulated:true; bindingAuthority:false }>;
export type RecoveryProjection = Readonly<{ programmeId:string; grossLossMinor:number; recoveryMinor:number; retainedLossMinor:number; collateralCoverageBps:number; status:"ELIGIBLE"|"BLOCKED"; reasonCodes:readonly string[]; simulated:true }>;

const digest=/^sha256:[a-f0-9]{64}$/; const ref=/^(ledger|account):\/[a-z0-9/_-]+$/;
export function forecastLiquidity(input:Readonly<{forecastId:string;legalEntityId:string;currency:"USD"|"GBP"|"EUR";openingMinor:number;expectedClaimsMinor:number;horizonDays:number;flows:readonly TreasuryCashFlow[];policy:LiquidityPolicy}>):LiquidityForecast{
 if(!input.forecastId.trim()||!input.legalEntityId.trim()||!Number.isSafeInteger(input.openingMinor)||input.openingMinor<0||!Number.isSafeInteger(input.expectedClaimsMinor)||input.expectedClaimsMinor<=0||!Number.isInteger(input.horizonDays)||input.horizonDays<1||input.horizonDays>90)throw new Error("Valid forecast identity, balances and horizon are required.");
 if(input.flows.some(f=>f.legalEntityId!==input.legalEntityId||f.currency!==input.currency||f.customerSafeguarded||!f.simulated||!Number.isSafeInteger(f.amountMinor)||f.amountMinor<=0||f.day<1||f.day>input.horizonDays||!f.evidenceIds.length))throw new Error("Tenant-matched simulated non-customer cash flows are required.");
 let closing=input.openingMinor;const days:LiquidityDay[]=[];for(let day=1;day<=input.horizonDays;day++){const current=input.flows.filter(f=>f.day===day);const inflow=current.filter(f=>f.direction==="IN").reduce((s,f)=>s+f.amountMinor,0);const outflow=current.filter(f=>f.direction==="OUT").reduce((s,f)=>s+f.amountMinor,0);closing+=inflow-outflow;const coverage=Math.round(Math.max(0,closing)*10_000/input.expectedClaimsMinor);const status=closing<input.policy.minimumClosingMinor||coverage<input.policy.minimumCoverageBps||outflow>input.policy.maximumSingleDayOutflowMinor?"BREACH":coverage<input.policy.minimumCoverageBps+2000?"WATCH":"ADEQUATE";days.push({day,inflowMinor:inflow,outflowMinor:outflow,closingMinor:closing,coverageBps:coverage,status});}
 const status=days.some(d=>d.status==="BREACH")?"BREACH":days.some(d=>d.status==="WATCH")?"WATCH":"ADEQUATE";return{forecastId:input.forecastId,version:TREASURY_VERSION,legalEntityId:input.legalEntityId,currency:input.currency,openingMinor:input.openingMinor,expectedClaimsMinor:input.expectedClaimsMinor,days,status,evidenceIds:[...new Set(input.flows.flatMap(f=>f.evidenceIds))],simulated:true,customerMoneyIncluded:false};
}
export function proposeTreasuryTransfer(forecast:LiquidityForecast,input:Readonly<{transferId:string;amountMinor:number;sourceAccountReference:string;destinationAccountReference:string;makerId:string;evidenceDigest:`sha256:${string}`}>):TreasuryTransfer{if(forecast.status!=="BREACH"||!input.transferId.trim()||!Number.isSafeInteger(input.amountMinor)||input.amountMinor<=0||!ref.test(input.sourceAccountReference)||!ref.test(input.destinationAccountReference)||input.sourceAccountReference===input.destinationAccountReference||!input.makerId.trim()||!digest.test(input.evidenceDigest))throw new Error("A breached forecast and valid segregated transfer proposal are required.");return{...input,forecastId:forecast.forecastId,checkerId:null,state:"PROPOSED",executionEligible:false,moneyMovement:false};}
export function approveTreasuryTransfer(transfer:TreasuryTransfer,input:Readonly<{checkerId:string;assurance:"STEP_UP"}>):TreasuryTransfer{if(transfer.state!=="PROPOSED"||!input.checkerId.trim()||input.checkerId===transfer.makerId||input.assurance!=="STEP_UP")throw new Error("Different-checker step-up approval is required.");return{...transfer,checkerId:input.checkerId,state:"APPROVED",executionEligible:false,moneyMovement:false};}
export function projectRiskTransfer(programme:RiskTransferProgramme,grossLossMinor:number,policy:Readonly<{minimumCollateralCoverageBps:number;maximumCounterpartyConcentrationBps:number}>):RecoveryProjection{const reasons:string[]=[];if(programme.state!=="APPROVED"||programme.dueDiligenceState!=="APPROVED"||programme.wordingState!=="APPROVED"||programme.bindingAuthority)reasons.push("PROGRAMME_NOT_APPROVED");if(programme.counterpartyConcentrationBps>policy.maximumCounterpartyConcentrationBps)reasons.push("CONCENTRATION_EXCEEDED");const layerLoss=Math.min(programme.limitMinor,Math.max(0,grossLossMinor-programme.attachmentMinor));const recovery=Math.round(layerLoss*programme.cededShareBps/10_000);const collateralCoverage=recovery===0?10_000:Math.round(programme.collateralMinor*10_000/recovery);if(collateralCoverage<policy.minimumCollateralCoverageBps)reasons.push("COLLATERAL_INSUFFICIENT");return{programmeId:programme.programmeId,grossLossMinor,recoveryMinor:reasons.length?0:recovery,retainedLossMinor:grossLossMinor-(reasons.length?0:recovery),collateralCoverageBps:collateralCoverage,status:reasons.length?"BLOCKED":"ELIGIBLE",reasonCodes:reasons,simulated:true};}
export function approveRiskTransferProgramme(programme:RiskTransferProgramme,input:Readonly<{checkerId:string;assurance:"STEP_UP"}>):RiskTransferProgramme{if(programme.state!=="DRAFT"||programme.dueDiligenceState!=="APPROVED"||programme.wordingState!=="APPROVED"||programme.bindingAuthority||!input.checkerId.trim()||input.checkerId===programme.makerId||input.assurance!=="STEP_UP")throw new Error("Approved diligence, wording and different-checker step-up are required.");return{...programme,checkerId:input.checkerId,state:"APPROVED",bindingAuthority:false};}
export const seededLiquidityPolicy:LiquidityPolicy={policyId:"LIQ-POLICY-1",minimumClosingMinor:100_000,minimumCoverageBps:12_000,maximumSingleDayOutflowMinor:240_000};
export const seededTreasuryFlows:readonly TreasuryCashFlow[]=[{flowId:"FLOW-1",legalEntityId:"fuelcap-us",currency:"USD",day:1,category:"PREMIUM",amountMinor:80_000,direction:"IN",evidenceIds:["LEDGER-0842"],customerSafeguarded:false,simulated:true},{flowId:"FLOW-2",legalEntityId:"fuelcap-us",currency:"USD",day:2,category:"CLAIM",amountMinor:290_000,direction:"OUT",evidenceIds:["STRESS-BREACH"],customerSafeguarded:false,simulated:true},{flowId:"FLOW-3",legalEntityId:"fuelcap-us",currency:"USD",day:3,category:"HEDGE",amountMinor:90_000,direction:"IN",evidenceIds:["HEDGE-PLAN-TX-1"],customerSafeguarded:false,simulated:true}];
export const seededLiquidityForecast=forecastLiquidity({forecastId:"LIQ-US-7D-1",legalEntityId:"fuelcap-us",currency:"USD",openingMinor:330_000,expectedClaimsMinor:150_000,horizonDays:7,flows:seededTreasuryFlows,policy:seededLiquidityPolicy});
export const seededTreasuryTransfer=approveTreasuryTransfer(proposeTreasuryTransfer(seededLiquidityForecast,{transferId:"TRANSFER-SIM-1",amountMinor:180_000,sourceAccountReference:"account:/corporate/liquidity",destinationAccountReference:"account:/risk-pool/usd",makerId:"principal-treasury-maker",evidenceDigest:"sha256:eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee"}),{checkerId:"principal-risk-checker",assurance:"STEP_UP"});
const programmeDraft:RiskTransferProgramme={programmeId:"RTP-US-XOL-1",legalEntityId:"fuelcap-us",currency:"USD",type:"EXCESS_OF_LOSS",attachmentMinor:100_000,limitMinor:400_000,cededShareBps:8000,collateralMinor:320_000,counterparty:"SIMULATED-RISK-CARRIER",counterpartyConcentrationBps:6000,dueDiligenceState:"APPROVED",wordingState:"APPROVED",makerId:"principal-risk-maker",checkerId:null,state:"DRAFT",simulated:true,bindingAuthority:false};
export const seededRiskTransferProgramme=approveRiskTransferProgramme(programmeDraft,{checkerId:"principal-treasury-checker",assurance:"STEP_UP"});
export const seededRecoveryProjection=projectRiskTransfer(seededRiskTransferProgramme,450_000,{minimumCollateralCoverageBps:10_000,maximumCounterpartyConcentrationBps:7000});
