import { describe, expect, it } from "vitest";
import { acknowledgeAlert, alertsForOrganisation, assignAlert, filterAlerts, initialAlertEvents, resolveAlert, seededAlerts, summariseAlert, validateAlert, type AlertEvent, type GovernedAlert } from "./alert-lifecycle";

describe("governed alert lifecycle", () => {
  const operational = seededAlerts[0]; const events = initialAlertEvents[operational.alertId];
  it("validates four case-linked synthetic alerts", () => { expect(seededAlerts).toHaveLength(4); expect(new Set(seededAlerts.map(({ domain }) => domain)).size).toBe(4); seededAlerts.forEach((alert) => expect(validateAlert(alert, initialAlertEvents[alert.alertId])).toEqual({ valid: true, eventCount: 1 })); });
  it("enforces ordered acknowledgement, assignment and evidence-backed resolution", () => { const acknowledged = acknowledgeAlert(operational, events, "principal-operations", "OP"); const assigned = assignAlert(acknowledged.alert, acknowledged.events, "principal-operations", "OP", "principal-operations"); expect(() => resolveAlert(assigned.alert, assigned.events, "principal-operations", "OP", "", [])).toThrow("evidence"); const resolved = resolveAlert(assigned.alert, assigned.events, "principal-operations", "OP", "Balanced journal verified.", ["AUD-RECOVERY-0201"]); expect(resolved.alert).toMatchObject({ state: "RESOLVED", ownerId: "principal-operations", assignmentVersion: 1 }); expect(resolved.events.map(({ eventType }) => eventType)).toEqual(["ALERT_OPENED", "ACKNOWLEDGED", "ASSIGNED", "RESOLVED"]); });
  it("rejects out-of-order and Presenter mutations", () => { expect(() => assignAlert(operational, events, "principal-operations", "OP", "principal-operations")).toThrow("acknowledged"); expect(() => acknowledgeAlert(operational, events, "principal-presenter", "DP")).toThrow("not authorised"); });
  it("preserves immutable assignment history", () => { const acknowledged = acknowledgeAlert(operational, events, "op", "OP"); const assigned = assignAlert(acknowledged.alert, acknowledged.events, "op", "OP", "owner-1"); expect(assigned.events.at(-1)).toMatchObject({ eventType: "ASSIGNED", ownerId: "owner-1", immutable: true }); expect(acknowledged.events.at(-1)?.ownerId).toBeNull(); });
  it("rejects duplicate, broken-link and cross-tenant evidence", () => { expect(() => validateAlert(operational, [events[0], events[0]])).toThrow("Duplicate"); expect(() => validateAlert({ ...operational, linkedCaseId: "CASE-MISSING" }, events)).toThrow("Broken"); expect(() => validateAlert(operational, [{ ...events[0], organisationId: "org-other" } as AlertEvent])).toThrow("Cross-tenant"); expect(() => validateAlert({ ...operational, schemaVersion: "governed-alert@2" } as unknown as GovernedAlert, events)).toThrow("Incompatible"); });
  it("filters with reconciling counts and no tenant leakage", () => { expect(filterAlerts(seededAlerts, { domain: "DATA" })).toHaveLength(1); expect(filterAlerts(seededAlerts, { state: "OPEN" })).toHaveLength(4); expect(alertsForOrganisation(seededAlerts, "org-fuelcap-global")).toHaveLength(4); expect(alertsForOrganisation(seededAlerts, "org-fleet-northstar")).toEqual([]); });
  it("provides cited summaries and abstains without evidence", () => { expect(summariseAlert(operational, events)).toMatchObject({ status: "SUPPORTED", confidenceBps: 9700 }); expect(summariseAlert({ ...operational, evidenceIds: [] }, [])).toMatchObject({ status: "ABSTAIN" }); });
});
