import { describe, expect, it } from "vitest";
import { acknowledgeAlert, assignAlert, initialAlertEvents, seededAlerts } from "./alert-lifecycle";
import { escalateAlert, expireGovernedAction, filterEscalatedAlerts, filterTerminalRequests, rejectGovernedAction, replaceTerminalRequest } from "./exception-controls";
import { approveGovernedAction, beginGovernedExecution, draftConfigurationRequest, requestGovernedApproval, simulateGovernedAction, validateGovernedAction } from "./maker-checker";

const pending = () => requestGovernedApproval(simulateGovernedAction(validateGovernedAction(draftConfigurationRequest)));

describe("rejection, expiry and escalation controls", () => {
  it("allows an exact-bound different checker rejection", () => { const request = pending(); const rejected = rejectGovernedAction(request, { checkerId: "principal-platform", checkerRole: "PA", requestVersion: request.requestVersion, evidenceDigest: request.evidenceDigest, reasonCode: "CHANGE_NOT_JUSTIFIED", rationaleReference: "NOTE-REJECT-0092" }); expect(rejected).toMatchObject({ state: "REJECTED", rejection: { checkerId: "principal-platform", reasonCode: "CHANGE_NOT_JUSTIFIED" } }); expect(() => beginGovernedExecution(rejected, rejected.requestVersion, rejected.evidenceDigest)).toThrow("expected APPROVED"); expect(replaceTerminalRequest(rejected)).toMatchObject({ state: "DRAFT", requestVersion: 2, rejection: null }); });
  it("denies self, wrong-role, stale-version and changed-evidence rejection", () => { const request = pending(); const base = { checkerId: "principal-platform", checkerRole: "PA" as const, requestVersion: request.requestVersion, evidenceDigest: request.evidenceDigest, reasonCode: "REJECT", rationaleReference: "NOTE-1" }; expect(() => rejectGovernedAction(request, { ...base, checkerId: request.makerId })).toThrow("Self"); expect(() => rejectGovernedAction(request, { ...base, checkerRole: "OP" })).toThrow("DI or PA"); expect(() => rejectGovernedAction(request, { ...base, requestVersion: 0 })).toThrow("Stale"); expect(() => rejectGovernedAction(request, { ...base, evidenceDigest: "changed" })).toThrow("Changed evidence"); });
  it("expires deterministically and idempotently using injected time", () => { const request = pending(); expect(() => expireGovernedAction(request, "2026-08-25T17:59:59.000Z")).toThrow("not eligible"); const expired = expireGovernedAction(request, request.expiresAt); expect(expired.state).toBe("EXPIRED"); expect(expireGovernedAction(expired, "2026-08-25T19:00:00.000Z")).toBe(expired); expect(() => approveGovernedAction(expired, { checkerId: "checker", checkerRole: "PA", assurance: "step-up", requestVersion: expired.requestVersion, evidenceDigest: expired.evidenceDigest })).toThrow("expected PENDING_APPROVAL"); });
  it("reconciles pending, rejected and expired filters", () => { const request = pending(); const rejected = rejectGovernedAction(request, { checkerId: "checker", checkerRole: "DI", requestVersion: 1, evidenceDigest: request.evidenceDigest, reasonCode: "REJECT", rationaleReference: "NOTE" }); const expired = expireGovernedAction(request, request.expiresAt); expect(filterTerminalRequests([request, rejected, expired], "PENDING_APPROVAL")).toHaveLength(1); expect(filterTerminalRequests([request, rejected, expired], "REJECTED")).toHaveLength(1); expect(filterTerminalRequests([request, rejected, expired], "EXPIRED")).toHaveLength(1); });
  it("escalates eligible alerts through levels one and two with immutable ownership history", () => { const base = seededAlerts[0]; const acknowledged = acknowledgeAlert(base, initialAlertEvents[base.alertId], "op", "OP"); const assigned = assignAlert(acknowledged.alert, acknowledged.events, "op", "OP", "owner-1"); const level1 = escalateAlert(assigned.alert, assigned.events, { actorId: "op", actorRole: "OP", injectedNow: "2026-08-25T22:00:00.000Z", target: "ops-lead" }); expect(level1.alert).toMatchObject({ state: "ESCALATED", escalationLevel: 1, ownerId: "ops-lead" }); expect(level1.events.at(-1)).toMatchObject({ eventType: "ESCALATED", immutable: true }); const beforeThreshold = escalateAlert(level1.alert, level1.events, { actorId: "op", actorRole: "OP", injectedNow: "2026-08-25T22:30:00.000Z", target: "incident-lead" }); expect(beforeThreshold.idempotent).toBe(true); const level2 = escalateAlert(level1.alert, level1.events, { actorId: "op", actorRole: "OP", injectedNow: "2026-08-25T23:00:00.000Z", target: "incident-lead" }); expect(level2.alert.escalationLevel).toBe(2); expect(filterEscalatedAlerts([level1.alert, level2.alert], 2)).toHaveLength(1); expect(escalateAlert(level2.alert, level2.events, { actorId: "op", actorRole: "OP", injectedNow: "2026-08-26T02:00:00.000Z", target: "other" }).idempotent).toBe(true); });
  it("denies escalation for read-only roles and ineligible states", () => { const base = seededAlerts[0]; expect(() => escalateAlert(base, initialAlertEvents[base.alertId], { actorId: "au", actorRole: "AU", injectedNow: "2026-08-26T00:00:00.000Z", target: "lead" })).toThrow("not authorised"); expect(() => escalateAlert(base, initialAlertEvents[base.alertId], { actorId: "op", actorRole: "OP", injectedNow: "2026-08-26T00:00:00.000Z", target: "lead" })).toThrow("unresolved acknowledged"); });
});
