import { describe, expect, it } from "vitest";
import { approveGovernedAction, beginGovernedExecution, completeGovernedExecution, draftConfigurationRequest, requestGovernedApproval, runRepresentativeMakerCheckerFlow, simulateGovernedAction, validateGovernedAction, verifyGovernedExecution } from "./maker-checker";

const pending = () => requestGovernedApproval(simulateGovernedAction(validateGovernedAction(draftConfigurationRequest)));
const approval = (request = pending()) => ({ checkerId: "pa-checker", checkerRole: "PA", assurance: "step-up", requestVersion: request.requestVersion, evidenceDigest: request.evidenceDigest } as const);

describe("maker-checker governed action", () => {
  it("runs the ordered representative request through verification", () => expect(runRepresentativeMakerCheckerFlow()).toMatchObject({ state: "VERIFIED", executorId: "configuration-deployer", executionHash: draftConfigurationRequest.afterHash, verificationEvidenceId: "HEALTH-CHECK-0092" }));
  it("appends an immutable transition ID for every state", () => expect(runRepresentativeMakerCheckerFlow().immutableTransitionIds).toEqual(["GA-EVT-0092-DRAFT", "GA-EVT-0092-VALIDATED", "GA-EVT-0092-SIMULATED", "GA-EVT-0092-PENDING", "GA-EVT-0092-APPROVED", "GA-EVT-0092-EXECUTING", "GA-EVT-0092-EXECUTED", "GA-EVT-0092-VERIFIED"]));
  it("rejects out-of-order lifecycle transitions", () => { expect(() => simulateGovernedAction(draftConfigurationRequest)).toThrow("Invalid transition"); expect(() => completeGovernedExecution(pending())).toThrow("Invalid transition"); });
  it("requires complete safe validation evidence", () => { expect(() => validateGovernedAction({ ...draftConfigurationRequest, evidenceIds: [] })).toThrow("evidence"); expect(() => validateGovernedAction({ ...draftConfigurationRequest, secretValueDisplayed: true } as unknown as typeof draftConfigurationRequest)).toThrow("secret reference"); expect(() => validateGovernedAction({ ...draftConfigurationRequest, afterHash: draftConfigurationRequest.beforeHash })).toThrow("configuration change"); });
  it("requires a different DI/PA checker with fresh step-up", () => { const request = pending(); expect(approveGovernedAction(request, approval(request)).state).toBe("APPROVED"); expect(() => approveGovernedAction(request, { ...approval(request), checkerId: request.makerId })).toThrow("Self-approval"); expect(() => approveGovernedAction(request, { ...approval(request), checkerRole: "OP" })).toThrow("DI or PA"); expect(() => approveGovernedAction(request, { ...approval(request), assurance: "standard" })).toThrow("step-up"); });
  it("rejects stale versions and changed evidence", () => { const request = pending(); expect(() => approveGovernedAction(request, { ...approval(request), requestVersion: 0 })).toThrow("Stale"); expect(() => approveGovernedAction(request, { ...approval(request), evidenceDigest: "sha256:changed" })).toThrow("Changed evidence"); });
  it("binds execution to the exact approved version and evidence", () => { const request = pending(); const approved = approveGovernedAction(request, approval(request)); expect(beginGovernedExecution(approved, approved.requestVersion, approved.evidenceDigest).state).toBe("EXECUTING"); expect(() => beginGovernedExecution(approved, 2, approved.evidenceDigest)).toThrow("exact bound"); expect(() => beginGovernedExecution(approved, approved.requestVersion, "sha256:changed")).toThrow("exact bound"); });
  it("requires post-change health before verification", () => { const request = pending(); const approved = approveGovernedAction(request, approval(request)); const executed = completeGovernedExecution(beginGovernedExecution(approved, approved.requestVersion, approved.evidenceDigest)); expect(() => verifyGovernedExecution(executed, "")).toThrow("health evidence"); });
  it("never exposes a secret or moves customer money", () => expect(runRepresentativeMakerCheckerFlow()).toMatchObject({ secretValueDisplayed: false, moneyMovement: false, customerImpact: "NONE", environment: "demo" }));
});
