import { describe, expect, it } from "vitest";
import { adapters, approveIntegrationConfiguration, auditRecords, configurationProposal, correlationTrace, incident, platformRelease, replayEvent, serviceChecks, validateWebhook, webhookReceipt } from "./platform-integrations-audit";
import { latestVerifiedRelease } from "./release-rehearsal";

const approval = { initiatedBy: "di-maker", approvedBy: "di-checker", approverRole: "DI", assurance: "step-up", compatibilityStatus: "PASS", rollbackReference: configurationProposal.rollbackReference, secretValueDisplayed: false } as const;

describe("platform, integrations and audit", () => {
  it("exposes the verified release anchor and honest demonstrator health evidence", () => { expect(platformRelease).toMatchObject({ deploymentCommit: latestVerifiedRelease.commit.slice(0, 7), health: "HEALTHY", productionGradeSloClaimed: false }); expect(serviceChecks.some(({ health }) => health === "DEGRADED")).toBe(true); });
  it("labels every adapter mode and never displays credentials", () => { expect(adapters.map(({ mode }) => mode)).toEqual(["TEST", "SIMULATED", "MOCK"]); expect(adapters.every(({ compatible, secretDisplayed }) => compatible && !secretDisplayed)).toBe(true); });
  it("blocks an invalid signature before domain processing", () => expect(validateWebhook(webhookReceipt)).toEqual({ accepted: false, reasonCode: "DENY_INVALID_SIGNATURE" }));
  it("preserves typed receipt and dead-letter ownership", () => expect(webhookReceipt).toMatchObject({ processingState: "DEAD_LETTER", reasonCode: "INVALID_SIGNATURE", deadLetterOwner: "Data & Integrations", rawPayloadDisplayed: false, tenantValid: true, schemaCompatible: true }));
  it("traces one correlation across the operating chain", () => { expect(correlationTrace).toHaveLength(6); expect(new Set(correlationTrace.map(({ correlationId }) => correlationId))).toEqual(new Set([webhookReceipt.correlationId])); expect(correlationTrace.at(-1)?.state).toBe("SIMULATED"); });
  it("deduplicates replay and never duplicates a financial posting", () => { const inbox = new Set<string>(); const journals = new Set<string>(); expect(replayEvent("EVENT-0091", inbox, journals)).toMatchObject({ status: "REPLAYED", journalPosted: true, duplicateFinancialPosting: false }); expect(replayEvent("EVENT-0091", inbox, journals)).toMatchObject({ status: "DUPLICATE_SUPPRESSED", journalPosted: false, duplicateFinancialPosting: false }); });
  it("records scoped simulated incident and immutable redacted audit", () => { expect(incident).toMatchObject({ affectedCustomers: 0, state: "OPEN", simulated: true }); expect(auditRecords.every(({ immutable, sensitiveFieldsRedacted }) => immutable && sensitiveFieldsRedacted)).toBe(true); });
  it("requires different DI/PA, step-up, compatibility, rollback and secret safety", () => { expect(approveIntegrationConfiguration(approval).status).toBe("APPROVED"); expect(() => approveIntegrationConfiguration({ ...approval, approvedBy: approval.initiatedBy })).toThrow("Self-approval"); expect(() => approveIntegrationConfiguration({ ...approval, approverRole: "OP" })).toThrow("DI or PA"); expect(() => approveIntegrationConfiguration({ ...approval, assurance: "standard" })).toThrow("Step-up"); expect(() => approveIntegrationConfiguration({ ...approval, compatibilityStatus: "FAIL" })).toThrow("Compatibility"); expect(() => approveIntegrationConfiguration({ ...approval, secretValueDisplayed: true })).toThrow("Secret values"); });
});
