import { describe, expect, it } from "vitest";
import { approveRulePublication, blockingValidationEvidence, canonicalScenarioIds, draftEligibilityRule, pinnedRuleDecision, publishedEligibilityRule, replayPinnedRuleDecision, ruleImpact, scenarioRegression, validationEvidence } from "./rules-automation";

const approval = { initiatedBy: "cf-maker", approvedBy: "cf-checker", initiatorRole: "CF", approverRole: "CF", requiredRole: "CF", assurance: "step-up", validationStatus: "PASS", regressionPassed: true } as const;

describe("rules and automation", () => {
  it("keeps published and draft versions effective-dated and linked", () => { expect(publishedEligibilityRule.lifecycle).toBe("PUBLISHED"); expect(draftEligibilityRule).toMatchObject({ lifecycle: "DRAFT", supersedesVersion: publishedEligibilityRule.version }); });
  it("uses only typed restricted conditions", () => expect(draftEligibilityRule.conditions.every(({ fact, operator }) => fact.includes(".") && ["EQ", "IN"].includes(operator))).toBe(true));
  it("records complete passing validation without arbitrary code", () => expect(validationEvidence).toMatchObject({ status: "PASS", arbitraryCodeAllowed: false, checks: { types: "PASS", conflicts: "PASS", fallback: "PASS" } }));
  it("blocks invalid, conflicting, unreachable and fallback-less proposals", () => expect(blockingValidationEvidence).toMatchObject({ status: "BLOCKED", reasonCodes: ["TYPE_MISMATCH", "CONFLICTING_BRANCH", "UNREACHABLE_BRANCH", "MISSING_FALLBACK"] }));
  it("regresses all twelve canonical scenarios", () => { expect(canonicalScenarioIds).toHaveLength(12); expect(scenarioRegression).toHaveLength(12); expect(ruleImpact).toMatchObject({ scenarioCount: 12, passedScenarioCount: 12, status: "PASS" }); });
  it("preserves availability, eligibility and zero-impact evidence", () => { expect(scenarioRegression.find(({ scenarioId }) => scenarioId === "no-valid-quote-uk")?.proposedOutcome).toBe("NOT_QUOTE_ELIGIBLE"); expect(scenarioRegression.find(({ scenarioId }) => scenarioId === "eligibility-fraud-canada")?.proposedOutcome).toBe("HUMAN_REVIEW"); expect(ruleImpact.changedCustomers + ruleImpact.changedTransactions + ruleImpact.exposureDeltaMinor).toBe(0); });
  it("requires different same-domain principals, step-up and green gates", () => { expect(approveRulePublication(approval).status).toBe("SCHEDULED"); expect(() => approveRulePublication({ ...approval, approvedBy: approval.initiatedBy })).toThrow("Self-approval"); expect(() => approveRulePublication({ ...approval, approverRole: "RT" })).toThrow("Same-domain"); expect(() => approveRulePublication({ ...approval, assurance: "standard" })).toThrow("Step-up"); expect(() => approveRulePublication({ ...approval, regressionPassed: false })).toThrow("Validation and regression"); });
  it("replays only with the original pinned rule, facts and clock", () => { expect(replayPinnedRuleDecision(pinnedRuleDecision.ruleVersion, "eligibility-facts@1.0", pinnedRuleDecision.evaluatedAt)).toBe(pinnedRuleDecision); expect(pinnedRuleDecision.immutable).toBe(true); expect(() => replayPinnedRuleDecision("eligibility@latest", "eligibility-facts@1.0", pinnedRuleDecision.evaluatedAt)).toThrow("original pinned inputs"); });
});
