import { CASE_SCHEMA_VERSION, casesForOrganisation, openCaseTimeline, validateSharedCase, type CaseTimelineEntry, type SharedCase, type SharedCaseDomain } from "./shared-case";

const links = (overrides: Partial<SharedCase["linkedEntities"]>): SharedCase["linkedEntities"] => ({ customerId: null, fleetId: null, vehicleId: null, transactionId: null, quoteId: null, protectionId: null, journalId: null, providerReceiptId: null, incidentId: null, alertId: null, governedActionId: null, auditCorrelationId: "", ...overrides });
const seed = (input: Omit<SharedCase, "caseVersion" | "schemaVersion" | "environment" | "market" | "scenarioVersion" | "provenance" | "ownerId" | "assignmentVersion" | "updatedAt" | "slaState" | "dataClassification" | "sensitiveFieldsRedacted" | "correlationId" | "causationId" | "auditEventIds" | "resolutionReason" | "recoveryVerified" | "closedAt" | "linkedPriorCaseVersion">): SharedCase => ({ ...input, caseVersion: 1, schemaVersion: CASE_SCHEMA_VERSION, environment: "demo", market: "GLOBAL", scenarioVersion: "1.0.0", provenance: "synthetic-seeded", ownerId: null, assignmentVersion: 0, updatedAt: input.openedAt, slaState: "ON_TRACK", dataClassification: "CONFIDENTIAL", sensitiveFieldsRedacted: true, correlationId: input.linkedEntities.auditCorrelationId, causationId: input.evidenceIds[0], auditEventIds: input.evidenceIds.filter((id) => id.startsWith("AUD-")), resolutionReason: null, recoveryVerified: false, closedAt: null, linkedPriorCaseVersion: null });

export const seededDomainCases: readonly SharedCase[] = [
  seed({ caseId: "CASE-OPS-0101", caseType: "SETTLEMENT_RECONCILIATION_INTEGRITY", domain: "OPERATIONS", state: "OPEN", organisationId: "org-fuelcap-global", scenarioId: "settlement-boundary", severity: { customerMoney: "MEDIUM", integrity: "HIGH", privacySecurity: "NONE", operational: "HIGH", regulatory: "LOW" }, title: "Review settlement break without silent posting", reasonCodes: ["RECONCILIATION_BREAK", "POSTING_BLOCKED"], summary: "A deterministic settlement mismatch is held before posting while ledger evidence is reconciled.", ownerTeam: "FINANCE_OPERATIONS", openedAt: "2026-08-25T17:00:00.000Z", dueAt: "2026-08-25T21:00:00.000Z", linkedEntities: links({ transactionId: "TXN-BOUNDARY-0042", journalId: "JRN-SETTLE-0042", incidentId: "INC-SETTLE-0042", auditCorrelationId: "CORR-CASE-OPS-0101" }), impact: { customerValueMinor: 18420, capability: "SETTLEMENT_POSTING", holdId: "HOLD-SETTLE-0042", restrictionId: null }, evidenceIds: ["AUD-SETTLE-0042", "JRN-SETTLE-0042"], retentionPolicy: "financial-case@1.0", recoveryRoute: "Reconcile balanced journal legs, verify provider receipt and release only through governed posting." }),
  seed({ caseId: "CASE-FRAUD-0102", caseType: "SUSPICIOUS_TRANSACTION_REVIEW", domain: "FRAUD", state: "OPEN", organisationId: "org-fuelcap-global", scenarioId: "fraud-review", severity: { customerMoney: "MEDIUM", integrity: "MEDIUM", privacySecurity: "MEDIUM", operational: "LOW", regulatory: "HIGH" }, title: "Review statistically unusual transaction", reasonCodes: ["VELOCITY_OUTLIER", "HUMAN_REVIEW_REQUIRED"], summary: "Statistical signals require review; they do not establish fraud or customer guilt.", ownerTeam: "COMPLIANCE_FRAUD", openedAt: "2026-08-25T17:05:00.000Z", dueAt: "2026-08-26T17:05:00.000Z", linkedEntities: links({ customerId: "CUS-DEMO-0048", vehicleId: "VEH-DEMO-0048", transactionId: "TXN-DEMO-0048", auditCorrelationId: "CORR-CASE-FRAUD-0102" }), impact: { customerValueMinor: 9200, capability: "TRANSACTION_SETTLEMENT", holdId: "HOLD-FRAUD-0048", restrictionId: null }, evidenceIds: ["AUD-FRAUD-0048", "MODEL-FAIRNESS-001"], retentionPolicy: "fraud-case@1.0", recoveryRoute: "Human reviewer evaluates cited signals and fairness evidence before releasing or escalating the hold." }),
  seed({ caseId: "CASE-DATA-0103", caseType: "PRICING_SOURCE_QUALITY_REVIEW", domain: "DATA", state: "OPEN", organisationId: "org-fuelcap-global", scenarioId: "pricing-source-conflict", severity: { customerMoney: "LOW", integrity: "HIGH", privacySecurity: "NONE", operational: "MEDIUM", regulatory: "LOW" }, title: "Resolve conflicting pricing observation", reasonCodes: ["SOURCE_CONFLICT", "DECISION_INELIGIBLE"], summary: "A conflicting observation is excluded from pricing until provenance and eligibility are verified.", ownerTeam: "DATA_INTEGRATIONS", openedAt: "2026-08-25T17:10:00.000Z", dueAt: "2026-08-25T23:10:00.000Z", linkedEntities: links({ quoteId: "QUOTE-GLOBAL-1101", governedActionId: "GA-PRICE-SOURCE-0103", auditCorrelationId: "CORR-CASE-DATA-0103" }), impact: { customerValueMinor: 0, capability: "CANONICAL_PRICE_SELECTION", holdId: null, restrictionId: "RESTRICT-SOURCE-0103" }, evidenceIds: ["AUD-PRICE-0103", "OBS-PRICE-0103"], retentionPolicy: "pricing-case@1.0", recoveryRoute: "Verify licence, freshness and anomaly evidence before a governed source decision is published." }),
  seed({ caseId: "CASE-COMP-0104", caseType: "CONSENT_RETENTION_CONTROL_REVIEW", domain: "COMPLIANCE", state: "OPEN", organisationId: "org-fuelcap-global", scenarioId: "retention-review", severity: { customerMoney: "NONE", integrity: "MEDIUM", privacySecurity: "HIGH", operational: "LOW", regulatory: "HIGH" }, title: "Verify consent and retention control", reasonCodes: ["RETENTION_POLICY_REVIEW", "HUMAN_DECISION_REQUIRED"], summary: "A synthetic retention-policy conflict requires a human decision against cited consent and jurisdiction evidence.", ownerTeam: "COMPLIANCE_FRAUD", openedAt: "2026-08-25T17:15:00.000Z", dueAt: "2026-08-27T17:15:00.000Z", linkedEntities: links({ customerId: "CUS-DEMO-0051", governedActionId: "GA-RETENTION-0104", auditCorrelationId: "CORR-CASE-COMP-0104" }), impact: { customerValueMinor: 0, capability: "CUSTOMER_DATA_RETENTION", holdId: null, restrictionId: "RESTRICT-DISPOSAL-0104" }, evidenceIds: ["AUD-CONSENT-0051", "POLICY-RETENTION-UK-003"], retentionPolicy: "privacy-case@1.0", recoveryRoute: "Confirm consent version, jurisdiction and legal-hold status before a governed retention decision." }),
];

export const seededDomainCaseTimelines: Readonly<Record<string, readonly CaseTimelineEntry[]>> = Object.fromEntries(seededDomainCases.map((caseRecord) => [caseRecord.caseId, openCaseTimeline(caseRecord)]));
export const seededCasesForOrganisation = (organisationId: string) => casesForOrganisation(seededDomainCases, organisationId);
export const filterSeededCases = (cases: readonly SharedCase[], input: Readonly<{ domain?: SharedCaseDomain; state?: SharedCase["state"]; severity?: SharedCase["severity"][keyof SharedCase["severity"]]; }>) => cases.filter((caseRecord) => (!input.domain || caseRecord.domain === input.domain) && (!input.state || caseRecord.state === input.state) && (!input.severity || Object.values(caseRecord.severity).includes(input.severity)));

export function validateSeededCaseCatalogue(cases: readonly SharedCase[], timelines: Readonly<Record<string, readonly CaseTimelineEntry[]>>) {
  if (cases.length !== 4 || new Set(cases.map(({ domain }) => domain)).size !== 4) throw new Error("Exactly four distinct seeded domains are required.");
  if (new Set(cases.map(({ caseId }) => caseId)).size !== cases.length) throw new Error("Duplicate seeded case ID.");
  for (const caseRecord of cases) {
    const timeline = timelines[caseRecord.caseId];
    if (!timeline || !caseRecord.evidenceIds.length || !caseRecord.linkedEntities.auditCorrelationId) throw new Error("Seeded case evidence and correlation are required.");
    validateSharedCase(caseRecord, timeline);
  }
  return { valid: true as const, caseCount: cases.length, domains: cases.map(({ domain }) => domain) };
}
