import { describe, expect, it } from "vitest";
import { filterSeededCases, seededCasesForOrganisation, seededDomainCases, seededDomainCaseTimelines, validateSeededCaseCatalogue } from "./seeded-domain-cases";
import { summariseCase } from "./shared-case";

describe("seeded domain case catalogue", () => {
  it("validates exactly four distinct immutable domain seeds", () => expect(validateSeededCaseCatalogue(seededDomainCases, seededDomainCaseTimelines)).toMatchObject({ valid: true, caseCount: 4, domains: ["OPERATIONS", "FRAUD", "DATA", "COMPLIANCE"] }));
  it("uses unique IDs, correlations and synthetic provenance", () => { expect(new Set(seededDomainCases.map(({ caseId }) => caseId)).size).toBe(4); expect(new Set(seededDomainCases.map(({ correlationId }) => correlationId)).size).toBe(4); expect(seededDomainCases.every(({ provenance, sensitiveFieldsRedacted }) => provenance === "synthetic-seeded" && sensitiveFieldsRedacted)).toBe(true); });
  it("keeps domain links typed and recovery routes explicit", () => { expect(seededDomainCases.find(({ domain }) => domain === "OPERATIONS")?.linkedEntities.journalId).toBe("JRN-SETTLE-0042"); expect(seededDomainCases.find(({ domain }) => domain === "FRAUD")?.impact.holdId).toBe("HOLD-FRAUD-0048"); expect(seededDomainCases.find(({ domain }) => domain === "DATA")?.linkedEntities.quoteId).toBe("QUOTE-GLOBAL-1101"); expect(seededDomainCases.find(({ domain }) => domain === "COMPLIANCE")?.impact.restrictionId).toBe("RESTRICT-DISPOSAL-0104"); expect(seededDomainCases.every(({ recoveryRoute }) => recoveryRoute.length > 20)).toBe(true); });
  it("filters by domain, state and decomposed severity with reconciling counts", () => { expect(filterSeededCases(seededDomainCases, { domain: "FRAUD" })).toHaveLength(1); expect(filterSeededCases(seededDomainCases, { state: "OPEN" })).toHaveLength(4); expect(filterSeededCases(seededDomainCases, { severity: "HIGH" })).toHaveLength(4); });
  it("does not leak catalogue rows or counts across organisations", () => { expect(seededCasesForOrganisation("org-fuelcap-global")).toHaveLength(4); expect(seededCasesForOrganisation("org-fleet-northstar")).toEqual([]); });
  it("produces evidence-cited summaries and abstains without evidence", () => { const selected = seededDomainCases[0]; expect(summariseCase(selected, seededDomainCaseTimelines[selected.caseId])).toMatchObject({ status: "SUPPORTED", confidenceBps: 9700 }); expect(summariseCase({ ...selected, evidenceIds: [] }, [])).toMatchObject({ status: "ABSTAIN" }); });
  it("rejects duplicate IDs and missing evidence", () => { expect(() => validateSeededCaseCatalogue([...seededDomainCases.slice(0, 3), seededDomainCases[0]], seededDomainCaseTimelines)).toThrow(); const missing = { ...seededDomainCases[0], evidenceIds: [] }; expect(() => validateSeededCaseCatalogue([missing, ...seededDomainCases.slice(1)], { ...seededDomainCaseTimelines, [missing.caseId]: seededDomainCaseTimelines[missing.caseId] })).toThrow("evidence"); });
});
