import { describe, expect, it } from "vitest";
import { addInvestigatorNote, assignCase, casesForOrganisation, initialCaseTimeline, prepareResolution, representativeSharedCase, summariseCase, transitionCase, validateSharedCase, type CaseTimelineEntry, type SharedCase } from "./shared-case";

describe("shared case model", () => {
  it("validates the versioned tenant-scoped case and timeline", () => expect(validateSharedCase(representativeSharedCase, initialCaseTimeline)).toEqual({ valid: true, entryCount: 1 }));
  it("rejects duplicate entries, incompatible versions and cross-tenant rows", () => { expect(() => validateSharedCase(representativeSharedCase, [initialCaseTimeline[0], initialCaseTimeline[0]])).toThrow("Duplicate"); expect(() => validateSharedCase({ ...representativeSharedCase, schemaVersion: "shared-case@2.0" } as unknown as SharedCase, initialCaseTimeline)).toThrow("Incompatible"); expect(() => validateSharedCase(representativeSharedCase, [{ ...initialCaseTimeline[0], organisationId: "org-other" }])).toThrow("Cross-tenant"); });
  it("rejects broken causation and executable timeline content", () => { expect(() => validateSharedCase(representativeSharedCase, [{ ...initialCaseTimeline[0], causationId: "missing" }])).toThrow("Broken"); expect(() => validateSharedCase(representativeSharedCase, [{ ...initialCaseTimeline[0], toolExecutionAllowed: true } as unknown as CaseTimelineEntry])).toThrow("integrity"); });
  it("preserves assignment history and denies Presenter assignment", () => { const assigned = assignCase(representativeSharedCase, initialCaseTimeline, { actorId: "principal-operations", actorRole: "OP", ownerId: "principal-data" }); expect(assigned.caseRecord).toMatchObject({ ownerId: "principal-data", assignmentVersion: 1 }); expect(assigned.timeline.at(-1)?.entryType).toBe("ASSIGNED"); expect(() => assignCase(representativeSharedCase, initialCaseTimeline, { actorId: "principal-presenter", actorRole: "DP", ownerId: "principal-data" })).toThrow("not authorised"); });
  it("records notes as append-only untrusted non-executable evidence", () => expect(addInvestigatorNote(representativeSharedCase, initialCaseTimeline, "principal-data", "sha256:note-0092").at(-1)).toMatchObject({ entryType: "NOTE_ADDED", untrustedInput: true, toolExecutionAllowed: false, immutable: true }));
  it("enforces ordered transitions", () => { expect(transitionCase(representativeSharedCase, initialCaseTimeline, "TRIAGED", "principal-operations", "TRIAGE_COMPLETE").caseRecord.state).toBe("TRIAGED"); expect(() => transitionCase(representativeSharedCase, initialCaseTimeline, "CLOSED", "principal-operations", "CLOSE")).toThrow("Invalid"); });
  it("requires evidence-backed resolution and verified closure", () => { const triaged = transitionCase(representativeSharedCase, initialCaseTimeline, "TRIAGED", "op", "TRIAGE"); const investigating = transitionCase(triaged.caseRecord, triaged.timeline, "INVESTIGATING", "di", "INVESTIGATE"); expect(() => transitionCase(investigating.caseRecord, investigating.timeline, "RESOLVED", "di", "RESOLVE")).toThrow("Resolution evidence"); const ready = prepareResolution(investigating.caseRecord, "Signed test receipt and adapter health verified.", true); const resolved = transitionCase(ready, investigating.timeline, "RESOLVED", "di", "RECOVERY_VERIFIED"); expect(transitionCase(resolved.caseRecord, resolved.timeline, "CLOSED", "op", "CLOSE_VERIFIED").caseRecord.state).toBe("CLOSED"); });
  it("reopens through a linked new version without losing closure", () => { const triaged = transitionCase(representativeSharedCase, initialCaseTimeline, "TRIAGED", "op", "TRIAGE"); const investigating = transitionCase(triaged.caseRecord, triaged.timeline, "INVESTIGATING", "di", "INVESTIGATE"); const resolved = transitionCase(prepareResolution(investigating.caseRecord, "Verified.", true), investigating.timeline, "RESOLVED", "di", "RESOLVE"); const closed = transitionCase(resolved.caseRecord, resolved.timeline, "CLOSED", "op", "CLOSE"); const reopened = transitionCase(closed.caseRecord, closed.timeline, "INVESTIGATING", "op", "NEW_EVIDENCE"); expect(reopened.caseRecord).toMatchObject({ state: "INVESTIGATING", linkedPriorCaseVersion: closed.caseRecord.caseVersion }); expect(reopened.timeline.at(-1)?.entryType).toBe("REOPENED"); });
  it("filters cases by organisation without leaking counts", () => { expect(casesForOrganisation([representativeSharedCase], "org-fuelcap-global")).toHaveLength(1); expect(casesForOrganisation([representativeSharedCase], "org-fleet-northstar")).toEqual([]); });
  it("provides cited case summary and abstains without evidence", () => { expect(summariseCase(representativeSharedCase, initialCaseTimeline)).toMatchObject({ status: "SUPPORTED", confidenceBps: 9700 }); expect(summariseCase({ ...representativeSharedCase, evidenceIds: [] }, [])).toMatchObject({ status: "ABSTAIN" }); });
});
