import { describe, expect, it } from "vitest";
import { assessExposureLimits, createExposureSnapshot, runApprovedStressSuite, type AcceptedPosition, type StressAssumption } from "./index";
import { approvePaperHedge, createPaperHedgeRecommendation, executePaperHedge } from "./paper";

const position: AcceptedPosition = { positionId: "POS-1", organisationId: "ORG-1", legalEntityId: "LE-US", status: "ACCEPTED", remainingQuantity4dp: 684_000_000, market: "US-TX", grade: "REGULAR", geography: "TX", currency: "USD", strikePrice4dp: 36_750, boundaryPrice4dp: 40_250, expiry: "2026-09-01", customerId: "CUS-1", fleetId: "FLEET-1", basisRiskCategory: "RETAIL_WHOLESALE", expectedClaimMinor: 1_408_800, priceDecisionVersion: "price@1", spreadDecisionVersion: "spread@1", fxDecisionVersion: "fx@1", rulesVersion: "rules@1" };
const snapshot = () => createExposureSnapshot({ snapshotId: "EXP-1", organisationId: "ORG-1", legalEntityId: "LE-US", currency: "USD", asOf: "2026-08-27", reserveAvailableMinor: 2_394_960, reconciliationStatus: "PASS", positions: [position] });
const limits = { limitVersion: "limits@1", maxQuantity4dp: 1_000_000_000, maxValueAtBoundaryMinor: 3_000_000, maxConcentrationBps: 10_000, minimumReserveCoverageBps: 10_000, warningUtilisationBps: 7500 } as const;
const kinds = ["CALM", "WITHIN_BOUNDARY_RISE", "BOUNDARY_BREACH", "VOLATILITY_SHOCK", "BASIS_DIVERGENCE", "CORRELATION_BREAKDOWN", "COUNTERPARTY_FAILURE"] as const;
const assumptions: readonly StressAssumption[] = kinds.map((kind, index) => ({ stressId: `STRESS-${index}`, kind, modelVersion: "black-76@1", assumptionVersion: "market-inputs@1", claimBpsOfBoundaryValue: 10_000, payoffBpsOfBoundaryValue: kind === "COUNTERPARTY_FAILURE" ? 0 : 3000, basisResidualBpsOfBoundaryValue: kind === "BASIS_DIVERGENCE" ? 500 : 0 }));
const recommendation = (overrides: Record<string, unknown> = {}) => createPaperHedgeRecommendation({ recommendationId: "REC-1", version: 1, snapshot: snapshot(), limitAssessment: assessExposureLimits(snapshot(), limits), stresses: runApprovedStressSuite(snapshot(), assumptions), modelInputs: { modelVersion: "black-76@1", assumptionVersion: "market-inputs@1", volatilityBps: 2200, forwardPrice4dp: 39_000, riskFreeRateBps: 450, basisAdjustmentBps: 75, estimatedProtectionCostBps: 130, spreadProtectionCostBps: 130 }, instrument: "SIMULATED_CALL_SPREAD", notionalQuantity4dp: 250_000_000, strikePrice4dp: 38_500, capPrice4dp: 40_250, expiry: "2026-09-01", estimatedPremiumMinor: 325_000, simulatedCounterparty: "Demo Energy Markets", rationale: "Reduce boundary exposure while retaining a governed pool", evidenceIds: ["MODEL-EVD-1"], ...overrides });
const approval = () => approvePaperHedge(recommendation(), { approvalId: "APR-1", initiatedBy: "rt-maker", approvedBy: "rt-checker", assurance: "STEP_UP", assuranceAt: "2026-08-27T10:00:00Z", approvedAt: "2026-08-27T10:03:00Z", reason: "Stress evidence supports simulated cover" });

describe("paper hedging engine", () => {
  it("pins the recommendation to snapshot, limits, stresses and model inputs", () => expect(recommendation()).toMatchObject({ exposureSnapshotId: "EXP-1", limitVersion: "limits@1", stressIds: ["STRESS-0", "STRESS-1", "STRESS-2", "STRESS-3", "STRESS-4", "STRESS-5", "STRESS-6"], modelInputs: { modelVersion: "black-76@1" }, executionBoundary: "SIMULATION_ONLY" }));
  it("fixes the demonstrator recommendation at 25,000 gallons", () => expect(recommendation()).toMatchObject({ notionalQuantity4dp: 250_000_000, instrument: "SIMULATED_CALL_SPREAD" }));
  it("reconciles modeled protection cost to the Spread Engine", () => expect(() => recommendation({ modelInputs: { modelVersion: "black-76@1", assumptionVersion: "inputs@1", volatilityBps: 2200, forwardPrice4dp: 39000, riskFreeRateBps: 450, basisAdjustmentBps: 75, estimatedProtectionCostBps: 129, spreadProtectionCostBps: 130 } })).toThrow(/reconcile/));
  it("rejects notionals above accepted exposure", () => expect(() => recommendation({ notionalQuantity4dp: 684_000_001 })).toThrow(/must not exceed/));
  it("blocks recommendations on reconciliation or critical limits", () => { const broken = { ...snapshot(), reconciliationStatus: "BREAK" as const }; expect(() => recommendation({ snapshot: broken, limitAssessment: assessExposureLimits(broken, limits) })).toThrow(/reconciled/); });
  it("labels the counterparty and execution boundary as simulated", () => expect(recommendation()).toMatchObject({ simulatedCounterparty: "Demo Energy Markets · simulated", executionBoundary: "SIMULATION_ONLY" }));
  it("requires different RT principals and fresh step-up", () => { expect(approval().state).toBe("APPROVED"); expect(() => approvePaperHedge(recommendation(), { approvalId: "A", initiatedBy: "rt", approvedBy: "rt", assurance: "STEP_UP", assuranceAt: "2026-08-27T10:00:00Z", approvedAt: "2026-08-27T10:01:00Z", reason: "Evidence" })).toThrow(/different RT/); expect(() => approvePaperHedge(recommendation(), { approvalId: "A", initiatedBy: "maker", approvedBy: "checker", assurance: "STEP_UP", assuranceAt: "2026-08-27T09:00:00Z", approvedAt: "2026-08-27T10:00:00Z", reason: "Evidence" })).toThrow(/Fresh/); });
  it("creates an immutable simulated execution without money movement", () => expect(executePaperHedge(recommendation(), approval(), { executionId: "EXEC-1", executedBy: "rt-maker", executedAt: "2026-08-27T10:04:00Z" })).toMatchObject({ executionType: "SIMULATED", quantity4dp: 250_000_000, liveAdapterCallable: false, moneyMovementMinor: 0 }));
  it("rejects approval for another recommendation version", () => expect(() => executePaperHedge({ ...recommendation(), version: 2 }, approval(), { executionId: "EXEC", executedBy: "rt", executedAt: "2026-08-27T10:04:00Z" })).toThrow(/pinned/));
  it("preserves audit evidence through execution", () => expect(executePaperHedge(recommendation(), approval(), { executionId: "EXEC-1", executedBy: "rt-maker", executedAt: "2026-08-27T10:04:00Z" }).auditEvidenceIds).toContain("APR-1"));
});
