import type { ExposureSnapshot, LimitAssessment, StressResult } from "./index";

export type PaperHedgeModelInputs = Readonly<{ modelVersion: string; assumptionVersion: string; volatilityBps: number; forwardPrice4dp: number; riskFreeRateBps: number; basisAdjustmentBps: number; estimatedProtectionCostBps: number; spreadProtectionCostBps: number }>;
export type PaperHedgeRecommendation = Readonly<{ recommendationId: string; version: number; organisationId: string; exposureSnapshotId: string; exposureSnapshotVersion: ExposureSnapshot["version"]; limitVersion: string; stressIds: readonly string[]; modelInputs: PaperHedgeModelInputs; instrument: "SIMULATED_CALL" | "SIMULATED_CALL_SPREAD" | "RETAINED_POOL" | "UNHEDGED_RESIDUAL"; notionalQuantity4dp: number; strikePrice4dp: number; capPrice4dp: number | null; expiry: string; estimatedPremiumMinor: number; simulatedCounterparty: string; expectedClaimsBeforeMinor: number; expectedPayoffMinor: number; residualExposureMinor: number; effectivenessBps: number; reserveUseAfterMinor: number; capitalImpactMinor: number; rationale: string; evidenceIds: readonly string[]; state: "PENDING_APPROVAL"; executionBoundary: "SIMULATION_ONLY" }>;
export type PaperHedgeApproval = Readonly<{ approvalId: string; recommendationId: string; recommendationVersion: number; exposureSnapshotId: string; initiatedBy: string; approvedBy: string; assurance: "STEP_UP"; assuranceAt: string; approvedAt: string; reason: string; state: "APPROVED" }>;
export type SimulatedHedgeExecution = Readonly<{ executionId: string; recommendationId: string; recommendationVersion: number; exposureSnapshotId: string; executionType: "SIMULATED"; instrument: PaperHedgeRecommendation["instrument"]; quantity4dp: number; premiumMinor: number; counterparty: string; initiatedBy: string; approvedBy: string; executedBy: string; executedAt: string; liveAdapterCallable: false; moneyMovementMinor: 0; auditEvidenceIds: readonly string[] }>;

export function createPaperHedgeRecommendation(input: Readonly<{ recommendationId: string; version: number; snapshot: ExposureSnapshot; limitAssessment: LimitAssessment; stresses: readonly StressResult[]; modelInputs: PaperHedgeModelInputs; instrument: PaperHedgeRecommendation["instrument"]; notionalQuantity4dp: number; strikePrice4dp: number; capPrice4dp?: number | null; expiry: string; estimatedPremiumMinor: number; simulatedCounterparty: string; rationale: string; evidenceIds: readonly string[] }>): PaperHedgeRecommendation {
  if (!input.recommendationId.trim() || !Number.isSafeInteger(input.version) || input.version <= 0 || input.snapshot.reconciliationStatus !== "PASS" || input.limitAssessment.blocksDownstream || input.limitAssessment.snapshotId !== input.snapshot.snapshotId) throw new Error("Recommendation requires a reconciled snapshot and non-blocking limit assessment.");
  if (input.stresses.length !== 7 || input.stresses.some((stress) => stress.snapshotId !== input.snapshot.snapshotId) || new Set(input.stresses.map(({ kind }) => kind)).size !== 7) throw new Error("Recommendation requires the complete pinned stress suite.");
  if (!Number.isSafeInteger(input.notionalQuantity4dp) || input.notionalQuantity4dp <= 0 || input.notionalQuantity4dp > input.snapshot.acceptedQuantity4dp) throw new Error("Paper hedge notional must not exceed accepted exposure.");
  if (![input.modelInputs.volatilityBps, input.modelInputs.forwardPrice4dp, input.modelInputs.riskFreeRateBps, input.modelInputs.basisAdjustmentBps, input.modelInputs.estimatedProtectionCostBps, input.modelInputs.spreadProtectionCostBps].every(Number.isSafeInteger) || input.modelInputs.volatilityBps <= 0 || input.modelInputs.forwardPrice4dp <= 0 || input.modelInputs.estimatedProtectionCostBps !== input.modelInputs.spreadProtectionCostBps) throw new Error("Versioned model inputs must reconcile to the Spread Engine protection cost.");
  if (!Number.isSafeInteger(input.estimatedPremiumMinor) || input.estimatedPremiumMinor < 0 || !input.simulatedCounterparty.trim() || !input.rationale.trim() || !input.evidenceIds.length || !Number.isFinite(Date.parse(input.expiry))) throw new Error("Premium, simulated counterparty, rationale, evidence and expiry are required.");
  const boundary = input.stresses.find(({ kind }) => kind === "BOUNDARY_BREACH")!;
  const expectedPayoffMinor = boundary.simulatedPayoffMinor;
  const effectivenessBps = boundary.expectedClaimsMinor === 0 ? 0 : Math.round(expectedPayoffMinor * 10_000 / boundary.expectedClaimsMinor);
  return { recommendationId: input.recommendationId, version: input.version, organisationId: input.snapshot.organisationId, exposureSnapshotId: input.snapshot.snapshotId, exposureSnapshotVersion: input.snapshot.version, limitVersion: input.limitAssessment.limitVersion, stressIds: input.stresses.map(({ stressId }) => stressId), modelInputs: { ...input.modelInputs }, instrument: input.instrument, notionalQuantity4dp: input.notionalQuantity4dp, strikePrice4dp: input.strikePrice4dp, capPrice4dp: input.capPrice4dp ?? null, expiry: input.expiry, estimatedPremiumMinor: input.estimatedPremiumMinor, simulatedCounterparty: `${input.simulatedCounterparty} · simulated`, expectedClaimsBeforeMinor: boundary.expectedClaimsMinor, expectedPayoffMinor, residualExposureMinor: boundary.residualExposureMinor, effectivenessBps, reserveUseAfterMinor: boundary.reserveUseMinor, capitalImpactMinor: input.estimatedPremiumMinor + boundary.reserveUseMinor, rationale: input.rationale, evidenceIds: [...new Set([input.snapshot.snapshotId, ...input.evidenceIds, ...input.stresses.map(({ stressId }) => stressId)])], state: "PENDING_APPROVAL", executionBoundary: "SIMULATION_ONLY" };
}

export function approvePaperHedge(recommendation: PaperHedgeRecommendation, input: Readonly<{ approvalId: string; initiatedBy: string; approvedBy: string; assurance: "STEP_UP"; assuranceAt: string; approvedAt: string; reason: string }>): PaperHedgeApproval {
  const assuranceAge = Date.parse(input.approvedAt) - Date.parse(input.assuranceAt);
  if (!input.approvalId.trim() || input.initiatedBy === input.approvedBy || !input.initiatedBy.trim() || !input.approvedBy.trim()) throw new Error("Paper hedge approval requires different RT principals.");
  if (input.assurance !== "STEP_UP" || !Number.isFinite(assuranceAge) || assuranceAge < 0 || assuranceAge > 300_000) throw new Error("Fresh step-up assurance is required.");
  if (!input.reason.trim() || recommendation.executionBoundary !== "SIMULATION_ONLY") throw new Error("Approval reason and simulation-only boundary are required.");
  return { approvalId: input.approvalId, recommendationId: recommendation.recommendationId, recommendationVersion: recommendation.version, exposureSnapshotId: recommendation.exposureSnapshotId, initiatedBy: input.initiatedBy, approvedBy: input.approvedBy, assurance: input.assurance, assuranceAt: input.assuranceAt, approvedAt: input.approvedAt, reason: input.reason, state: "APPROVED" };
}

export function executePaperHedge(recommendation: PaperHedgeRecommendation, approval: PaperHedgeApproval, input: Readonly<{ executionId: string; executedBy: string; executedAt: string }>): SimulatedHedgeExecution {
  if (approval.recommendationId !== recommendation.recommendationId || approval.recommendationVersion !== recommendation.version || approval.exposureSnapshotId !== recommendation.exposureSnapshotId || approval.state !== "APPROVED") throw new Error("Execution requires approval pinned to this recommendation and snapshot.");
  if (!input.executionId.trim() || !input.executedBy.trim() || Date.parse(input.executedAt) < Date.parse(approval.approvedAt)) throw new Error("Valid simulated execution identity and time are required.");
  return { executionId: input.executionId, recommendationId: recommendation.recommendationId, recommendationVersion: recommendation.version, exposureSnapshotId: recommendation.exposureSnapshotId, executionType: "SIMULATED", instrument: recommendation.instrument, quantity4dp: recommendation.notionalQuantity4dp, premiumMinor: recommendation.estimatedPremiumMinor, counterparty: recommendation.simulatedCounterparty, initiatedBy: approval.initiatedBy, approvedBy: approval.approvedBy, executedBy: input.executedBy, executedAt: input.executedAt, liveAdapterCallable: false, moneyMovementMinor: 0, auditEvidenceIds: [...recommendation.evidenceIds, approval.approvalId] };
}
