import { describe, expect, it } from "vitest";
import { createExposureSnapshot, type AcceptedPosition } from "./index";
import { approvePoolScenario, createPoolRollForward, projectPoolScenario, publishPoolScenario, rejectIneligiblePoolSource, type PoolMovement, type PoolScenario } from "./pool";

const movement = (category: PoolMovement["category"], amountMinor: number, index: number): PoolMovement => ({ movementId: `MOV-${index}`, organisationId: "ORG-1", legalEntityId: "LE-US", currency: "USD", category, amountMinor, occurredAt: "2026-08-27T10:00:00Z", sourceId: `SRC-${index}`, ledgerJournalId: `JRN-${index}`, simulated: true });
const movements = [movement("COST_FUNDING", 91, 1), movement("BUFFER_CONTRIBUTION", 21, 2), movement("CLAIM_UTILISATION", 450, 3), movement("HEDGE_PREMIUM", 50, 4), movement("HEDGE_RECOVERY", 200, 5)];
const rollForward = (ledgerClosingBalanceMinor = 812) => createPoolRollForward({ rollForwardId: "POOL-RF-1", organisationId: "ORG-1", legalEntityId: "LE-US", currency: "USD", periodStart: "2026-08-27T00:00:00Z", periodEnd: "2026-08-28T00:00:00Z", openingBalanceMinor: 1_000, movements, ledgerClosingBalanceMinor });
const position: AcceptedPosition = { positionId: "POS-1", organisationId: "ORG-1", legalEntityId: "LE-US", status: "ACCEPTED", remainingQuantity4dp: 100_000_000, market: "US-TX", grade: "REGULAR", geography: "TX", currency: "USD", strikePrice4dp: 36_750, boundaryPrice4dp: 40_250, expiry: "2026-09-01", customerId: "CUS-1", fleetId: null, basisRiskCategory: "RETAIL_WHOLESALE", expectedClaimMinor: 700, priceDecisionVersion: "price@1", spreadDecisionVersion: "spread@1", fxDecisionVersion: "fx@1", rulesVersion: "rules@1" };
const snapshot = () => createExposureSnapshot({ snapshotId: "EXP-1", organisationId: "ORG-1", legalEntityId: "LE-US", currency: "USD", asOf: "2026-08-27", reserveAvailableMinor: 812, reconciliationStatus: "PASS", positions: [position] });
const draft: PoolScenario = { scenarioId: "POOL-SCEN-1", version: 2, name: "Claims shock", state: "DRAFT", makerId: "rt-maker", checkerId: null, assumptionVersion: "pool-assumptions@2", costFundingChangeBps: 0, bufferChangeBps: 0, claimChangeBps: 5000, hedgeRecoveryChangeBps: -5000, transferInMinor: 0, transferOutMinor: 0, effectiveFrom: "2026-08-27T12:00:00Z" };
const published = () => publishPoolScenario(approvePoolScenario(draft, "rt-checker"));

describe("reserve and risk-pool administration", () => {
  it("rolls forward each economic line without silent netting", () => expect(rollForward()).toMatchObject({ openingBalanceMinor: 1000, costFundingMinor: 91, bufferContributionMinor: 21, claimUtilisationMinor: 450, hedgePremiumMinor: 50, hedgeRecoveryMinor: 200, closingBalanceMinor: 812 }));
  it("never includes margin or customer money as pool capacity", () => { expect(rollForward()).toMatchObject({ marginIncludedMinor: 0, customerMoneyIncludedMinor: 0 }); for (const source of ["CUSTOMER_AVAILABLE", "CUSTOMER_RESERVED", "CUSTOMER_REFUND_PAYABLE", "MARGIN_REVENUE"] as const) expect(() => rejectIneligiblePoolSource(source)).toThrow(/cannot be classified/); });
  it("pins every movement to ledger lineage", () => expect(rollForward()).toMatchObject({ movementIds: ["MOV-1", "MOV-2", "MOV-3", "MOV-4", "MOV-5"], journalIds: ["JRN-1", "JRN-2", "JRN-3", "JRN-4", "JRN-5"] }));
  it("surfaces rather than plugs ledger reconciliation breaks", () => expect(rollForward(800)).toMatchObject({ reconciliationStatus: "BREAK", differenceMinor: 12 }));
  it("rejects cross-tenant pool movements", () => expect(() => createPoolRollForward({ rollForwardId: "R", organisationId: "ORG-1", legalEntityId: "LE-US", currency: "USD", periodStart: "2026-08-27", periodEnd: "2026-08-28", openingBalanceMinor: 0, movements: [{ ...movements[0]!, organisationId: "ORG-2" }], ledgerClosingBalanceMinor: 91 })).toThrow(/Cross-tenant/));
  it("requires a different checker before scenario publication", () => { expect(published().state).toBe("PUBLISHED"); expect(() => approvePoolScenario(draft, "rt-maker")).toThrow(/different checker/); expect(() => publishPoolScenario(draft)).toThrow(/approved/); });
  it("pins scenario and assumption versions to projections", () => expect(projectPoolScenario(rollForward(), snapshot(), published(), { minimumCoverageBps: 10_000, warningCoverageBps: 12_500 })).toMatchObject({ scenarioId: "POOL-SCEN-1", scenarioVersion: 2, rollForwardId: "POOL-RF-1", exposureSnapshotId: "EXP-1", simulated: true }));
  it("projects stressed claims and hedge recovery separately", () => expect(projectPoolScenario(rollForward(), snapshot(), published(), { minimumCoverageBps: 10_000, warningCoverageBps: 12_500 })).toMatchObject({ projectedClaimsMinor: 675, projectedHedgeRecoveryMinor: 100 }));
  it("classifies inadequate coverage as critical", () => expect(projectPoolScenario(rollForward(), snapshot(), published(), { minimumCoverageBps: 15_000, warningCoverageBps: 20_000 }).status).toBe("CRITICAL"));
  it("blocks scenario projection on reconciliation breaks", () => expect(() => projectPoolScenario(rollForward(800), snapshot(), published(), { minimumCoverageBps: 10_000, warningCoverageBps: 12_500 })).toThrow(/reconciled/));
});
