import { describe, expect, it } from "vitest";
import { approveEuBenchmarkConfiguration, assessEuBenchmarkMonitoring, assessOfficialSourceEvidence, createEuBenchmarkConfiguration, createEuBenchmarkRelease, createSyntheticBulletinWorkbook, EU_COUNTRIES, EU_CURRENCY_BY_COUNTRY, officialWeeklyBulletinGate2Decision, officialWeeklyBulletinGate2Evidence, parseEuWeeklyBulletinFixture, publishEuBenchmarkConfiguration, REQUIRED_HEADERS, rollbackEuBenchmarkRelease, seededEuBenchmarkConfiguration, seededEuBenchmarkMonitoring, seededEuBenchmarkRelease, syntheticEuWeeklyBulletin, syntheticEuWeeklyBulletinDecision } from "./index";

describe("P7-001 offline EU Weekly Oil Bulletin contract", () => {
  it("reconciles exactly 27 countries and four rows per country", () => expect(syntheticEuWeeklyBulletinDecision).toMatchObject({ disposition: "ACCEPTED", countryCount: 27, rowCount: 108 }));
  it("emits national and EUR benchmark presentations only", () => { expect(syntheticEuWeeklyBulletinDecision.observations).toHaveLength(216); expect(new Set(syntheticEuWeeklyBulletinDecision.observations.map(({presentation})=>presentation))).toEqual(new Set(["NATIONAL","EUR"])); expect(syntheticEuWeeklyBulletinDecision.observations.every(({quoteEligible,settlementEligible,permittedUses})=>!quoteEligible && !settlementEligible && permittedUses.join() === "DISPLAY,SIMULATE")).toBe(true); });
  it("models 21 EUR and six non-EUR member states for 2026", () => { expect(EU_COUNTRIES.filter((country)=>EU_CURRENCY_BY_COUNTRY[country] === "EUR")).toHaveLength(21); expect(EU_COUNTRIES.filter((country)=>EU_CURRENCY_BY_COUNTRY[country] !== "EUR")).toHaveLength(6); expect(EU_CURRENCY_BY_COUNTRY.BG).toBe("EUR"); });
  it("retains country-level provenance and row lineage", () => expect(syntheticEuWeeklyBulletinDecision.observations.every(({geographicScope,provenance,rowLineage})=>geographicScope === "COUNTRY" && provenance === "OFFICIAL_BENCHMARK_FIXTURE" && rowLineage.startsWith("rows["))).toBe(true));
  it("fails closed on exact header/schema drift", () => { const result = parseEuWeeklyBulletinFixture(createSyntheticBulletinWorkbook({ headers: [...REQUIRED_HEADERS,"unexpected"] }), "2026-08-27T12:00:00Z"); expect(result.disposition).toBe("QUARANTINED"); expect(result.issues[0]?.code).toBe("SCHEMA_DRIFT"); });
  it("quarantines missing country coverage", () => { const result = parseEuWeeklyBulletinFixture(createSyntheticBulletinWorkbook({ rows: syntheticEuWeeklyBulletin.rows.filter(({country})=>country !== "SE") }), "2026-08-27T12:00:00Z"); expect(result.issues.map(({code})=>code)).toContain("COUNTRY_COVERAGE"); });
  it("quarantines duplicate rows", () => { const result = parseEuWeeklyBulletinFixture(createSyntheticBulletinWorkbook({ rows: [...syntheticEuWeeklyBulletin.rows, syntheticEuWeeklyBulletin.rows[0]!] }), "2026-08-27T12:00:00Z"); expect(result.issues.map(({code})=>code)).toContain("DUPLICATE_ROW"); });
  it("quarantines invalid country currency and price precision storage", () => { const rows = syntheticEuWeeklyBulletin.rows.map((row,index)=>index ? row : { ...row, nationalCurrency: "CZK" as const, nationalPricePer1000LMinor4: 0 }); const result = parseEuWeeklyBulletinFixture(createSyntheticBulletinWorkbook({ rows }), "2026-08-27T12:00:00Z"); expect(result.issues.map(({code})=>code)).toContain("VALUE_INVALID"); });
  it("quarantines future and stale releases using the injected clock", () => { expect(parseEuWeeklyBulletinFixture(syntheticEuWeeklyBulletin, "2026-08-26T00:00:00Z").issues.map(({code})=>code)).toContain("FUTURE_RELEASE"); expect(parseEuWeeklyBulletinFixture(syntheticEuWeeklyBulletin, "2026-09-10T00:00:00Z").issues.map(({code})=>code)).toContain("STALE"); });
  it("accepts only explicit corrections of a known distinct hash", () => { const correction = createSyntheticBulletinWorkbook({ fileHash: "sha256:synthetic-eu-wob-2026-08-24-v2", supersedesFileHash: syntheticEuWeeklyBulletin.fileHash }); expect(parseEuWeeklyBulletinFixture(correction, "2026-08-27T12:00:00Z", new Set([syntheticEuWeeklyBulletin.fileHash])).disposition).toBe("CORRECTION"); expect(parseEuWeeklyBulletinFixture(correction, "2026-08-27T12:00:00Z").issues.map(({code})=>code)).toContain("CORRECTION_INVALID"); });
  it("rejects malformed workbook hashes", () => expect(parseEuWeeklyBulletinFixture(createSyntheticBulletinWorkbook({ fileHash: "sha256:" }), "2026-08-27T12:00:00Z").issues.map(({code})=>code)).toContain("HASH_INVALID"));
  it("contains no network location or station identifier", () => { expect(JSON.stringify(syntheticEuWeeklyBulletin)).not.toMatch(/https?:\/\//); expect(JSON.stringify(syntheticEuWeeklyBulletinDecision.observations)).not.toMatch(/station/i); });
});

describe("P7-001 read-only official-source evidence", () => {
  it("records both official workbooks as immutable evidence", () => { expect(officialWeeklyBulletinGate2Decision).toMatchObject({ status: "EVIDENCE_ACCEPTED", issues: [] }); expect(officialWeeklyBulletinGate2Decision.evidence).toHaveLength(2); expect(new Set(officialWeeklyBulletinGate2Decision.evidence.map(({kind})=>kind))).toEqual(new Set(["WITH_TAXES","WITHOUT_TAXES"])); });
  it("pins acquisition to Commission HTTPS document endpoints", () => expect(officialWeeklyBulletinGate2Evidence.every(({sourceUrl})=>{ const url = new URL(sourceUrl); return url.protocol === "https:" && url.hostname === "energy.ec.europa.eu" && url.pathname.startsWith("/document/download/"); })).toBe(true));
  it("retains observed hashes and single-sheet XLSX structure", () => expect(officialWeeklyBulletinGate2Evidence.every(({sha256,containerMagic,worksheetNames,contentLength})=>/^sha256:[a-f0-9]{64}$/.test(sha256) && containerMagic === "PK\u0003\u0004" && worksheetNames.join() === "Sheet1" && contentLength > 0)).toBe(true));
  it("keeps reuse evidence pending checker approval", () => expect(officialWeeklyBulletinGate2Evidence.every(({licenceEvidence,licenceApproval})=>licenceEvidence === "EC_LEGAL_NOTICE_CC_BY_4_UNLESS_OTHERWISE_INDICATED" && licenceApproval === "PENDING_CHECKER")).toBe(true));
  it("prohibits publication, quoting and settlement", () => expect(officialWeeklyBulletinGate2Evidence.every(({permittedUses,publicationEligible,quoteEligible,settlementEligible})=>permittedUses.join() === "EVIDENCE_REVIEW" && !publicationEligible && !quoteEligible && !settlementEligible)).toBe(true));
  it("fails closed on unapproved hosts", () => { const evidence = officialWeeklyBulletinGate2Evidence.map((item,index)=>index ? item : { ...item, sourceUrl: "https://example.com/workbook.xlsx" as const }); expect(assessOfficialSourceEvidence(evidence)).toMatchObject({ status: "EVIDENCE_REJECTED", evidence: [] }); });
  it("fails closed on workbook structure drift", () => { const evidence = officialWeeklyBulletinGate2Evidence.map((item,index)=>index ? item : { ...item, worksheetNames: ["Changed"] as unknown as readonly ["Sheet1"] }); expect(assessOfficialSourceEvidence(evidence).issues).toContain("WITH_TAXES: workbook structure drifted from the observed single-sheet shape."); });
  it("rejects any eligibility escalation", () => { const evidence = officialWeeklyBulletinGate2Evidence.map((item,index)=>index ? item : { ...item, publicationEligible: true as false }); expect(assessOfficialSourceEvidence(evidence).issues).toContain("WITH_TAXES: Gate 2 evidence exceeded its permitted-use boundary."); });
});

describe("P7-001 governed synthetic benchmark publication", () => {
  const input = { configurationId: "CONFIG-TEST", version: 1, makerId: "maker", sourceEvidenceHashes: officialWeeklyBulletinGate2Evidence.map(({sha256})=>sha256), countries: EU_COUNTRIES, products: ["PETROL_95","ROAD_DIESEL"] as const, taxBases: ["WITH_TAXES","WITHOUT_TAXES"] as const, licenceApproval: "CHECKER_APPROVED" as const, attribution: "European Commission with FuelCap synthetic transformation disclosure.", freshnessCurrentDays: 10 as const, freshnessExpiredDays: 17 as const, rollbackReference: "RB-1", evidenceDigest: "sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" as const, requestedAt: "2026-08-27T09:00:00Z", supersedesConfigurationId: null };
  const pending = () => createEuBenchmarkConfiguration(input);
  const approved = () => approveEuBenchmarkConfiguration(pending(), { checkerId: "checker", assurance: "STEP_UP", evidenceDigest: input.evidenceDigest, approvedAt: "2026-08-27T09:01:00Z" });
  it("publishes only a complete differently checked configuration", () => { expect(publishEuBenchmarkConfiguration(approved(), "2026-08-27T09:02:00Z").state).toBe("PUBLISHED"); expect(()=>approveEuBenchmarkConfiguration(pending(), { checkerId: "maker", assurance: "STEP_UP", evidenceDigest: input.evidenceDigest, approvedAt: "2026-08-27T09:01:00Z" })).toThrow(/different checker/); });
  it("binds approval to the exact evidence digest", () => expect(()=>approveEuBenchmarkConfiguration(pending(), { checkerId: "checker", assurance: "STEP_UP", evidenceDigest: "changed", approvedAt: "2026-08-27T09:01:00Z" })).toThrow(/exact evidence/));
  it("creates a display-and-simulate-only synthetic release", () => expect(seededEuBenchmarkRelease).toMatchObject({ state: "PUBLISHED", health: "CURRENT", observationCount: 216, countryCount: 27, quoteEligible: false, settlementEligible: false, permittedUses: ["DISPLAY","SIMULATE"] }));
  it("quarantines rejected parser decisions without observations", () => { const bad = parseEuWeeklyBulletinFixture(createSyntheticBulletinWorkbook({ rows: [] }), "2026-08-27T12:00:00Z"); expect(createEuBenchmarkRelease(seededEuBenchmarkConfiguration, bad, {releaseId:"BAD",ingestedAt:"2026-08-27T12:01:00Z"})).toMatchObject({state:"QUARANTINED",observationCount:0}); });
  it("classifies current, stale and expired releases with an injected clock", () => { expect(assessEuBenchmarkMonitoring([seededEuBenchmarkRelease], "2026-09-07T00:00:01Z")).toMatchObject({current:0,stale:1,publicationHealthy:false}); expect(assessEuBenchmarkMonitoring([seededEuBenchmarkRelease], "2026-09-11T00:00:01Z")).toMatchObject({expired:1,activeReleaseId:null}); });
  it("raises quarantine alerts and blocks healthy publication", () => { const bad = createEuBenchmarkRelease(seededEuBenchmarkConfiguration, { disposition:"QUARANTINED",issues:[{code:"SCHEMA_DRIFT",detail:"test"}],observations:[],countryCount:0,rowCount:0 }, {releaseId:"BAD",ingestedAt:"2026-08-27T12:00:00Z"}); expect(assessEuBenchmarkMonitoring([seededEuBenchmarkRelease,bad], "2026-08-27T20:24:00Z")).toMatchObject({quarantined:1,publicationHealthy:false,alerts:["QUARANTINE_REVIEW_REQUIRED"]}); });
  it("requires different principals and evidence for rollback", () => { expect(rollbackEuBenchmarkRelease(seededEuBenchmarkRelease,{makerId:"maker",checkerId:"checker",rollbackReference:"INC-1",rolledBackAt:"2026-08-27T21:00:00Z"}).state).toBe("ROLLED_BACK"); expect(()=>rollbackEuBenchmarkRelease(seededEuBenchmarkRelease,{makerId:"maker",checkerId:"maker",rollbackReference:"INC-1",rolledBackAt:"2026-08-27T21:00:00Z"})).toThrow(/different principals/); });
  it("provides a healthy deterministic seeded monitoring state", () => expect(seededEuBenchmarkMonitoring).toMatchObject({current:1,stale:0,expired:0,quarantined:0,activeReleaseId:"EU-BENCHMARK-2026-08-24-V1",publicationHealthy:true}));
});
