import { describe, expect, it } from "vitest";
import { createSyntheticBulletinWorkbook, EU_COUNTRIES, EU_CURRENCY_BY_COUNTRY, parseEuWeeklyBulletinFixture, REQUIRED_HEADERS, syntheticEuWeeklyBulletin, syntheticEuWeeklyBulletinDecision } from "./index";

describe("P7-001 offline EU Weekly Oil Bulletin contract", () => {
  it("reconciles exactly 27 countries and four rows per country", () => expect(syntheticEuWeeklyBulletinDecision).toMatchObject({ disposition: "ACCEPTED", countryCount: 27, rowCount: 108 }));
  it("emits national and EUR benchmark presentations only", () => { expect(syntheticEuWeeklyBulletinDecision.observations).toHaveLength(216); expect(new Set(syntheticEuWeeklyBulletinDecision.observations.map(({presentation})=>presentation))).toEqual(new Set(["NATIONAL","EUR"])); expect(syntheticEuWeeklyBulletinDecision.observations.every(({quoteEligible,settlementEligible,permittedUses})=>!quoteEligible && !settlementEligible && permittedUses.join() === "DISPLAY,SIMULATE")).toBe(true); });
  it("models 21 EUR and six non-EUR member states for 2026", () => { expect(EU_COUNTRIES.filter((country)=>EU_CURRENCY_BY_COUNTRY[country] === "EUR")).toHaveLength(21); expect(EU_COUNTRIES.filter((country)=>EU_CURRENCY_BY_COUNTRY[country] !== "EUR")).toHaveLength(6); expect(EU_CURRENCY_BY_COUNTRY.BG).toBe("EUR"); });
  it("retains country-level provenance and row lineage", () => expect(syntheticEuWeeklyBulletinDecision.observations.every(({geographicScope,provenance,rowLineage})=>geographicScope === "COUNTRY" && provenance === "OFFICIAL_BENCHMARK_FIXTURE" && rowLineage.startsWith("rows["))).toBe(true));
  it("fails closed on exact header/schema drift", () => { const result = parseEuWeeklyBulletinFixture(createSyntheticBulletinWorkbook({ headers: [...REQUIRED_HEADERS,"unexpected"] }), "2026-08-27T12:00:00Z"); expect(result.disposition).toBe("QUARANTINED"); expect(result.issues[0]?.code).toBe("SCHEMA_DRIFT"); });
  it("quarantines missing country coverage", () => { const result = parseEuWeeklyBulletinFixture(createSyntheticBulletinWorkbook({ rows: syntheticEuWeeklyBulletin.rows.filter(({country})=>country !== "SE") }), "2026-08-27T12:00:00Z"); expect(result.issues.map(({code})=>code)).toContain("COUNTRY_COVERAGE"); });
  it("quarantines duplicate rows", () => { const result = parseEuWeeklyBulletinFixture(createSyntheticBulletinWorkbook({ rows: [...syntheticEuWeeklyBulletin.rows, syntheticEuWeeklyBulletin.rows[0]!] }), "2026-08-27T12:00:00Z"); expect(result.issues.map(({code})=>code)).toContain("DUPLICATE_ROW"); });
  it("quarantines invalid country currency and price precision storage", () => { const rows = syntheticEuWeeklyBulletin.rows.map((row,index)=>index ? row : { ...row, nationalCurrency: "CZK" as const, nationalPricePer1000LMinor4: 0 }); const result = parseEuWeeklyBulletinFixture(createSyntheticBulletinWorkbook({ rows }), "2026-08-27T12:00:00Z"); expect(result.issues.map(({code})=>code)).toContain("VALUE_INVALID"); });
  it("quarantines future and stale releases using the injected clock", () => { expect(parseEuWeeklyBulletinFixture(syntheticEuWeeklyBulletin, "2026-08-26T00:00:00Z").issues.map(({code})=>code)).toContain("FUTURE_RELEASE"); expect(parseEuWeeklyBulletinFixture(syntheticEuWeeklyBulletin, "2026-09-10T00:00:00Z").issues.map(({code})=>code)).toContain("STALE"); });
  it("accepts only explicit corrections of a known distinct hash", () => { const correction = createSyntheticBulletinWorkbook({ fileHash: "sha256:synthetic-eu-wob-2026-08-24-v2", supersedesFileHash: syntheticEuWeeklyBulletin.fileHash }); expect(parseEuWeeklyBulletinFixture(correction, "2026-08-27T12:00:00Z", new Set([syntheticEuWeeklyBulletin.fileHash])).disposition).toBe("CORRECTION"); expect(parseEuWeeklyBulletinFixture(correction, "2026-08-27T12:00:00Z").issues.map(({code})=>code)).toContain("CORRECTION_INVALID"); });
  it("rejects malformed workbook hashes", () => expect(parseEuWeeklyBulletinFixture(createSyntheticBulletinWorkbook({ fileHash: "sha256:" }), "2026-08-27T12:00:00Z").issues.map(({code})=>code)).toContain("HASH_INVALID"));
  it("contains no network location or station identifier", () => { expect(JSON.stringify(syntheticEuWeeklyBulletin)).not.toMatch(/https?:\/\//); expect(JSON.stringify(syntheticEuWeeklyBulletinDecision.observations)).not.toMatch(/station/i); });
});
