import { describe, expect, it } from "vitest";
import { CardAuthorizationClearingSimulator, type AuthorizeCardCommand, type CardProfile, type ClearCardCommand } from "./index";

const card: CardProfile = { cardId: "CARD-1", customerId: "CUSTOMER-1", walletId: "WALLET-1", organisationId: "ORG-1", currency: "USD", status: "ACTIVE", allowedMerchantCategoryCodes: ["5541", "5542"], transactionLimitMinor: 15_000, dailyLimitMinor: 20_000 };
const merchant = { merchantId: "STATION-1", merchantName: "Demo Fuel", merchantCategoryCode: "5541", countryCode: "US" } as const;
const authorization: AuthorizeCardCommand = { commandId: "CMD-A1", idempotencyKey: "auth:1", authorizationId: "AUTH-1", cardId: "CARD-1", amountMinor: 8_000, currency: "USD", merchant, availableValueMinor: 10_000, occurredAt: "2026-08-27T07:00:00.000Z", correlationId: "CORR-1", mode: "SIMULATED" };
const clearing: ClearCardCommand = { commandId: "CMD-C1", idempotencyKey: "clear:1", clearingId: "CLEAR-1", authorizationId: "AUTH-1", providerReference: "SIM-PRESENTMENT-1", amountMinor: 6_800, currency: "USD", clearedAt: "2026-08-27T08:00:00.000Z", mode: "SIMULATED" };
const simulator = (profile: CardProfile = card) => new CardAuthorizationClearingSimulator([profile]);

describe("card authorization simulator", () => {
  it("approves an eligible simulated fuel authorization and creates an outstanding hold", () => expect(simulator().authorize(authorization)).toMatchObject({ outcome: "APPROVED", reason: "APPROVED", status: "OPEN", outstandingMinor: 8_000, mode: "SIMULATED" }));
  it("replays an identical authorization idempotently", () => { const service = simulator(); const first = service.authorize(authorization); expect(service.authorize(authorization)).toEqual(first); });
  it("rejects idempotency-key reuse with changed authorization parameters", () => { const service = simulator(); service.authorize(authorization); expect(() => service.authorize({ ...authorization, amountMinor: 7_999 })).toThrow(/different command/i); });
  it("hard-blocks live authorization", () => expect(() => simulator().authorize({ ...authorization, mode: "LIVE" })).toThrow(/Phase 6/i));
  it("declines frozen cards and disallowed merchant categories", () => { expect(simulator({ ...card, status: "FROZEN" }).authorize(authorization).reason).toBe("CARD_NOT_ACTIVE"); expect(simulator().authorize({ ...authorization, merchant: { ...merchant, merchantCategoryCode: "5812" } }).reason).toBe("MERCHANT_CATEGORY_NOT_ALLOWED"); });
  it("declines transaction and daily limit excess deterministically", () => { expect(simulator().authorize({ ...authorization, amountMinor: 15_001, availableValueMinor: 30_000 }).reason).toBe("TRANSACTION_LIMIT_EXCEEDED"); const service = simulator(); service.authorize({ ...authorization, amountMinor: 11_000, availableValueMinor: 30_000 }); expect(service.authorize({ ...authorization, commandId: "CMD-A2", idempotencyKey: "auth:2", authorizationId: "AUTH-2", amountMinor: 10_000, availableValueMinor: 30_000 }).reason).toBe("DAILY_LIMIT_EXCEEDED"); });
  it("accounts for existing open holds when checking available value", () => { const service = simulator(); service.authorize(authorization); expect(service.authorize({ ...authorization, commandId: "CMD-A2", idempotencyKey: "auth:2", authorizationId: "AUTH-2", amountMinor: 3_000 }).reason).toBe("INSUFFICIENT_AVAILABLE_VALUE"); });
});

describe("card clearing simulator", () => {
  it("accepts a matched partial clearing and emits a downstream instruction without posting a ledger", () => { const service = simulator(); service.authorize(authorization); expect(service.clear(clearing).status).toBe("ACCEPTED"); expect(service.getAuthorization("AUTH-1")).toMatchObject({ status: "PARTIALLY_CLEARED", clearedMinor: 6_800, outstandingMinor: 1_200 }); expect(service.listClearingInstructions()).toEqual([expect.objectContaining({ eventType: "CARD_CLEARING_ACCEPTED", amountMinor: 6_800, walletId: "WALLET-1" })]); });
  it("supports multiple presentments up to the authorized amount", () => { const service = simulator(); service.authorize(authorization); service.clear({ ...clearing, amountMinor: 6_000 }); service.clear({ ...clearing, commandId: "CMD-C2", idempotencyKey: "clear:2", clearingId: "CLEAR-2", providerReference: "SIM-PRESENTMENT-2", amountMinor: 2_000 }); expect(service.getAuthorization("AUTH-1")).toMatchObject({ status: "CLEARED", outstandingMinor: 0, clearedMinor: 8_000 }); expect(service.listClearingInstructions()).toHaveLength(2); });
  it("deduplicates a clearing and never emits a second instruction", () => { const service = simulator(); service.authorize(authorization); const first = service.clear(clearing); expect(service.clear(clearing)).toEqual(first); expect(service.listClearingInstructions()).toHaveLength(1); });
  it("routes missing and mismatched clearing records to the break queue", () => { const missing = simulator(); expect(missing.clear(clearing)).toMatchObject({ status: "BREAK", reason: "AUTHORIZATION_NOT_FOUND" }); expect(missing.listReconciliationBreaks()).toHaveLength(1); const excessive = simulator(); excessive.authorize(authorization); expect(excessive.clear({ ...clearing, amountMinor: 8_001 })).toMatchObject({ status: "BREAK", reason: "AMOUNT_EXCEEDS_AUTHORIZATION" }); expect(excessive.listClearingInstructions()).toHaveLength(0); });
  it("releases only the uncleared remainder through an immutable reversal", () => { const service = simulator(); service.authorize(authorization); service.clear(clearing); const reversal = service.reverse({ commandId: "CMD-R1", idempotencyKey: "reverse:1", reversalId: "REV-1", authorizationId: "AUTH-1", reason: "Final amount received", reversedAt: "2026-08-27T08:05:00.000Z", mode: "SIMULATED" }); expect(reversal.releasedMinor).toBe(1_200); expect(service.getAuthorization("AUTH-1")).toMatchObject({ status: "REVERSED", clearedMinor: 6_800, releasedMinor: 1_200, outstandingMinor: 0 }); });
  it("does not permit clearing after reversal", () => { const service = simulator(); service.authorize(authorization); service.reverse({ commandId: "CMD-R1", idempotencyKey: "reverse:1", reversalId: "REV-1", authorizationId: "AUTH-1", reason: "Voided", reversedAt: "2026-08-27T08:05:00.000Z", mode: "SIMULATED" }); expect(service.clear(clearing)).toMatchObject({ status: "BREAK", reason: "AUTHORIZATION_NOT_OPEN" }); });
  it("hard-blocks live clearing and reversal commands", () => { const service = simulator(); service.authorize(authorization); expect(() => service.clear({ ...clearing, mode: "LIVE" })).toThrow(/Phase 6/i); expect(() => service.reverse({ commandId: "CMD-R1", idempotencyKey: "reverse:1", reversalId: "REV-1", authorizationId: "AUTH-1", reason: "Void", reversedAt: "2026-08-27T08:05:00.000Z", mode: "LIVE" })).toThrow(/Phase 6/i); });
});
