export const PRICING_CONTROL_VERSION = "pricing-control@1.0.0" as const;
export type PricingEngineSnapshot = Readonly<{ snapshotId: string; scenarioVersion: string; observedAt: string; evidenceReferences: readonly string[]; ingestion: Readonly<{ version: string; acceptedCount: number; quarantinedCount: number; freshestAgeSeconds: number; maximumAgeSeconds: number }>; benchmark: Readonly<{ version: string; decisionId: string; status: "PUBLISHED" | "BLOCKED"; coverageBps: number; minimumCoverageBps: number; dispersionBps: number | null; maximumDispersionBps: number }>; quote: Readonly<{ version: string; status: "QUOTED" | "UNAVAILABLE" | "INELIGIBLE"; reasonCode: string }>; spread: Readonly<{ version: string; componentTotalBps: number; publishedTotalBps: number }>; fx: Readonly<{ version: string; valid: boolean; stalePairCount: number }>; rules: Readonly<{ version: string; validationPassed: boolean; regressionPassed: boolean }> }>;
export type ControlCheck = Readonly<{ checkId: "FRESHNESS" | "COVERAGE" | "DISPERSION" | "QUOTE" | "SPREAD_RECONCILIATION" | "FX_VALIDITY" | "RULES_GATES"; status: "PASS" | "WARN" | "BLOCK"; reasonCode: string; evidenceReferences: readonly string[] }>;
export type PricingControlAssessment = Readonly<{ assessmentId: string; assessmentVersion: typeof PRICING_CONTROL_VERSION; snapshotId: string; state: "HEALTHY" | "DEGRADED" | "QUOTE_STOPPED"; quotePermitted: boolean; checks: readonly ControlCheck[]; blockingReasonCodes: readonly string[]; evaluatedAt: string }>;
export type PricingRecommendationDraft = Readonly<{ recommendationId: string; summary: string; proposedAction: "KEEP_CURRENT" | "DRAFT_SOURCE_CHANGE" | "DRAFT_SPREAD_CHANGE" | "ESCALATE_INCIDENT"; confidenceBps: number; citations: readonly string[]; modelVersion: string; untrustedContext?: string | null }>;
export type GovernedPricingRecommendation = Readonly<{ recommendationId: string; status: "SUPPORTED" | "VERIFY" | "ABSTAIN" | "BLOCKED"; summary: string; proposedAction: PricingRecommendationDraft["proposedAction"] | null; confidenceBps: number; citations: readonly string[]; reasonCodes: readonly string[]; actionEnvelope: "READ_ONLY_OR_DRAFT"; humanApprovalRequired: true; autonomousPublication: false; assessmentId: string; modelVersion: string }>;
const injectionPatterns = [/ignore\s+(all|previous)\s+instructions/i, /system\s+prompt/i, /override\s+(policy|controls?)/i, /publish\s+without\s+approval/i];
const evidenceFor = (snapshot: PricingEngineSnapshot, ...extra: string[]) => [...new Set([...snapshot.evidenceReferences, ...extra])];
export function assessPricingControl(assessmentId: string, snapshot: PricingEngineSnapshot, evaluatedAt: string): PricingControlAssessment {
  if (!assessmentId.trim() || !snapshot.snapshotId.trim() || !Number.isFinite(Date.parse(evaluatedAt)) || Date.parse(evaluatedAt) < Date.parse(snapshot.observedAt)) throw new Error("Assessment identity and clock are invalid.");
  const checks: ControlCheck[] = [
    { checkId: "FRESHNESS", status: snapshot.ingestion.freshestAgeSeconds <= snapshot.ingestion.maximumAgeSeconds ? "PASS" : "BLOCK", reasonCode: snapshot.ingestion.freshestAgeSeconds <= snapshot.ingestion.maximumAgeSeconds ? "OBSERVATIONS_FRESH" : "OBSERVATIONS_STALE", evidenceReferences: evidenceFor(snapshot, snapshot.ingestion.version) },
    { checkId: "COVERAGE", status: snapshot.benchmark.coverageBps >= snapshot.benchmark.minimumCoverageBps ? "PASS" : "BLOCK", reasonCode: snapshot.benchmark.coverageBps >= snapshot.benchmark.minimumCoverageBps ? "COVERAGE_SUFFICIENT" : "COVERAGE_INSUFFICIENT", evidenceReferences: evidenceFor(snapshot, snapshot.benchmark.decisionId) },
    { checkId: "DISPERSION", status: snapshot.benchmark.dispersionBps !== null && snapshot.benchmark.dispersionBps <= snapshot.benchmark.maximumDispersionBps ? "PASS" : "BLOCK", reasonCode: snapshot.benchmark.dispersionBps === null ? "DISPERSION_UNAVAILABLE" : snapshot.benchmark.dispersionBps <= snapshot.benchmark.maximumDispersionBps ? "DISPERSION_WITHIN_LIMIT" : "DISPERSION_EXCESSIVE", evidenceReferences: evidenceFor(snapshot, snapshot.benchmark.decisionId) },
    { checkId: "QUOTE", status: snapshot.benchmark.status === "PUBLISHED" && snapshot.quote.status === "QUOTED" ? "PASS" : "BLOCK", reasonCode: snapshot.benchmark.status === "PUBLISHED" && snapshot.quote.status === "QUOTED" ? "QUOTE_AVAILABLE" : snapshot.quote.reasonCode, evidenceReferences: evidenceFor(snapshot, snapshot.quote.version) },
    { checkId: "SPREAD_RECONCILIATION", status: snapshot.spread.componentTotalBps === snapshot.spread.publishedTotalBps ? "PASS" : "BLOCK", reasonCode: snapshot.spread.componentTotalBps === snapshot.spread.publishedTotalBps ? "SPREAD_COMPONENTS_RECONCILE" : "SPREAD_TOTAL_MISMATCH", evidenceReferences: evidenceFor(snapshot, snapshot.spread.version) },
    { checkId: "FX_VALIDITY", status: snapshot.fx.valid && snapshot.fx.stalePairCount === 0 ? "PASS" : "WARN", reasonCode: snapshot.fx.valid && snapshot.fx.stalePairCount === 0 ? "FX_VALID" : "FX_REVIEW_REQUIRED", evidenceReferences: evidenceFor(snapshot, snapshot.fx.version) },
    { checkId: "RULES_GATES", status: snapshot.rules.validationPassed && snapshot.rules.regressionPassed ? "PASS" : "BLOCK", reasonCode: snapshot.rules.validationPassed && snapshot.rules.regressionPassed ? "RULES_GATES_GREEN" : "RULES_GATES_BLOCKED", evidenceReferences: evidenceFor(snapshot, snapshot.rules.version) },
  ];
  const blockingReasonCodes = checks.filter(({ status }) => status === "BLOCK").map(({ reasonCode }) => reasonCode);
  const state = blockingReasonCodes.length ? "QUOTE_STOPPED" : checks.some(({ status }) => status === "WARN") || snapshot.ingestion.quarantinedCount > 0 ? "DEGRADED" : "HEALTHY";
  return { assessmentId, assessmentVersion: PRICING_CONTROL_VERSION, snapshotId: snapshot.snapshotId, state, quotePermitted: blockingReasonCodes.length === 0, checks, blockingReasonCodes, evaluatedAt };
}
export function governPricingRecommendation(draft: PricingRecommendationDraft, assessment: PricingControlAssessment, snapshot: PricingEngineSnapshot): GovernedPricingRecommendation {
  const base = { recommendationId: draft.recommendationId, summary: draft.summary, confidenceBps: draft.confidenceBps, actionEnvelope: "READ_ONLY_OR_DRAFT" as const, humanApprovalRequired: true as const, autonomousPublication: false as const, assessmentId: assessment.assessmentId, modelVersion: draft.modelVersion };
  if (draft.untrustedContext && injectionPatterns.some((pattern) => pattern.test(draft.untrustedContext!))) return { ...base, status: "BLOCKED", proposedAction: null, citations: [], reasonCodes: ["PROMPT_INJECTION_ISOLATED"] };
  const allowedEvidence = new Set([...snapshot.evidenceReferences, ...assessment.checks.flatMap(({ evidenceReferences }) => evidenceReferences)]);
  const validCitations = [...new Set(draft.citations)].filter((citation) => allowedEvidence.has(citation));
  if (!draft.summary.trim() || draft.confidenceBps < 0 || draft.confidenceBps > 10_000) return { ...base, status: "BLOCKED", proposedAction: null, citations: validCitations, reasonCodes: ["RECOMMENDATION_INVALID"] };
  if (!validCitations.length || validCitations.length !== new Set(draft.citations).size || draft.confidenceBps < 6_000) return { ...base, status: "ABSTAIN", proposedAction: null, citations: validCitations, reasonCodes: [!validCitations.length ? "CITATIONS_REQUIRED" : "EVIDENCE_OR_CONFIDENCE_INSUFFICIENT"] };
  if (assessment.state === "QUOTE_STOPPED" && draft.proposedAction !== "ESCALATE_INCIDENT") return { ...base, status: "BLOCKED", proposedAction: null, citations: validCitations, reasonCodes: ["QUOTE_STOP_REQUIRES_INCIDENT_ESCALATION"] };
  const status = draft.confidenceBps < 8_500 ? "VERIFY" : "SUPPORTED";
  return { ...base, status, proposedAction: draft.proposedAction, citations: validCitations, reasonCodes: status === "VERIFY" ? ["HUMAN_VERIFICATION_REQUIRED"] : ["EVIDENCE_AND_CONFIDENCE_GATES_PASSED"] };
}
