import{describe,expect,it}from"vitest";import{evaluateHedgePortfolio,optimizeSelectiveHedge,publishSelectiveHedgePlan,seededHedgeCandidates,seededHedgeDecision,seededHedgePolicy,seededPublishedHedgePlan}from"./index";
describe("P7-003 selective hedge optimisation",()=>{
it("enumerates every non-empty portfolio",()=>expect(seededHedgeDecision.portfolios).toHaveLength(7));
it("selects the lowest deterministic objective",()=>expect(seededHedgeDecision).toMatchObject({status:"SELECTED",reasonCode:"PORTFOLIO_SELECTED",selectedPortfolioId:"PORTFOLIO-011",simulationOnly:true,executionEligible:false}));
it("pins exposure and basis-model lineage",()=>expect(seededHedgeDecision).toMatchObject({snapshotId:"EXP-TX-0842",basisModelId:"BASIS-MODEL-EU-DE-1"}));
it("rejects excess premium and coverage",()=>expect(evaluateHedgePortfolio({portfolioId:"ALL",candidates:seededHedgeCandidates,acceptedQuantity4dp:500_000_000,stressedExposureMinor:150_000,policy:seededHedgePolicy}).reasonCodes).toEqual(expect.arrayContaining(["PREMIUM_BUDGET_EXCEEDED","OVER_HEDGED"])));
it("rejects weak basis correlation",()=>expect(evaluateHedgePortfolio({portfolioId:"C",candidates:[seededHedgeCandidates[2]!],acceptedQuantity4dp:684_000_000,stressedExposureMinor:150_000,policy:seededHedgePolicy}).reasonCodes).toContain("BASIS_CORRELATION_BELOW_MINIMUM"));
it("rejects concentrated single-counterparty portfolios",()=>expect(evaluateHedgePortfolio({portfolioId:"A",candidates:[seededHedgeCandidates[0]!],acceptedQuantity4dp:684_000_000,stressedExposureMinor:150_000,policy:seededHedgePolicy}).reasonCodes).toContain("COUNTERPARTY_CONCENTRATION_EXCEEDED"));
it("blocks when no portfolio is eligible",()=>expect(optimizeSelectiveHedge({decisionId:"BLOCK",snapshotId:"EXP",basisModelId:"BASIS",acceptedQuantity4dp:684_000_000,stressedExposureMinor:150_000,candidates:seededHedgeCandidates,policy:{...seededHedgePolicy,maximumPremiumMinor:1},decidedAt:"2026-08-28T08:00:00Z"})).toMatchObject({status:"BLOCKED",reasonCode:"NO_ELIGIBLE_PORTFOLIO"}));
it("publishes only a different-checker simulation plan",()=>{expect(seededPublishedHedgePlan).toMatchObject({state:"PUBLISHED",executionType:"SIMULATED",brokerConnected:false,moneyMovement:false});expect(()=>publishSelectiveHedgePlan(seededHedgeDecision,{planId:"P",makerId:"same",checkerId:"same",assurance:"STEP_UP",evidenceDigest:"sha256:ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff",publishedAt:"2026-08-28T08:01:00Z"})).toThrow(/different-checker/);});
});
