export const HEDGE_OPTIMIZER_VERSION="hedge-optimizer@0.1.0" as const;
export type HedgeCandidate=Readonly<{candidateId:string;instrument:"PAPER_CALL"|"PAPER_CALL_SPREAD"|"PAPER_SWAP";market:string;quantity4dp:number;premiumMinor:number;stressPayoffMinor:number;basisCorrelationBps:number;counterparty:string;liquidityScoreBps:number;evidenceIds:readonly string[];simulated:true}>;
export type HedgeOptimizationPolicy=Readonly<{policyId:string;maximumPremiumMinor:number;maximumCoveredQuantity4dp:number;minimumBasisCorrelationBps:number;minimumLiquidityScoreBps:number;maximumCounterpartyConcentrationBps:number;residualWeightBps:number;premiumWeightBps:number;basisPenaltyWeightBps:number}>;
export type HedgePortfolio=Readonly<{portfolioId:string;candidateIds:readonly string[];status:"ELIGIBLE"|"REJECTED";reasonCodes:readonly string[];coveredQuantity4dp:number;coverageBps:number;premiumMinor:number;stressPayoffMinor:number;residualExposureMinor:number;weightedBasisCorrelationBps:number;maximumCounterpartyConcentrationBps:number;objectiveScore:number;evidenceIds:readonly string[]}>;
export type HedgeOptimizationDecision=Readonly<{decisionId:string;version:typeof HEDGE_OPTIMIZER_VERSION;status:"SELECTED"|"BLOCKED";reasonCode:"PORTFOLIO_SELECTED"|"NO_ELIGIBLE_PORTFOLIO"|"INPUT_INVALID";snapshotId:string;basisModelId:string;selectedPortfolioId:string|null;portfolios:readonly HedgePortfolio[];decidedAt:string;simulationOnly:true;brokerConnected:false;executionEligible:false}>;
export type PublishedHedgePlan=Readonly<{planId:string;decisionId:string;portfolioId:string;candidateIds:readonly string[];makerId:string;checkerId:string;evidenceDigest:`sha256:${string}`;publishedAt:string;state:"PUBLISHED";executionType:"SIMULATED";brokerConnected:false;moneyMovement:false}>;
const bps=(part:number,total:number)=>total===0?0:Math.round(part*10_000/total);
export function evaluateHedgePortfolio(input:Readonly<{portfolioId:string;candidates:readonly HedgeCandidate[];acceptedQuantity4dp:number;stressedExposureMinor:number;policy:HedgeOptimizationPolicy}>):HedgePortfolio{
 const reasons:string[]=[];const quantity=input.candidates.reduce((s,c)=>s+c.quantity4dp,0);const premium=input.candidates.reduce((s,c)=>s+c.premiumMinor,0);const payoff=input.candidates.reduce((s,c)=>s+c.stressPayoffMinor,0);const coverage=bps(quantity,input.acceptedQuantity4dp);
 if(!input.candidates.length)reasons.push("EMPTY_PORTFOLIO");if(input.candidates.some(c=>!c.simulated||c.quantity4dp<=0||c.premiumMinor<0||c.stressPayoffMinor<0||!c.evidenceIds.length))reasons.push("CANDIDATE_INVALID");if(premium>input.policy.maximumPremiumMinor)reasons.push("PREMIUM_BUDGET_EXCEEDED");if(quantity>input.policy.maximumCoveredQuantity4dp||quantity>input.acceptedQuantity4dp)reasons.push("OVER_HEDGED");if(input.candidates.some(c=>c.basisCorrelationBps<input.policy.minimumBasisCorrelationBps))reasons.push("BASIS_CORRELATION_BELOW_MINIMUM");if(input.candidates.some(c=>c.liquidityScoreBps<input.policy.minimumLiquidityScoreBps))reasons.push("LIQUIDITY_BELOW_MINIMUM");
 const byCounterparty=new Map<string,number>();for(const c of input.candidates)byCounterparty.set(c.counterparty,(byCounterparty.get(c.counterparty)??0)+c.quantity4dp);const maxConcentration=quantity?Math.max(...byCounterparty.values())*10_000/quantity:0;if(maxConcentration>input.policy.maximumCounterpartyConcentrationBps)reasons.push("COUNTERPARTY_CONCENTRATION_EXCEEDED");
 const correlation=quantity?Math.round(input.candidates.reduce((s,c)=>s+c.basisCorrelationBps*c.quantity4dp,0)/quantity):0;const residual=Math.max(0,input.stressedExposureMinor-payoff);const basisPenalty=Math.round(input.stressedExposureMinor*(10_000-correlation)/10_000);const score=Math.round(residual*input.policy.residualWeightBps/10_000+premium*input.policy.premiumWeightBps/10_000+basisPenalty*input.policy.basisPenaltyWeightBps/10_000);
 return {portfolioId:input.portfolioId,candidateIds:input.candidates.map(c=>c.candidateId),status:reasons.length?"REJECTED":"ELIGIBLE",reasonCodes:reasons,coveredQuantity4dp:quantity,coverageBps:coverage,premiumMinor:premium,stressPayoffMinor:payoff,residualExposureMinor:residual,weightedBasisCorrelationBps:correlation,maximumCounterpartyConcentrationBps:Math.round(maxConcentration),objectiveScore:score,evidenceIds:[...new Set(input.candidates.flatMap(c=>c.evidenceIds))]};
}
export function optimizeSelectiveHedge(input:Readonly<{decisionId:string;snapshotId:string;basisModelId:string;acceptedQuantity4dp:number;stressedExposureMinor:number;candidates:readonly HedgeCandidate[];policy:HedgeOptimizationPolicy;decidedAt:string}>):HedgeOptimizationDecision{
 if(!input.decisionId.trim()||!input.snapshotId.trim()||!input.basisModelId.trim()||!Number.isFinite(Date.parse(input.decidedAt))||input.acceptedQuantity4dp<=0||input.stressedExposureMinor<=0||!input.candidates.length||input.candidates.length>12)return {decisionId:input.decisionId,version:HEDGE_OPTIMIZER_VERSION,status:"BLOCKED",reasonCode:"INPUT_INVALID",snapshotId:input.snapshotId,basisModelId:input.basisModelId,selectedPortfolioId:null,portfolios:[],decidedAt:input.decidedAt,simulationOnly:true,brokerConnected:false,executionEligible:false};
 const portfolios:HedgePortfolio[]=[];for(let mask=1;mask<2**input.candidates.length;mask++){const members=input.candidates.filter((_,i)=>mask&(1<<i));portfolios.push(evaluateHedgePortfolio({portfolioId:`PORTFOLIO-${mask.toString(2).padStart(input.candidates.length,"0")}`,candidates:members,acceptedQuantity4dp:input.acceptedQuantity4dp,stressedExposureMinor:input.stressedExposureMinor,policy:input.policy}));}
 const selected=portfolios.filter(p=>p.status==="ELIGIBLE").sort((a,b)=>a.objectiveScore-b.objectiveScore||b.stressPayoffMinor-a.stressPayoffMinor||a.premiumMinor-b.premiumMinor||a.portfolioId.localeCompare(b.portfolioId))[0];return {decisionId:input.decisionId,version:HEDGE_OPTIMIZER_VERSION,status:selected?"SELECTED":"BLOCKED",reasonCode:selected?"PORTFOLIO_SELECTED":"NO_ELIGIBLE_PORTFOLIO",snapshotId:input.snapshotId,basisModelId:input.basisModelId,selectedPortfolioId:selected?.portfolioId??null,portfolios,decidedAt:input.decidedAt,simulationOnly:true,brokerConnected:false,executionEligible:false};
}
export function publishSelectiveHedgePlan(decision:HedgeOptimizationDecision,input:Readonly<{planId:string;makerId:string;checkerId:string;assurance:"STEP_UP";evidenceDigest:`sha256:${string}`;publishedAt:string}>):PublishedHedgePlan{const selected=decision.portfolios.find(p=>p.portfolioId===decision.selectedPortfolioId);if(decision.status!=="SELECTED"||!selected||!input.planId.trim()||!input.makerId.trim()||input.makerId===input.checkerId||input.assurance!=="STEP_UP"||!/^sha256:[a-f0-9]{64}$/.test(input.evidenceDigest)||!Number.isFinite(Date.parse(input.publishedAt))||Date.parse(input.publishedAt)<Date.parse(decision.decidedAt))throw new Error("Selected portfolio and different-checker step-up evidence are required.");return {planId:input.planId,decisionId:decision.decisionId,portfolioId:selected.portfolioId,candidateIds:selected.candidateIds,makerId:input.makerId,checkerId:input.checkerId,evidenceDigest:input.evidenceDigest,publishedAt:input.publishedAt,state:"PUBLISHED",executionType:"SIMULATED",brokerConnected:false,moneyMovement:false};}
export const seededHedgeCandidates:readonly HedgeCandidate[]=[{candidateId:"HEDGE-A",instrument:"PAPER_CALL_SPREAD",market:"US-TX",quantity4dp:250_000_000,premiumMinor:18_000,stressPayoffMinor:72_000,basisCorrelationBps:9200,counterparty:"PAPER-CP-A",liquidityScoreBps:9000,evidenceIds:["EXP-TX","BASIS-MODEL-EU-DE-1"],simulated:true},{candidateId:"HEDGE-B",instrument:"PAPER_SWAP",market:"US-TX",quantity4dp:180_000_000,premiumMinor:12_000,stressPayoffMinor:50_000,basisCorrelationBps:8700,counterparty:"PAPER-CP-B",liquidityScoreBps:8500,evidenceIds:["EXP-TX","STRESS-CORR"],simulated:true},{candidateId:"HEDGE-C",instrument:"PAPER_CALL",market:"US-TX",quantity4dp:160_000_000,premiumMinor:15_000,stressPayoffMinor:58_000,basisCorrelationBps:7800,counterparty:"PAPER-CP-A",liquidityScoreBps:9200,evidenceIds:["EXP-TX","STRESS-BREACH"],simulated:true}];
export const seededHedgePolicy:HedgeOptimizationPolicy={policyId:"HEDGE-OPT-POLICY-1",maximumPremiumMinor:35_000,maximumCoveredQuantity4dp:450_000_000,minimumBasisCorrelationBps:8000,minimumLiquidityScoreBps:8000,maximumCounterpartyConcentrationBps:7000,residualWeightBps:10_000,premiumWeightBps:2000,basisPenaltyWeightBps:3000};
export const seededHedgeDecision=optimizeSelectiveHedge({decisionId:"HEDGE-OPT-TX-1",snapshotId:"EXP-TX-0842",basisModelId:"BASIS-MODEL-EU-DE-1",acceptedQuantity4dp:684_000_000,stressedExposureMinor:150_000,candidates:seededHedgeCandidates,policy:seededHedgePolicy,decidedAt:"2026-08-28T08:00:00Z"});
export const seededPublishedHedgePlan=publishSelectiveHedgePlan(seededHedgeDecision,{planId:"HEDGE-PLAN-TX-1",makerId:"principal-risk",checkerId:"principal-data",assurance:"STEP_UP",evidenceDigest:"sha256:eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee",publishedAt:"2026-08-28T08:01:00Z"});
