import { describe, expect, it } from "vitest";
import { createLedgerState, createReversalCommand, postJournal, type LedgerAccount, type LedgerState, type PostJournalCommand } from "@fuelcap/ledger";
import { assertWalletSnapshot, deriveWalletActivity, deriveWalletBalance, type WalletDefinition } from "./index";

const entity = "FC-US-INC";
const accounts: readonly LedgerAccount[] = [
  { accountId: "cash", legalEntityId: entity, currency: "USD", type: "ASSET", normalBalance: "DEBIT", purpose: "SAFEGUARDED_CASH" },
  { accountId: "available", legalEntityId: entity, currency: "USD", type: "LIABILITY", normalBalance: "CREDIT", purpose: "CUSTOMER_AVAILABLE" },
  { accountId: "reserved", legalEntityId: entity, currency: "USD", type: "LIABILITY", normalBalance: "CREDIT", purpose: "CUSTOMER_RESERVED" },
  { accountId: "refund", legalEntityId: entity, currency: "USD", type: "LIABILITY", normalBalance: "CREDIT", purpose: "CUSTOMER_REFUND_PAYABLE" },
];
const wallet: WalletDefinition = { walletId: "WALLET-1", customerId: "CUSTOMER-1", organisationId: "ORG-1", legalEntityId: entity, currency: "USD", availableAccountId: "available", reservedAccountId: "reserved", refundPayableAccountId: "refund", positionIds: ["POS-1"] };
const lineage = { organisationId: "ORG-1", legalEntityId: entity, market: "US-TX", sourceContractId: "CUSTOMER-FUNDING", rulesVersion: "rules-engine@1.0.0", scenarioId: "flat-market-us", externalReference: null, actorId: "wallet-system", correlationId: "CORR-1" } as const;
const command = (input: Pick<PostJournalCommand, "commandId" | "idempotencyKey" | "journalId" | "transactionId" | "eventType" | "lines"> & Partial<Pick<PostJournalCommand, "positionMovements" | "postedAt">>): PostJournalCommand => ({ ...input, postedAt: input.postedAt ?? "2026-08-26T15:00:00.000Z", positionMovements: input.positionMovements ?? [], lineage, correctionOf: null });
const fundedState = () => postJournal(createLedgerState("LEDGER-1", accounts), command({ commandId: "FUND", idempotencyKey: "fund:1", journalId: "JRN-FUND", transactionId: "TXN-FUND", eventType: "CUSTOMER_FUNDED", lines: [{ lineId: "F1", accountId: "cash", currency: "USD", side: "DEBIT", amountMinor: 10_000 }, { lineId: "F2", accountId: "available", currency: "USD", side: "CREDIT", amountMinor: 10_000 }] })).state;

describe("wallet derived balances", () => {
  it("derives available value solely from the journal", () => expect(deriveWalletBalance(fundedState(), wallet)).toMatchObject({ availableMinor: 10_000, reservedMinor: 0, refundPayableMinor: 0, totalCustomerValueMinor: 10_000, state: "CURRENT" }));
  it("moves value from available to reserved without changing total customer value", () => { const first = fundedState(); const protectedState = postJournal(first, command({ commandId: "PROTECT", idempotencyKey: "protect:1", journalId: "JRN-PROTECT", transactionId: "TXN-PROTECT", eventType: "PROTECTION_ACCEPTED", lines: [{ lineId: "P1", accountId: "available", currency: "USD", side: "DEBIT", amountMinor: 9_188 }, { lineId: "P2", accountId: "reserved", currency: "USD", side: "CREDIT", amountMinor: 9_188 }], positionMovements: [{ movementId: "M1", positionId: "POS-1", fuelProductId: "US-TX-REGULAR", type: "PROTECT", quantity4dp: 250_000 }] })).state; expect(deriveWalletBalance(protectedState, wallet)).toMatchObject({ availableMinor: 812, reservedMinor: 9_188, totalCustomerValueMinor: 10_000, protectedQuantity4dp: 250_000 }); });
  it("releases unused reserved value back to available", () => { let state = fundedState(); state = postJournal(state, command({ commandId: "R", idempotencyKey: "release:1", journalId: "JRN-RELEASE", transactionId: "TXN-RELEASE", eventType: "VALUE_RELEASED", lines: [{ lineId: "R1", accountId: "available", currency: "USD", side: "CREDIT", amountMinor: 550 }, { lineId: "R2", accountId: "reserved", currency: "USD", side: "DEBIT", amountMinor: 550 }] })).state; expect(deriveWalletBalance(state, wallet)).toMatchObject({ availableMinor: 10_550, reservedMinor: -550, state: "BREAK", reasonCodes: ["NEGATIVE_CUSTOMER_LIABILITY"] }); });
  it("derives refund-payable separately from spendable value", () => { const state = postJournal(fundedState(), command({ commandId: "REF", idempotencyKey: "refund:1", journalId: "JRN-REF", transactionId: "TXN-REF", eventType: "REFUND_APPROVED", lines: [{ lineId: "R1", accountId: "available", currency: "USD", side: "DEBIT", amountMinor: 500 }, { lineId: "R2", accountId: "refund", currency: "USD", side: "CREDIT", amountMinor: 500 }] })).state; expect(deriveWalletBalance(state, wallet)).toMatchObject({ availableMinor: 9_500, refundPayableMinor: 500, totalCustomerValueMinor: 10_000 }); });
  it("does not include unrelated customer accounts or positions", () => { const otherWallet = { ...wallet, walletId: "W2", customerId: "C2", positionIds: [] }; expect(deriveWalletBalance(fundedState(), otherWallet).totalCustomerValueMinor).toBe(10_000); });
  it("rejects wallet mappings with the wrong account purpose", () => expect(() => deriveWalletBalance(fundedState(), { ...wallet, availableAccountId: "cash" })).toThrow(/purpose/i));
  it("produces an ordered auditable activity timeline", () => { const activity = deriveWalletActivity(fundedState(), wallet); expect(activity).toHaveLength(1); expect(activity[0]).toMatchObject({ sequence: 1, eventType: "CUSTOMER_FUNDED", availableDeltaMinor: 10_000 }); });
  it("reverses both monetary and position effects through linked correction lineage", () => { let state: LedgerState = fundedState(); const protection = postJournal(state, command({ commandId: "P", idempotencyKey: "p:1", journalId: "JRN-P", transactionId: "TXN-P", eventType: "PROTECTION_ACCEPTED", lines: [{ lineId: "P1", accountId: "available", currency: "USD", side: "DEBIT", amountMinor: 1_000 }, { lineId: "P2", accountId: "reserved", currency: "USD", side: "CREDIT", amountMinor: 1_000 }], positionMovements: [{ movementId: "M1", positionId: "POS-1", fuelProductId: "US-TX-REGULAR", type: "PROTECT", quantity4dp: 25_000 }] })); state = protection.state; const reversal = createReversalCommand(protection.journal, { commandId: "REV", idempotencyKey: "rev:1", journalId: "JRN-REV", transactionId: "TXN-REV", postedAt: "2026-08-26T15:01:00.000Z", actorId: "maker", approverId: "checker", reason: "Correction" }); state = postJournal(state, reversal).state; expect(deriveWalletBalance(state, wallet)).toMatchObject({ availableMinor: 10_000, reservedMinor: 0, protectedQuantity4dp: 0 }); });
  it("detects a stored snapshot that diverges from journal rebuild", () => { const current = deriveWalletBalance(fundedState(), wallet); expect(assertWalletSnapshot(fundedState(), wallet, current)).toEqual(current); expect(() => assertWalletSnapshot(fundedState(), wallet, { ...current, availableMinor: 9_999 })).toThrow(/diverges/i); });
  it("returns the genesis anchor for an empty wallet", () => expect(deriveWalletBalance(createLedgerState("LEDGER-1", accounts), wallet)).toMatchObject({ totalCustomerValueMinor: 0, throughSequence: 0, throughIntegrityHash: "GENESIS" }));
});
