import { describe, expect, it } from "vitest";
import { applySpreadAdjustments, approveSpreadProposal, createFixedUnitCharge, createFuelCapPlusProposal, createPercentageCharge, createSpreadProposal, publishScheduledSpreadDecision, publishSpreadDecision, scheduleSpreadDecision, simulateSpreadProposal, supersedeSpreadDecision, toQuoteChargeSnapshot, totalSpreadBps, withdrawSpreadDecision, type PublishedSpreadDecision, type SpreadPolicy } from "./index";

const policy: SpreadPolicy = { policyId: "SPREAD-POLICY-1", maximumTotalChargeBps: 500, defaultComponents: { modelledProtectionCostBps: 130, fuelCapMarginBps: 70, reserveBufferBps: 30 }, fuelCapPlusRemovesMargin: true, maximumChangeBps: 50, minimumCostRecoveryBps: 120, maximumExposureQuantity4dp: 2_000_000 };
const proposal = (components = policy.defaultComponents, extra: { subsidySource?: string } = {}) => createSpreadProposal({ proposalId: "PROPOSAL-1", makerId: "rates-maker", reason: "Reprice governed components", createdAt: "2026-08-26T09:00:00Z", components, ...extra }, policy);
const approval = (source = proposal()) => approveSpreadProposal(source, { approvalId: "APPROVAL-1", checkerId: "finance-checker", assurance: "STEP_UP", approvedAt: "2026-08-26T09:01:00Z" });

describe("spread engine", () => {
  it("derives 2.30% solely as the sum of editable components", () => { const result = proposal(); expect(result.totalChargeBps).toBe(230); expect(totalSpreadBps(result.components)).toBe(230); });
  it("recomputes the total when an individual component changes", () => { const result = proposal({ modelledProtectionCostBps: 134, fuelCapMarginBps: 70, reserveBufferBps: 30 }); expect(result.totalChargeBps).toBe(234); });
  it("FuelCap+ removes margin only", () => { const result = createFuelCapPlusProposal({ proposalId: "PLUS-1", makerId: "rates-maker", reason: "FuelCap+", createdAt: "2026-08-26T09:00:00Z" }, policy); expect(result.components).toEqual({ modelledProtectionCostBps: 130, fuelCapMarginBps: 0, reserveBufferBps: 30 }); expect(result.totalChargeBps).toBe(160); });
  it("requires subsidy evidence when modelled protection cost is reduced", () => { expect(() => proposal({ modelledProtectionCostBps: 120, fuelCapMarginBps: 70, reserveBufferBps: 30 })).toThrow(/subsidy/i); expect(proposal({ modelledProtectionCostBps: 120, fuelCapMarginBps: 70, reserveBufferBps: 30 }, { subsidySource: "PROMO-BUDGET-7" }).subsidySource).toBe("PROMO-BUDGET-7"); });
  it("rejects negative, fractional and excessive components", () => { expect(() => proposal({ modelledProtectionCostBps: -1, fuelCapMarginBps: 70, reserveBufferBps: 30 })).toThrow(); expect(() => proposal({ modelledProtectionCostBps: 130.5, fuelCapMarginBps: 70, reserveBufferBps: 30 })).toThrow(); expect(() => proposal({ modelledProtectionCostBps: 400, fuelCapMarginBps: 80, reserveBufferBps: 30 })).toThrow(/limit/i); });
  it("enforces different-maker step-up approval", () => { const source = proposal(); expect(() => approveSpreadProposal(source, { approvalId: "A", checkerId: "rates-maker", assurance: "STEP_UP", approvedAt: "2026-08-26T09:01:00Z" })).toThrow(/differ/i); expect(approval(source).assurance).toBe("STEP_UP"); });
  it("publishes immutable component and approval lineage", () => { const source = proposal(); const result = publishSpreadDecision("SPREAD-DECISION-1", source, approval(source), "2026-08-26T09:02:00Z", policy); expect(result.state).toBe("PUBLISHED"); expect(result.totalChargeBps).toBe(230); expect(result.proposalId).toBe("PROPOSAL-1"); expect(result.approvalId).toBe("APPROVAL-1"); });
  it("detects any tampered non-derived proposal total at publication", () => { const source = { ...proposal(), totalChargeBps: 231 }; expect(() => publishSpreadDecision("SPREAD-DECISION-1", source, approval(source), "2026-08-26T09:02:00Z", policy)).toThrow(/component-derived/i); });
  it("supplies the quote engine with a pinned flat component snapshot", () => { const source = proposal(); const snapshot = toQuoteChargeSnapshot(publishSpreadDecision("SPREAD-DECISION-1", source, approval(source), "2026-08-26T09:02:00Z", policy)); expect(snapshot).toEqual({ chargeDecisionId: "SPREAD-DECISION-1", chargeDecisionVersion: "spread-engine@1.1.0", modelledProtectionCostBps: 130, fuelCapMarginBps: 70, reserveBufferBps: 30, totalChargeBps: 230 }); });
  it("applies component adjustments in deterministic DEC-034 precedence", () => { const result = applySpreadAdjustments(policy.defaultComponents, [{ adjustmentId: "PROMO", kind: "PROMOTION", component: "fuelCapMarginBps", deltaBps: -10, reasonCode: "PROMO_APPROVED" }, { adjustmentId: "VOL", kind: "EXPOSURE_VOLATILITY", component: "modelledProtectionCostBps", deltaBps: 15, reasonCode: "VOLATILITY_HIGH" }], policy); expect(result.components).toEqual({ modelledProtectionCostBps: 145, fuelCapMarginBps: 60, reserveBufferBps: 30 }); expect(result.appliedAdjustmentIds).toEqual(["VOL", "PROMO"]); });
  it("keeps percentage and fixed-unit modes explicitly non-interchangeable", () => { expect(createPercentageCharge(policy.defaultComponents, policy)).toEqual({ mode: "PERCENTAGE_OF_REFERENCE", components: policy.defaultComponents, totalChargeBps: 230 }); expect(createFixedUnitCharge({ currency: "USD", fuelUnit: "GALLON", amountMinorPerUnit: 9 })).toEqual({ mode: "FIXED_MINOR_PER_UNIT", fixed: { currency: "USD", fuelUnit: "GALLON", amountMinorPerUnit: 9 } }); expect(() => createFixedUnitCharge({ currency: "GBP", fuelUnit: "LITRE", amountMinorPerUnit: 1.5 })).toThrow(/integer/i); });
  it("simulates customer, exposure, claim, margin and reserve impact before approval", () => { const current = publishSpreadDecision("CURRENT", proposal(), approval(), "2026-08-26T09:02:00Z", policy); const next = proposal({ modelledProtectionCostBps: 140, fuelCapMarginBps: 70, reserveBufferBps: 30 }); const result = simulateSpreadProposal({ simulationId: "SIM-1", proposal: next, currentDecision: current, cohorts: [{ cohortId: "US-FLEET", customerCount: 12, protectedQuantity4dp: 1_000_000, referencePriceMinorPerUnit: 400, expectedClaimMinor: 450 }], simulatedAt: "2026-08-26T09:03:00Z" }, policy); expect(result).toMatchObject({ state: "SIMULATED", affectedCustomers: 12, protectedQuantity4dp: 1_000_000, expectedRevenueDeltaMinor: 40, expectedClaimsMinor: 450, expectedMarginMinor: 280, expectedReserveContributionMinor: 120, blockers: [] }); });
  it("fails simulation closed on change and exposure limits", () => { const current = publishSpreadDecision("CURRENT", proposal(), approval(), "2026-08-26T09:02:00Z", policy); const next = proposal({ modelledProtectionCostBps: 190, fuelCapMarginBps: 70, reserveBufferBps: 30 }); const result = simulateSpreadProposal({ simulationId: "SIM-BLOCKED", proposal: next, currentDecision: current, cohorts: [{ cohortId: "ALL", customerCount: 50, protectedQuantity4dp: 2_000_001, referencePriceMinorPerUnit: 400, expectedClaimMinor: 900 }], simulatedAt: "2026-08-26T09:03:00Z" }, policy); expect(result.state).toBe("BLOCKED"); expect(result.blockers).toEqual(["MAXIMUM_CHANGE_EXCEEDED", "EXPOSURE_CAP_EXCEEDED"]); });
  it("schedules only approved passing simulations and publishes at the effective time", () => { const current = publishSpreadDecision("CURRENT", proposal(), approval(), "2026-08-26T09:02:00Z", policy); const next = proposal({ modelledProtectionCostBps: 140, fuelCapMarginBps: 70, reserveBufferBps: 30 }); const checked = approval(next); const simulation = simulateSpreadProposal({ simulationId: "SIM-2", proposal: next, currentDecision: current, cohorts: [], simulatedAt: "2026-08-26T09:03:00Z" }, policy); const scheduled = scheduleSpreadDecision({ scheduleId: "SCHEDULE-1", chargeDecisionId: "NEXT", proposal: next, approval: checked, simulation, scheduledBy: "scheduler", scheduledAt: "2026-08-26T09:04:00Z", effectiveFrom: "2026-08-27T00:00:00Z" }); expect(() => publishScheduledSpreadDecision(scheduled, "2026-08-26T23:59:59Z", policy)).toThrow(/before/i); expect(publishScheduledSpreadDecision(scheduled, "2026-08-27T00:00:00Z", policy).state).toBe("PUBLISHED"); });
  it("withdraws new-quote eligibility without rewriting accepted quote snapshots", () => { const current = publishSpreadDecision("CURRENT", proposal(), approval(), "2026-08-26T09:02:00Z", policy); const snapshot = toQuoteChargeSnapshot(current); const withdrawal = withdrawSpreadDecision(current, { withdrawalId: "WITHDRAW-1", withdrawnBy: "risk-checker", reason: "Emergency new-quote stop", withdrawnAt: "2026-08-26T09:05:00Z" }); expect(withdrawal).toMatchObject({ state: "WITHDRAWN", stopsNewQuotesOnly: true }); expect(toQuoteChargeSnapshot(current)).toEqual(snapshot); });
  it("supersedes a decision while preserving accepted quotes", () => { const current = publishSpreadDecision("CURRENT", proposal(), approval(), "2026-08-26T09:02:00Z", policy); const replacement = { ...current, chargeDecisionId: "NEXT", publishedAt: "2026-08-27T00:00:00Z" } satisfies PublishedSpreadDecision; expect(supersedeSpreadDecision(current, replacement, { supersessionId: "SUPERSEDE-1", supersededAt: "2026-08-27T00:00:01Z" })).toMatchObject({ state: "SUPERSEDED", preservesAcceptedQuotes: true, previousDecisionId: "CURRENT", replacementDecisionId: "NEXT" }); });
});
