import { describe, expect, it } from "vitest";
import { approveSpreadProposal, createFuelCapPlusProposal, createSpreadProposal, publishSpreadDecision, toQuoteChargeSnapshot, totalSpreadBps, type SpreadPolicy } from "./index";

const policy: SpreadPolicy = { policyId: "SPREAD-POLICY-1", maximumTotalChargeBps: 500, defaultComponents: { modelledProtectionCostBps: 130, fuelCapMarginBps: 70, reserveBufferBps: 30 }, fuelCapPlusRemovesMargin: true };
const proposal = (components = policy.defaultComponents, extra: { subsidySource?: string } = {}) => createSpreadProposal({ proposalId: "PROPOSAL-1", makerId: "rates-maker", reason: "Reprice governed components", createdAt: "2026-08-26T09:00:00Z", components, ...extra }, policy);
const approval = (source = proposal()) => approveSpreadProposal(source, { approvalId: "APPROVAL-1", checkerId: "finance-checker", assurance: "STEP_UP", approvedAt: "2026-08-26T09:01:00Z" });

describe("spread engine", () => {
  it("derives 2.30% solely as the sum of editable components", () => { const result = proposal(); expect(result.totalChargeBps).toBe(230); expect(totalSpreadBps(result.components)).toBe(230); });
  it("recomputes the total when an individual component changes", () => { const result = proposal({ modelledProtectionCostBps: 134, fuelCapMarginBps: 70, reserveBufferBps: 30 }); expect(result.totalChargeBps).toBe(234); });
  it("FuelCap+ removes margin only", () => { const result = createFuelCapPlusProposal({ proposalId: "PLUS-1", makerId: "rates-maker", reason: "FuelCap+", createdAt: "2026-08-26T09:00:00Z" }, policy); expect(result.components).toEqual({ modelledProtectionCostBps: 130, fuelCapMarginBps: 0, reserveBufferBps: 30 }); expect(result.totalChargeBps).toBe(160); });
  it("requires subsidy evidence when modelled protection cost is reduced", () => { expect(() => proposal({ modelledProtectionCostBps: 120, fuelCapMarginBps: 70, reserveBufferBps: 30 })).toThrow(/subsidy/i); expect(proposal({ modelledProtectionCostBps: 120, fuelCapMarginBps: 70, reserveBufferBps: 30 }, { subsidySource: "PROMO-BUDGET-7" }).subsidySource).toBe("PROMO-BUDGET-7"); });
  it("rejects negative, fractional and excessive components", () => { expect(() => proposal({ modelledProtectionCostBps: -1, fuelCapMarginBps: 70, reserveBufferBps: 30 })).toThrow(); expect(() => proposal({ modelledProtectionCostBps: 130.5, fuelCapMarginBps: 70, reserveBufferBps: 30 })).toThrow(); expect(() => proposal({ modelledProtectionCostBps: 400, fuelCapMarginBps: 80, reserveBufferBps: 30 })).toThrow(/limit/i); });
  it("enforces different-maker step-up approval", () => { const source = proposal(); expect(() => approveSpreadProposal(source, { approvalId: "A", checkerId: "rates-maker", assurance: "STEP_UP", approvedAt: "2026-08-26T09:01:00Z" })).toThrow(/differ/i); expect(approval(source).assurance).toBe("STEP_UP"); });
  it("publishes immutable component and approval lineage", () => { const source = proposal(); const result = publishSpreadDecision("SPREAD-DECISION-1", source, approval(source), "2026-08-26T09:02:00Z", policy); expect(result.state).toBe("PUBLISHED"); expect(result.totalChargeBps).toBe(230); expect(result.proposalId).toBe("PROPOSAL-1"); expect(result.approvalId).toBe("APPROVAL-1"); });
  it("detects any tampered non-derived proposal total at publication", () => { const source = { ...proposal(), totalChargeBps: 231 }; expect(() => publishSpreadDecision("SPREAD-DECISION-1", source, approval(source), "2026-08-26T09:02:00Z", policy)).toThrow(/component-derived/i); });
  it("supplies the quote engine with a pinned flat component snapshot", () => { const source = proposal(); const snapshot = toQuoteChargeSnapshot(publishSpreadDecision("SPREAD-DECISION-1", source, approval(source), "2026-08-26T09:02:00Z", policy)); expect(snapshot).toEqual({ chargeDecisionId: "SPREAD-DECISION-1", chargeDecisionVersion: "spread-engine@1.0.0", modelledProtectionCostBps: 130, fuelCapMarginBps: 70, reserveBufferBps: 30, totalChargeBps: 230 }); });
});
