import { createHmac } from "node:crypto";
import { describe, expect, it, vi } from "vitest";
import { createStripeWebhookVerifier, StripeTestBillingAdapter, type CreatePaymentCommand, type CreateSubscriptionCommand, type StripeGateway } from "./index";

const clock = () => "2026-08-26T16:00:00.000Z";
const gateway: StripeGateway = {
  createPaymentIntent: vi.fn(async () => ({ id: "pi_test_1", status: "requires_action" as const, livemode: false })),
  createSubscription: vi.fn(async () => ({ id: "sub_test_1", status: "trialing" as const, livemode: false, currentPeriodEnd: "2026-09-26T00:00:00.000Z" })),
};
const payment: CreatePaymentCommand = { commandId: "PAY-1", idempotencyKey: "funding:1", customerId: "CUSTOMER-1", walletId: "WALLET-1", amountMinor: 10_000, currency: "USD", paymentMethodReference: "pm_test_1", mode: "TEST" };
const subscription: CreateSubscriptionCommand = { commandId: "SUB-1", idempotencyKey: "plus:1", customerId: "CUSTOMER-1", planId: "FUELCAP-PLUS", priceReference: "price_test_plus", currency: "USD", mode: "TEST" };
const makeEvent = (id: string, type: string, object: Record<string, unknown>) => JSON.stringify({ id, type, livemode: false, data: { object } });
const request = (rawBody: string) => ({ rawBody, signatureHeader: "verified", receivedAt: clock() });
const adapter = () => new StripeTestBillingAdapter(gateway, ({ signatureHeader }) => signatureHeader === "verified", clock);

describe("Stripe test-mode billing adapter", () => {
  it("creates a provider-neutral payment record and persists the external ID", async () => expect(await adapter().createPayment(payment)).toMatchObject({ providerObjectId: "pi_test_1", status: "REQUIRES_ACTION", mode: "TEST" }));
  it("replays the same payment command without another provider call", async () => { const localGateway = { ...gateway, createPaymentIntent: vi.fn(async () => ({ id: "pi_test_1", status: "requires_action" as const, livemode: false })) }; const service = new StripeTestBillingAdapter(localGateway, () => true, clock); await service.createPayment(payment); await service.createPayment(payment); expect(localGateway.createPaymentIntent).toHaveBeenCalledTimes(1); });
  it("rejects idempotency-key reuse with different parameters", async () => { const service = adapter(); await service.createPayment(payment); await expect(service.createPayment({ ...payment, amountMinor: 9_999 })).rejects.toThrow(/different payment parameters/i); });
  it("hard-blocks live payment commands", async () => await expect(adapter().createPayment({ ...payment, mode: "LIVE" })).rejects.toThrow(/Phase 6/i));
  it("creates and idempotently replays a test subscription", async () => { const localGateway = { ...gateway, createSubscription: vi.fn(async () => ({ id: "sub_test_1", status: "trialing" as const, livemode: false, currentPeriodEnd: "2026-09-26T00:00:00.000Z" })) }; const service = new StripeTestBillingAdapter(localGateway, () => true, clock); const first = await service.createSubscription(subscription); const second = await service.createSubscription(subscription); expect(second).toEqual(first); expect(localGateway.createSubscription).toHaveBeenCalledTimes(1); });
  it("rejects unverified webhooks before parsing or storage", () => expect(() => adapter().ingestWebhook({ ...request("not-json"), signatureHeader: "bad" })).toThrow(/signature/i));
  it("stores an immutable webhook and deduplicates an exact retry", () => { const service = adapter(); const webhook = request(makeEvent("evt_1", "unhandled", {})); expect(service.ingestWebhook(webhook).disposition).toBe("QUEUED"); expect(service.ingestWebhook(webhook).disposition).toBe("DUPLICATE"); expect(service.listWebhookEvents()).toHaveLength(1); });
  it("rejects an event ID reused with a different payload", () => { const service = adapter(); service.ingestWebhook(request(makeEvent("evt_1", "first", {}))); expect(() => service.ingestWebhook(request(makeEvent("evt_1", "second", {})))).toThrow(/immutable payload/i); });
  it("processes webhooks asynchronously and emits one ledger instruction only after reconciled success", async () => { const service = adapter(); await service.createPayment(payment); const body = makeEvent("evt_success", "payment_intent.succeeded", { id: "pi_test_1", livemode: false, amount_received: 10_000, currency: "usd" }); service.ingestWebhook(request(body)); expect(service.listFundingInstructions()).toHaveLength(0); expect(service.processNextWebhook()?.status).toBe("PROCESSED"); expect(service.listFundingInstructions()).toEqual([expect.objectContaining({ amountMinor: 10_000, walletId: "WALLET-1", idempotencyKey: "stripe-event:evt_success" })]); expect(service.processNextWebhook()).toBeNull(); });
  it("rejects a succeeded payment that does not reconcile", async () => { const service = adapter(); await service.createPayment(payment); service.ingestWebhook(request(makeEvent("evt_bad", "payment_intent.succeeded", { id: "pi_test_1", amount_received: 9_999, currency: "usd" }))); expect(() => service.processNextWebhook()).toThrow(/reconcile/i); expect(service.listFundingInstructions()).toHaveLength(0); });
  it("accepts out-of-order unknown events without inventing ledger state", () => { const service = adapter(); service.ingestWebhook(request(makeEvent("evt_unknown", "payment_intent.succeeded", { id: "pi_missing", amount_received: 10_000, currency: "usd" }))); expect(service.processNextWebhook()?.status).toBe("IGNORED"); expect(service.listFundingInstructions()).toHaveLength(0); });
  it("projects subscription lifecycle updates without changing ledger value", async () => { const service = adapter(); await service.createSubscription(subscription); service.ingestWebhook(request(makeEvent("evt_sub", "customer.subscription.updated", { id: "sub_test_1", status: "active", current_period_end: 1_788_480_000 }))); expect(service.processNextWebhook()?.status).toBe("PROCESSED"); expect(service.getSubscription("sub_test_1")?.status).toBe("ACTIVE"); expect(service.listFundingInstructions()).toHaveLength(0); });
});

describe("Stripe-compatible webhook verification", () => {
  it("verifies the raw body, timestamp and v1 HMAC", () => { const body = "{\"id\":\"evt_signed\"}"; const secret = "whsec_test_only"; const timestamp = 1_788_480_000; const signature = createHmac("sha256", secret).update(`${timestamp}.${body}`).digest("hex"); const verify = createStripeWebhookVerifier(secret, 300, () => timestamp + 10); expect(verify({ rawBody: body, signatureHeader: `t=${timestamp},v1=${signature}`, receivedAt: clock() })).toBe(true); expect(verify({ rawBody: `${body} `, signatureHeader: `t=${timestamp},v1=${signature}`, receivedAt: clock() })).toBe(false); });
  it("rejects stale signatures", () => { const verify = createStripeWebhookVerifier("whsec_test_only", 300, () => 1_000); expect(verify({ rawBody: "{}", signatureHeader: "t=1,v1=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", receivedAt: clock() })).toBe(false); });
});
