import {describe,expect,it} from "vitest";
import {evaluateBasisCandidate,optimizeBasisModel,proposeBasisModel,publishBasisModel,seededBasisDecision,seededBasisObservations,seededBasisPolicy,seededPublishedBasisModel,toBasisPoints} from "./index";

describe("P7-002 deterministic basis optimisation",()=>{
  it("defines signed basis as retail minus wholesale",()=>expect(toBasisPoints(seededBasisObservations)[0]?.signedBasisMinor4).toBe(520));
  it("sorts observations and rejects duplicate time points",()=>{expect(toBasisPoints([...seededBasisObservations].reverse())[0]?.observationId).toBe("BASIS-EU-01");expect(()=>toBasisPoints([...seededBasisObservations,{...seededBasisObservations[0]!,observationId:"DUP"}])).toThrow(/time-distinct/);});
  it("backtests every candidate without lookahead",()=>{expect(seededBasisDecision.noLookahead).toBe(true);expect(seededBasisDecision.candidates).toHaveLength(6);expect(seededBasisDecision.candidates.every(({holdoutCount})=>holdoutCount===4)).toBe(true);});
  it("selects deterministically by MAE, bias, window and ID",()=>expect(seededBasisDecision).toMatchObject({status:"SELECTED",reasonCode:"MODEL_SELECTED",selectedCandidateId:"ROLLING_MEDIAN-4",observationCount:12,holdoutCount:4}));
  it("retains explainable holdout metrics and evidence",()=>{const selected=seededBasisDecision.candidates.find(({candidateId})=>candidateId===seededBasisDecision.selectedCandidateId)!;expect(selected).toMatchObject({status:"PASS",meanAbsoluteErrorMinor4:18,maximumAbsoluteErrorMinor4:27,signedBiasMinor4:-18});expect(selected.evidenceIds).toHaveLength(24);});
  it("rejects unpermitted model complexity",()=>expect(evaluateBasisCandidate(toBasisPoints(seededBasisObservations),{candidateId:"BAD",strategy:"ROLLING_MEAN",windowSize:12},4,seededBasisPolicy)).toMatchObject({status:"REJECTED",reasonCodes:["WINDOW_NOT_PERMITTED","INSUFFICIENT_HOLDOUT_HISTORY"]}));
  it("blocks when every candidate breaches validation thresholds",()=>{const policy={...seededBasisPolicy,maximumMeanAbsoluteErrorMinor4:1,maximumAbsoluteErrorMinor4:1,maximumSignedBiasAbsoluteMinor4:1};expect(optimizeBasisModel({decisionId:"BLOCKED",decidedAt:"2027-05-02T00:00:00Z",observations:seededBasisObservations,candidates:[{candidateId:"ONE",strategy:"ROLLING_MEAN",windowSize:4}],holdoutCount:4,policy})).toMatchObject({status:"BLOCKED",reasonCode:"NO_ELIGIBLE_MODEL",selectedCandidateId:null});});
  it("requires a selected decision and real evidence digest for proposal",()=>expect(()=>proposeBasisModel({...seededBasisDecision,status:"BLOCKED",selectedCandidateId:null,selectedForecastBasisMinor4:null},{proposalId:"P",evidenceDigest:"sha256:bad",makerId:"maker",reason:"reason",rollbackReference:"RB",proposedAt:"2027-05-02T00:01:00Z"})).toThrow(/selected decision/));
  it("requires a different checker bound to the exact proposal",()=>{expect(seededPublishedBasisModel).toMatchObject({state:"PUBLISHED",makerId:"principal-risk",checkerId:"principal-data"});const proposal={proposalId:"P",decisionId:"D",selectedCandidateId:"C",forecastBasisMinor4:1,evidenceDigest:"sha256:dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd",makerId:"maker",reason:"reason",rollbackReference:"RB",state:"PENDING_APPROVAL",proposedAt:"2027-05-02T00:01:00Z"} as const;expect(()=>publishBasisModel("M",proposal,{checkerId:"maker",assurance:"STEP_UP",evidenceDigest:proposal.evidenceDigest,publishedAt:"2027-05-02T00:02:00Z"})).toThrow(/Different-checker/);});
  it("keeps published output display/simulation only",()=>expect(seededPublishedBasisModel).toMatchObject({permittedUses:["DISPLAY","SIMULATE"],quoteEligible:false,hedgeExecutionEligible:false}));
});
