import { describe, expect, it } from "vitest";
import { allocatePurchase, createAllocationState, type ProtectionPosition, type PurchaseMatchCommand } from "./index";

const position = (id: string, overrides: Partial<ProtectionPosition> = {}): ProtectionPosition => ({ protectionTransactionId: id, owner: { type: "CUSTOMER", ownerId: "CUSTOMER-1" }, countryCode: "US", currency: "USD", fuelGradeId: "REGULAR", scope: { type: "STATION", scopeId: "STATION-1" }, status: "ACTIVE", startsAt: "2026-08-20T00:00:00.000Z", expiresAt: "2026-08-28T00:00:00.000Z", acceptedAt: "2026-08-20T10:00:00.000Z", remainingQuantity4dp: 100_000, referencePriceId: `REF-${id}`, quoteId: `QUOTE-${id}`, spreadDecisionVersion: "spread@1", rulesVersion: "rules@1", ...overrides });
const clearing = { clearingId: "CLEAR-1", authorizationId: "AUTH-1", customerId: "CUSTOMER-1", walletId: "WALLET-1", organisationId: "ORG-1", providerReference: "SIM-1", merchantId: "STATION-1", amountMinor: 6_800, currency: "USD", eventType: "CARD_CLEARING_ACCEPTED", source: "CARD_SIMULATOR", correlationId: "CORR-1" } as const;
const command: PurchaseMatchCommand = { commandId: "CMD-1", idempotencyKey: "allocate:1", allocationId: "ALLOC-1", purchaseId: "PURCHASE-1", clearing, customerId: "CUSTOMER-1", vehicleId: null, protectionPoolId: null, countryCode: "US", currency: "USD", fuelGradeId: "REGULAR", stationId: "STATION-1", providerId: "PROVIDER-1", geographyId: "US-TX", confirmedFuelQuantity4dp: 150_000, nonFuelAmountMinor: 500, purchasedAt: "2026-08-27T09:00:00.000Z", actualPumpObservationId: "PUMP-1", provenance: "SIMULATED" };

describe("purchase matching and lock allocation", () => {
  it("allocates soonest-expiry protection first and carries pinned lineage", () => { const state = createAllocationState([position("LATE", { expiresAt: "2026-08-29T00:00:00.000Z" }), position("EARLY")]); const result = allocatePurchase(state, { ...command, confirmedFuelQuantity4dp: 50_000 }); expect(result.allocation.lines).toEqual([expect.objectContaining({ protectionTransactionId: "EARLY", allocatedQuantity4dp: 50_000, protectionChargeMinor: 0, quoteId: "QUOTE-EARLY" })]); });
  it("uses earliest acceptance and immutable transaction ID as deterministic tie-breakers", () => { const later = position("Z", { acceptedAt: "2026-08-20T11:00:00.000Z" }); const earlierB = position("B"); const earlierA = position("A"); const result = allocatePurchase(createAllocationState([later, earlierB, earlierA]), { ...command, confirmedFuelQuantity4dp: 250_000 }); expect(result.allocation.lines.map(({ protectionTransactionId }) => protectionTransactionId)).toEqual(["A", "B", "Z"]); });
  it("spans multiple protections and records overflow unprotected", () => { const result = allocatePurchase(createAllocationState([position("A"), position("B", { remainingQuantity4dp: 25_000 })]), command); expect(result.allocation).toMatchObject({ protectedQuantity4dp: 125_000, unprotectedQuantity4dp: 25_000, unprotectedReason: "PROTECTION_VOLUME_EXHAUSTED" }); expect(result.allocation.lines).toHaveLength(2); });
  it("matches customer, assigned vehicle and pool ownership", () => { const positions = [position("CUSTOMER"), position("VEHICLE", { owner: { type: "VEHICLE", ownerId: "VEHICLE-1" } }), position("POOL", { owner: { type: "POOL", ownerId: "POOL-1" } })]; const result = allocatePurchase(createAllocationState(positions), { ...command, vehicleId: "VEHICLE-1", protectionPoolId: "POOL-1", confirmedFuelQuantity4dp: 250_000 }); expect(result.allocation.lines.map(({ protectionTransactionId }) => protectionTransactionId)).toEqual(["CUSTOMER", "POOL", "VEHICLE"]); });
  it("requires exact country, currency and fuel-grade matching", () => { const positions = [position("COUNTRY", { countryCode: "CA" }), position("CURRENCY", { currency: "CAD" }), position("GRADE", { fuelGradeId: "PREMIUM" })]; const result = allocatePurchase(createAllocationState(positions), command); expect(result.allocation).toMatchObject({ protectedQuantity4dp: 0, unprotectedQuantity4dp: 150_000, unprotectedReason: "NO_ELIGIBLE_PROTECTION" }); });
  it("enforces exact station, provider and geography scope", () => { const positions = [position("STATION"), position("PROVIDER", { scope: { type: "PROVIDER", scopeId: "PROVIDER-1" } }), position("GEO", { scope: { type: "GEOGRAPHY", scopeId: "US-TX" } }), position("WRONG", { scope: { type: "GEOGRAPHY", scopeId: "US-CA" } })]; const result = allocatePurchase(createAllocationState(positions), { ...command, confirmedFuelQuantity4dp: 300_000 }); expect(result.allocation.lines.map(({ protectionTransactionId }) => protectionTransactionId)).toEqual(["GEO", "PROVIDER", "STATION"]); });
  it("excludes canceled, expired, not-yet-active and exhausted protection", () => { const positions = [position("CANCELED", { status: "CANCELED" }), position("EXPIRED", { expiresAt: "2026-08-27T08:00:00.000Z" }), position("FUTURE", { startsAt: "2026-08-27T10:00:00.000Z", expiresAt: "2026-08-28T10:00:00.000Z" }), position("EMPTY", { remainingQuantity4dp: 0 })]; expect(allocatePurchase(createAllocationState(positions), command).allocation.lines).toHaveLength(0); });
  it("does not allocate non-fuel spend", () => { const result = allocatePurchase(createAllocationState([position("A", { remainingQuantity4dp: 150_000 })]), command); expect(result.allocation).toMatchObject({ confirmedFuelQuantity4dp: 150_000, protectedQuantity4dp: 150_000, nonFuelAmountMinor: 500 }); });
  it("reduces remaining quantities without mutating the input state", () => { const state = createAllocationState([position("A")]); const result = allocatePurchase(state, { ...command, confirmedFuelQuantity4dp: 40_000 }); expect(state.positions[0]?.remainingQuantity4dp).toBe(100_000); expect(result.state.positions[0]?.remainingQuantity4dp).toBe(60_000); });
  it("replays the same allocation idempotently without consuming volume twice", () => { const first = allocatePurchase(createAllocationState([position("A")]), { ...command, confirmedFuelQuantity4dp: 40_000 }); const replay = allocatePurchase(first.state, { ...command, confirmedFuelQuantity4dp: 40_000 }); expect(replay.idempotentReplay).toBe(true); expect(replay.state.positions[0]?.remainingQuantity4dp).toBe(60_000); });
  it("rejects allocation idempotency-key reuse with changed purchase facts", () => { const first = allocatePurchase(createAllocationState([position("A")]), command); expect(() => allocatePurchase(first.state, { ...command, confirmedFuelQuantity4dp: 149_999 })).toThrow(/different command/i); });
  it("requires clearing evidence to agree with customer and currency", () => { expect(() => allocatePurchase(createAllocationState([position("A")]), { ...command, customerId: "CUSTOMER-2" })).toThrow(/clearing evidence/i); expect(() => allocatePurchase(createAllocationState([position("A")]), { ...command, currency: "CAD" })).toThrow(/clearing evidence/i); });
  it("pins pump-observation provenance and correlation lineage", () => { const result = allocatePurchase(createAllocationState([position("A")]), command); expect(result.allocation).toMatchObject({ actualPumpObservationId: "PUMP-1", provenance: "SIMULATED", correlationId: "CORR-1", allocationVersion: "allocation-engine@1.0.0" }); });
  it("rejects invalid quantities, timestamps and duplicate position IDs", () => { expect(() => createAllocationState([position("A"), position("A")])).toThrow(/unique/i); expect(() => allocatePurchase(createAllocationState([position("A")]), { ...command, confirmedFuelQuantity4dp: 0 })).toThrow(/positive/i); expect(() => allocatePurchase(createAllocationState([position("A")]), { ...command, purchasedAt: "invalid" })).toThrow(/timestamp/i); });
});
